=== PokeAPI/api-data/data/schema/v2/ability/$id/index.json
{
  "$schema": "http://json-schema.org/schema#",
  "type": "object",
  "properties": {
    "id": {
      "type": "integer"
    },
    "name": {
      "type": "string"
    },
    "is_main_series": {
      "type": "boolean"
    },
    "generation": {
      "$ref": "/schema/v2/named_api_resource.json"
    },
    "names": {
      "type": "array",
      "items": {
        "$ref": "/schema/v2/name.json"
      }
    },
    "effect_entries": {
      "type": "array",
      "items": {
        "$ref": "/schema/v2/verbose_effect.json"
      }
    },
    "effect_changes": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "version_group": {
            "$ref": "/schema/v2/named_api_resource.json"
          },
          "effect_entries": {
            "type": "array",
            "items": {
              "$ref": "/schema/v2/effect.json"
            }
          }
        },
        "required": [
          "effect_entries",
          "version_group"
        ]
      }
    },
    "flavor_text_entries": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "flavor_text": {
            "type": "string"
          },
          "language": {
            "$ref": "/schema/v2/named_api_resource.json"
          },
          "version_group": {
            "$ref": "/schema/v2/named_api_resource.json"
          }
        },
        "required": [
          "flavor_text",
          "language",
          "version_group"
        ]
      }
    },
    "pokemon": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "is_hidden": {
            "type": "boolean"
          },
          "slot": {
            "type": "integer"
          },
          "pokemon": {
            "$ref": "/schema/v2/named_api_resource.json"
          }
        },
        "required": [
          "is_hidden",
          "pokemon",
          "slot"
        ]
      }
    }
  },
  "required": [
    "effect_changes",
    "effect_entries",
    "flavor_text_entries",
    "generation",
    "id",
    "is_main_series",
    "name",
    "names",
    "pokemon"
  ]
}

=== PokeAPI/api-data/data/api/v2/ability/52/index.json
{
  "id": 52,
  "name": "hyper-cutter",
  "is_main_series": true,
  "generation": {
    "name": "generation-iii",
    "url": "/api/v2/generation/3/"
  },
  "names": [
    {
      "name": "かいりきバサミ",
      "language": {
        "name": "ja-hrkt",
        "url": "/api/v2/language/1/"
      }
    },
    {
      "name": "괴력집게",
      "language": {
        "name": "ko",
        "url": "/api/v2/language/3/"
      }
    },
    {
      "name": "怪力鉗",
      "language": {
        "name": "zh-hant",
        "url": "/api/v2/language/4/"
      }
    },
    {
      "name": "Hyper Cutter",
      "language": {
        "name": "fr",
        "url": "/api/v2/language/5/"
      }
    },
    {
      "name": "Scherenmacht",
      "language": {
        "name": "de",
        "url": "/api/v2/language/6/"
      }
    },
    {
      "name": "Corte Fuerte",
      "language": {
        "name": "es",
        "url": "/api/v2/language/7/"
      }
    },
    {
      "name": "Ipertaglio",
      "language": {
        "name": "it",
        "url": "/api/v2/language/8/"
      }
    },
    {
      "name": "Hyper Cutter",
      "language": {
        "name": "en",
        "url": "/api/v2/language/9/"
      }
    },
    {
      "name": "かいりきバサミ",
      "language": {
        "name": "ja",
        "url": "/api/v2/language/11/"
      }
    },
    {
      "name": "怪力钳",
      "language": {
        "name": "zh-hans",
        "url": "/api/v2/language/12/"
      }
    },
    {
      "name": "Corte Fuerte",
      "language": {
        "name": "es-419",
        "url": "/api/v2/language/14/"
      }
    }
  ],
  "effect_entries": [
    {
      "effect": "L'Attaque de ce Pokémon ne peut pas être baissée par d'autres Pokémon.\n\nCe talent n'empêche pas les baisses d'Attaque autres que les modifications de stat, telles que la baisse d'Attaque de la brûlure.  Ce Pokémon peut toujours recevoir des modifications d'Attaque négatives via Permucœur ou Permuforce.",
      "short_effect": "Empêche l'Attaque d'être baissée.",
      "language": {
        "name": "fr",
        "url": "/api/v2/language/5/"
      }
    },
    {
      "effect": "Pokémon mit dieser Fähigkeit kann der Angriff nicht gesenkt werden.\n\nDie Fähigkeit verhindert nur Statuswertveränderungen, der verminderte Angriff durch Verbrennung wird nicht verhindert. Pokémon mit dieser Fähigkeit können trotzdem negative Genauigkeit durch Statustausch oder Krafttausch übertragen werden.",
      "short_effect": "Verhindert das Absenken des Angriffs.",
      "language": {
        "name": "de",
        "url": "/api/v2/language/6/"
      }
    },
    {
      "effect": "This Pokémon's Attack cannot be lowered by other Pokémon.\n\nThis ability does not prevent any Attack losses other than stat modifiers, such as the Attack cut from a burn.  This Pokémon can still be passed negative Attack modifiers through Heart Swap or Power Swap.",
      "short_effect": "Prevents Attack from being lowered by other Pokémon.",
      "language": {
        "name": "en",
        "url": "/api/v2/language/9/"
      }
    }
  ],
  "effect_changes": [
    {
      "version_group": {
        "name": "emerald",
        "url": "/api/v2/version-group/6/"
      },
      "effect_entries": [
        {
          "effect": "N'a pas d'effet en dehors du combat.",
          "language": {
            "name": "fr",
            "url": "/api/v2/language/5/"
          }
        },
        {
          "effect": "Hat außerhalb vom Kampf keinen Effekt.",
          "language": {
            "name": "de",
            "url": "/api/v2/language/6/"
          }
        },
        {
          "effect": "This Pokémon's Attack cannot be lowered by other Pokémon. This ability does not prevent any Attack losses other than stat modifiers, such as the Attack cut from a burn.",
          "language": {
            "name": "en",
            "url": "/api/v2/language/9/"
          }
        }
      ]
    },
    {
      "version_group": {
        "name": "diamond-pearl",
        "url": "/api/v2/version-group/8/"
      },
      "effect_entries": [
        {
          "effect": "Double le rayon d'action de Coupe dans le monde extérieur si un Pokémon de l'équipe a ce talent.",
          "language": {
            "name": "fr",
            "url": "/api/v2/language/5/"
          }
        },
        {
          "effect": "Verdoppelt den Radius in dem Zerschneider Gras entfernt, wenn irgendein Pokémon im Team diese Fähigkeit hat.",
          "language": {
            "name": "de",
            "url": "/api/v2/language/6/"
          }
        },
        {
          "effect": "This Pokémon's Attack cannot be lowered by other Pokémon. This ability does not prevent any Attack losses other than stat modifiers, such as the Attack cut from a burn. Overworld: Doubles Cut's grass-cutting radius on the overworld if any party Pokémon has this ability.",
          "language": {
            "name": "en",
            "url": "/api/v2/language/9/"
          }
        }
      ]
    }
  ],
  "flavor_text_entries": [
    {
      "flavor_text": "Empêche réduction ATTAQUE.",
      "language": {
        "name": "fr",
        "url": "/api/v2/language/5/"
      },
      "version_group": {
        "name": "ruby-sapphire",
        "url": "/api/v2/version-group/5/"
      }
    },
    {
      "flavor_text": "Prevents ATTACK reduction.",
      "language": {
        "name": "en",
        "url": "/api/v2/language/9/"
      },
      "version_group": {
        "name": "ruby-sapphire",
        "url": "/api/v2/version-group/5/"
      }
    },
    {
      "flavor_text": "Empêche réduction ATTAQUE.",
      "language": {
        "name": "fr",
        "url": "/api/v2/language/5/"
      },
      "version_group": {
        "name": "emerald",
        "url": "/api/v2/version-group/6/"
      }
    },
    {
      "flavor_text": "Prevents ATTACK reduction.",
      "language": {
        "name": "en",
        "url": "/api/v2/language/9/"
      },
      "version_group": {
        "name": "emerald",
        "url": "/api/v2/version-group/6/"
      }
    },
    {
      "flavor_text": "Empêche réduction ATTAQUE.",
      "language": {
        "name": "fr",
        "url": "/api/v2/language/5/"
      },
      "version_group": {
        "name": "firered-leafgreen",
        "url": "/api/v2/version-group/7/"
      }
    },
    {
      "flavor_text": "Prevents ATTACK reduction.",
      "language": {
        "name": "en",
        "url": "/api/v2/language/9/"
      },
      "version_group": {
        "name": "firered-leafgreen",
        "url": "/api/v2/version-group/7/"
      }
    },
    {
      "flavor_text": "Empêche la réduction de l'Attaque.",
      "language": {
        "name": "fr",
        "url": "/api/v2/language/5/"
      },
      "version_group": {
        "name": "diamond-pearl",
        "url": "/api/v2/version-group/8/"
      }
    },
    {
      "flavor_text": "Prevents the Attack stat\nfrom being lowered.",
      "language": {
        "name": "en",
        "url": "/api/v2/language/9/"
      },
      "version_group": {
        "name": "diamond-pearl",
        "url": "/api/v2/version-group/8/"
      }
    },
    {
      "flavor_text": "Empêche la réduction de l'Attaque.",
      "language": {
        "name": "fr",
        "url": "/api/v2/language/5/"
      },
      "version_group": {
        "name": "platinum",
        "url": "/api/v2/version-group/9/"
      }
    },
    {
      "flavor_text": "Prevents the Attack stat\nfrom being lowered.",
      "language": {
        "name": "en",
        "url": "/api/v2/language/9/"
      },
      "version_group": {
        "name": "platinum",
        "url": "/api/v2/version-group/9/"
      }
    },
    {
      "flavor_text": "Empêche la réduction de l'Attaque.",
      "language": {
        "name": "fr",
        "url": "/api/v2/language/5/"
      },
      "version_group": {
        "name": "heartgold-soulsilver",
        "url": "/api/v2/version-group/10/"
      }
    },
    {
      "flavor_text": "Prevents the Attack\nstat from being lowered.",
      "language": {
        "name": "en",
        "url": "/api/v2/language/9/"
      },
      "version_group": {
        "name": "heartgold-soulsilver",
        "url": "/api/v2/version-group/10/"
      }
    },
    {
      "flavor_text": "Empêche la réduction de l'Attaque.",
      "language": {
        "name": "fr",
        "url": "/api/v2/language/5/"
      },
      "version_group": {
        "name": "black-white",
        "url": "/api/v2/version-group/11/"
      }
    },
    {
      "flavor_text": "Prevents other Pokémon\nfrom lowering Attack stat.",
      "language": {
        "name": "en",
        "url": "/api/v2/language/9/"
      },
      "version_group": {
        "name": "black-white",
        "url": "/api/v2/version-group/11/"
      }
    },
    {
      "flavor_text": "Empêche la réduction de l'Attaque.",
      "language": {
        "name": "fr",
        "url": "/api/v2/language/5/"
      },
      "version_group": {
        "name": "xd",
        "url": "/api/v2/version-group/13/"
      }
    },
    {
      "flavor_text": "Empêche la réduction de l'Attaque.",
      "language": {
        "name": "fr",
        "url": "/api/v2/language/5/"
      },
      "version_group": {
        "name": "black-2-white-2",
        "url": "/api/v2/version-group/14/"
      }
    },
    {
      "flavor_text": "Prevents other Pokémon\nfrom lowering Attack stat.",
      "language": {
        "name": "en",
        "url": "/api/v2/language/9/"
      },
      "version_group": {
        "name": "black-2-white-2",
        "url": "/api/v2/version-group/14/"
      }
    },
    {
      "flavor_text": "あいてに　こうげきを\nさげられない。",
      "language": {
        "name": "ja-hrkt",
        "url": "/api/v2/language/1/"
      },
      "version_group": {
        "name": "x-y",
        "url": "/api/v2/version-group/15/"
      }
    },
    {
      "flavor_text": "상대가 공격을\n떨어뜨리지 못한다.",
      "language": {
        "name": "ko",
        "url": "/api/v2/language/3/"
      },
      "version_group": {
