=== PokeAPI/api-data/data/schema/v2/berry/$id/index.json
{
  "$schema": "http://json-schema.org/schema#",
  "type": "object",
  "properties": {
    "id": {
      "type": "integer"
    },
    "name": {
      "type": "string"
    },
    "growth_time": {
      "type": [
        "integer",
        "null"
      ]
    },
    "max_harvest": {
      "type": [
        "integer",
        "null"
      ]
    },
    "natural_gift_power": {
      "type": [
        "integer",
        "null"
      ]
    },
    "size": {
      "type": [
        "integer",
        "null"
      ]
    },
    "smoothness": {
      "type": [
        "integer",
        "null"
      ]
    },
    "soil_dryness": {
      "type": [
        "integer",
        "null"
      ]
    },
    "firmness": {
      "anyOf": [
        {
          "type": "null"
        },
        {
          "$ref": "/schema/v2/named_api_resource.json"
        }
      ]
    },
    "flavors": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "potency": {
            "type": "integer"
          },
          "flavor": {
            "$ref": "/schema/v2/named_api_resource.json"
          }
        },
        "required": [
          "flavor",
          "potency"
        ]
      }
    },
    "item": {
      "$ref": "/schema/v2/named_api_resource.json"
    },
    "natural_gift_type": {
      "anyOf": [
        {
          "type": "null"
        },
        {
          "$ref": "/schema/v2/named_api_resource.json"
        }
      ]
    }
  },
  "required": [
    "firmness",
    "flavors",
    "growth_time",
    "id",
    "item",
    "max_harvest",
    "name",
    "natural_gift_power",
    "natural_gift_type",
    "size",
    "smoothness",
    "soil_dryness"
  ]
}

=== PokeAPI/api-data/data/api/v2/berry/33/index.json
{
  "id": 33,
  "name": "watmel",
  "growth_time": 15,
  "max_harvest": 15,
  "natural_gift_power": 80,
  "size": 250,
  "smoothness": 35,
  "soil_dryness": 8,
  "firmness": {
    "name": "soft",
    "url": "/api/v2/berry-firmness/2/"
  },
  "flavors": [
    {
      "potency": 0,
      "flavor": {
        "name": "spicy",
        "url": "/api/v2/berry-flavor/1/"
      }
    },
    {
      "potency": 0,
      "flavor": {
        "name": "dry",
        "url": "/api/v2/berry-flavor/2/"
      }
    },
    {
      "potency": 30,
      "flavor": {
        "name": "sweet",
        "url": "/api/v2/berry-flavor/3/"
      }
    },
    {
      "potency": 10,
      "flavor": {
        "name": "bitter",
        "url": "/api/v2/berry-flavor/4/"
      }
    },
    {
      "potency": 0,
      "flavor": {
        "name": "sour",
        "url": "/api/v2/berry-flavor/5/"
      }
    }
  ],
  "item": {
    "name": "watmel-berry",
    "url": "/api/v2/item/158/"
  },
  "natural_gift_type": {
    "name": "fire",
    "url": "/api/v2/type/10/"
  }
}
