=== PokeAPI/api-data/data/schema/v2/encounter-method/$id/index.json
{
  "$schema": "http://json-schema.org/schema#",
  "type": "object",
  "properties": {
    "id": {
      "type": "integer"
    },
    "name": {
      "type": "string"
    },
    "order": {
      "type": "integer"
    },
    "names": {
      "type": "array",
      "items": {
        "$ref": "/schema/v2/name.json"
      }
    }
  },
  "required": [
    "id",
    "name",
    "names",
    "order"
  ]
}

=== PokeAPI/api-data/data/api/v2/encounter-method/5/index.json
{
  "id": 5,
  "name": "surf",
  "order": 14,
  "names": [
    {
      "name": "Surfen",
      "language": {
        "name": "de",
        "url": "/api/v2/language/6/"
      }
    },
    {
      "name": "Surfing",
      "language": {
        "name": "en",
        "url": "/api/v2/language/9/"
      }
    },
    {
      "name": "En surfant",
      "language": {
        "name": "fr",
        "url": "/api/v2/language/5/"
      }
    }
  ]
}
