=== PokeAPI/api-data/data/schema/v2/pokedex/$id/index.json
{
  "$schema": "http://json-schema.org/schema#",
  "type": "object",
  "properties": {
    "id": {
      "type": "integer"
    },
    "name": {
      "type": "string"
    },
    "is_main_series": {
      "type": "boolean"
    },
    "descriptions": {
      "type": "array",
      "items": {
        "$ref": "/schema/v2/description.json"
      }
    },
    "names": {
      "type": "array",
      "items": {
        "$ref": "/schema/v2/name.json"
      }
    },
    "pokemon_entries": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "entry_number": {
            "type": "integer"
          },
          "pokemon_species": {
            "$ref": "/schema/v2/named_api_resource.json"
          }
        },
        "required": [
          "entry_number",
          "pokemon_species"
        ]
      }
    },
    "region": {
      "anyOf": [
        {
          "type": "null"
        },
        {
          "$ref": "/schema/v2/named_api_resource.json"
        }
      ]
    },
    "version_groups": {
      "type": "array",
      "items": {
        "$ref": "/schema/v2/named_api_resource.json"
      }
    }
  },
  "required": [
    "descriptions",
    "id",
    "is_main_series",
    "name",
    "names",
    "pokemon_entries",
    "region",
    "version_groups"
  ]
}

=== PokeAPI/api-data/data/api/v2/pokedex/29/index.json
{
    "descriptions": [
        {
            "description": "Pok\u00e9dex de Couronneige",
            "language": {
                "name": "fr",
                "url": "/api/v2/language/5/"
            }
        },
        {
            "description": "Kronen-Schneelande Dex",
            "language": {
                "name": "de",
                "url": "/api/v2/language/6/"
            }
        },
        {
            "description": "Pok\u00e9dex regional de Nieves de la Corona",
            "language": {
                "name": "es",
                "url": "/api/v2/language/7/"
            }
        },
        {
            "description": "Crown Tundra dex",
            "language": {
                "name": "en",
                "url": "/api/v2/language/9/"
            }
        },
        {
            "description": "Pok\u00e9dex regional de Nieves de la Corona",
            "language": {
                "name": "es-419",
                "url": "/api/v2/language/14/"
            }
        }
    ],
    "id": 29,
    "is_main_series": true,
    "name": "crown-tundra",
    "names": [
        {
            "language": {
                "name": "fr",
                "url": "/api/v2/language/5/"
            },
            "name": "Couronneige"
        },
        {
            "language": {
                "name": "de",
                "url": "/api/v2/language/6/"
            },
            "name": "Kronen-Schneelande"
        },
        {
            "language": {
                "name": "es",
                "url": "/api/v2/language/7/"
            },
            "name": "Nieves de la Corona"
        },
        {
            "language": {
                "name": "en",
                "url": "/api/v2/language/9/"
            },
            "name": "Crown Tundra"
        },
        {
            "language": {
                "name": "es-419",
                "url": "/api/v2/language/14/"
            },
            "name": "Nieves de la Corona"
        }
    ],
    "pokemon_entries": [
        {
            "entry_number": 1,
            "pokemon_species": {
                "name": "snom",
                "url": "/api/v2/pokemon-species/872/"
            }
        },
        {
            "entry_number": 2,
            "pokemon_species": {
                "name": "frosmoth",
                "url": "/api/v2/pokemon-species/873/"
            }
        },
        {
            "entry_number": 3,
            "pokemon_species": {
                "name": "wooloo",
                "url": "/api/v2/pokemon-species/831/"
            }
        },
        {
            "entry_number": 4,
            "pokemon_species": {
                "name": "dubwool",
                "url": "/api/v2/pokemon-species/832/"
            }
        },
        {
            "entry_number": 5,
            "pokemon_species": {
                "name": "skwovet",
                "url": "/api/v2/pokemon-species/819/"
            }
        },
        {
            "entry_number": 6,
            "pokemon_species": {
                "name": "greedent",
                "url": "/api/v2/pokemon-species/820/"
            }
        },
        {
            "entry_number": 7,
            "pokemon_species": {
                "name": "swinub",
                "url": "/api/v2/pokemon-species/220/"
            }
        },
        {
            "entry_number": 8,
            "pokemon_species": {
                "name": "piloswine",
                "url": "/api/v2/pokemon-species/221/"
            }
        },
        {
            "entry_number": 9,
            "pokemon_species": {
                "name": "mamoswine",
                "url": "/api/v2/pokemon-species/473/"
            }
        },
        {
            "entry_number": 10,
            "pokemon_species": {
                "name": "mime-jr",
                "url": "/api/v2/pokemon-species/439/"
            }
        },
        {
            "entry_number": 11,
            "pokemon_species": {
                "name": "mr-mime",
                "url": "/api/v2/pokemon-species/122/"
            }
        },
        {
            "entry_number": 12,
            "pokemon_species": {
                "name": "mr-rime",
                "url": "/api/v2/pokemon-species/866/"
            }
        },
        {
            "entry_number": 13,
            "pokemon_species": {
                "name": "smoochum",
                "url": "/api/v2/pokemon-species/238/"
            }
        },
        {
            "entry_number": 14,
            "pokemon_species": {
                "name": "jynx",
                "url": "/api/v2/pokemon-species/124/"
            }
        },
        {
            "entry_number": 15,
            "pokemon_species": {
                "name": "elekid",
                "url": "/api/v2/pokemon-species/239/"
            }
        },
        {
            "entry_number": 16,
            "pokemon_species": {
                "name": "electabuzz",
                "url": "/api/v2/pokemon-species/125/"
            }
        },
        {
            "entry_number": 17,
            "pokemon_species": {
                "name": "electivire",
                "url": "/api/v2/pokemon-species/466/"
            }
        },
        {
            "entry_number": 18,
            "pokemon_species": {
                "name": "magby",
                "url": "/api/v2/pokemon-species/240/"
            }
        },
        {
            "entry_number": 19,
            "pokemon_species": {
                "name": "magmar",
                "url": "/api/v2/pokemon-species/126/"
            }
        },
        {
            "entry_number": 20,
            "pokemon_species": {
                "name": "magmortar",
                "url": "/api/v2/pokemon-species/467/"
            }
        },
        {
            "entry_number": 21,
            "pokemon_species": {
                "name": "audino",
                "url": "/api/v2/pokemon-species/531/"
            }
        },
        {
            "entry_number": 22,
            "pokemon_species": {
                "name": "vanillite",
                "url": "/api/v2/pokemon-species/582/"
            }
        },
        {
            "entry_number": 23,
            "pokemon_species": {
                "name": "vanillish",
                "url": "/api/v2/pokemon-species/583/"
            }
        },
        {
            "entry_number": 24,
            "pokemon_species": {
                "name": "vanilluxe",
                "url": "/api/v2/pokemon-species/584/"
            }
        },
        {
            "entry_number": 25,
            "pokemon_species": {
                "name": "snorunt",
                "url": "/api/v2/pokemon-species/361/"
            }
        },
        {
            "entry_number": 26,
            "pokemon_species": {
                "name": "glalie",
                "url": "/api/v2/pokemon-species/362/"
            }
        },
        {
            "entry_number": 27,
            "pokemon_species": {
                "name": "froslass",
                "url": "/api/v2/pokemon-species/478/"
            }
        },
        {
            "entry_number": 28,
            "pokemon_species": {
                "name": "sneasel",
                "url": "/api/v2/pokemon-species/215/"
            }
        },
        {
            "entry_number": 29,
            "pokemon_species": {
                "name": "weavile",
                "url": "/api/v2/pokemon-species/461/"
            }
        },
        {
            "entry_number": 30,
            "pokemon_species": {
                "name": "cryogonal",
                "url": "/api/v2/pokemon-species/615/"
            }
        },
        {
            "entry_number": 31,
            "pokemon_species": {
                "name": "snover",
                "url": "/api/v2/pokemon-species/459/"
            }
        },
        {
            "entry_number": 32,
            "pokemon_species": {
                "name": "abomasnow",
                "url": "/api/v2/pokemon-species/460/"
            }
        },
        {
            "entry_number": 33,
            "pokemon_species": {
                "name": "phantump",
                "url": "/api/v2/pokemon-species/708/"
            }
        },
        {
            "entry_number": 34,
            "pokemon_species": {
                "name": "trevenant",
                "url": "/api/v2/pokemon-species/709/"
            }
        },
        {
            "entry_number": 35,
            "pokemon_species": {
                "name": "swablu",
                "url": "/api/v2/pokemon-species/333/"
            }
        },
        {
            "entry_number": 36,
            "pokemon_species": {
                "name": "altaria",
                "url": "/api/v2/pokemon-species/334/"
            }
        },
        {
            "entry_number": 37,
            "pokemon_species": {
                "name": "impidimp",
                "url": "/api/v2/pokemon-species/859/"
            }
        },
        {
            "entry_number": 38,
            "pokemon_species": {
                "name": "morgrem",
                "url": "/api/v2/pokemon-species/860/"
            }
        },
        {
            "entry_number": 39,
            "pokemon_species": {
                "name": "grimmsnarl",
                "url": "/api/v2/pokemon-species/861/"
            }
        },
        {
            "entry_number": 40,
            "pokemon_species": {
                "name": "hatenna",
                "url": "/api/v2/pokemon-species/856/"
            }
        },
        {
            "entry_number": 41,
            "pokemon_species": {
                "name": "hattrem",
                "url": "/api/v2/pokemon-species/857/"
            }
        },
        {
            "entry_number": 42,
            "pokemon_species": {
                "name": "hatterene",
                "url": "/api/v2/pokemon-species/858/"
            }
        },
        {
