=== PokeAPI/api-data/data/schema/v2/location-area/$id/index.json
{
    "$schema": "http://json-schema.org/schema#",
    "properties": {
        "encounter_method_rates": {
            "items": {
                "properties": {
                    "encounter_method": {
                        "$ref": "/schema/v2/named_api_resource.json"
                    },
                    "version_details": {
                        "items": {
                            "properties": {
                                "rate": {
                                    "type": "integer"
                                },
                                "version": {
                                    "$ref": "/schema/v2/named_api_resource.json"
                                }
                            },
                            "required": [
                                "rate",
                                "version"
                            ],
                            "type": "object"
                        },
                        "type": "array"
                    }
                },
                "required": [
                    "encounter_method",
                    "version_details"
                ],
                "type": "object"
            },
            "type": "array"
        },
        "game_index": {
            "type": "integer"
        },
        "id": {
            "type": "integer"
        },
        "location": {
            "$ref": "/schema/v2/named_api_resource.json"
        },
        "name": {
            "type": "string"
        },
        "names": {
            "items": {
                "$ref": "/schema/v2/name.json"
            },
            "type": "array"
        },
        "pokemon_encounters": {
            "items": {
                "properties": {
                    "pokemon": {
                        "$ref": "/schema/v2/named_api_resource.json"
                    },
                    "version_details": {
                        "items": {
                            "properties": {
                                "encounter_details": {
                                    "items": {
                                        "properties": {
                                            "chance": {
                                                "type": "integer"
                                            },
                                            "condition_values": {
                                                "items": {
                                                    "$ref": "/schema/v2/named_api_resource.json"
                                                },
                                                "type": "array"
                                            },
                                            "max_level": {
                                                "type": "integer"
                                            },
                                            "method": {
                                                "$ref": "/schema/v2/named_api_resource.json"
                                            },
                                            "min_level": {
                                                "type": "integer"
                                            },
                                            "pokemon_details": {
                                                "anyOf": [
                                                    {
                                                        "type": "null"
                                                    },
                                                    {
                                                        "properties": {
                                                            "always_shiny": {
                                                                "type": "boolean"
                                                            },
                                                            "is_alpha": {
                                                                "type": "boolean"
                                                            },
                                                            "min_perfect_ivs": {
                                                                "type": "null"
                                                            },
                                                            "never_shiny": {
                                                                "type": "boolean"
                                                            }
                                                        },
                                                        "required": [
                                                            "always_shiny",
                                                            "is_alpha",
                                                            "min_perfect_ivs",
                                                            "never_shiny"
                                                        ],
                                                        "type": "object"
                                                    }
                                                ]
                                            }
                                        },
                                        "required": [
                                            "chance",
                                            "condition_values",
                                            "max_level",
                                            "method",
                                            "min_level",
                                            "pokemon_details"
                                        ],
                                        "type": "object"
                                    },
                                    "type": "array"
                                },
                                "max_chance": {
                                    "type": "integer"
                                },
                                "version": {
                                    "$ref": "/schema/v2/named_api_resource.json"
                                }
                            },
                            "required": [
                                "encounter_details",
                                "max_chance",
                                "version"
                            ],
                            "type": "object"
                        },
                        "type": "array"
                    }
                },
                "required": [
                    "pokemon",
                    "version_details"
                ],
                "type": "object"
            },
            "type": "array"
        }
    },
    "required": [
        "encounter_method_rates",
        "game_index",
        "id",
        "location",
        "name",
        "names",
        "pokemon_encounters"
    ],
    "type": "object"
}

=== PokeAPI/api-data/data/api/v2/location-area/1207/index.json
{
    "encounter_method_rates": [],
    "game_index": 0,
    "id": 1207,
    "location": {
        "name": "hoenn-route-104",
        "url": "/api/v2/location/452/"
    },
    "name": "hoenn-route-104-north-oras",
    "names": [],
    "pokemon_encounters": [
        {
            "pokemon": {
                "name": "zigzagoon",
                "url": "/api/v2/pokemon/263/"
            },
            "version_details": [
                {
                    "encounter_details": [
                        {
                            "chance": 95,
                            "condition_values": [],
                            "max_level": 2,
                            "method": {
                                "name": "horde",
                                "url": "/api/v2/encounter-method/44/"
                            },
                            "min_level": 2,
                            "pokemon_details": null
                        }
                    ],
                    "max_chance": 95,
                    "version": {
                        "name": "omega-ruby",
                        "url": "/api/v2/version/25/"
                    }
                },
                {
                    "encounter_details": [
                        {
                            "chance": 95,
                            "condition_values": [],
                            "max_level": 2,
                            "method": {
                                "name": "horde",
                                "url": "/api/v2/encounter-method/44/"
                            },
                            "min_level": 2,
                            "pokemon_details": null
                        }
                    ],
                    "max_chance": 95,
                    "version": {
                        "name": "alpha-sapphire",
                        "url": "/api/v2/version/26/"
                    }
                }
            ]
        },
        {
            "pokemon": {
                "name": "taillow",
                "url": "/api/v2/pokemon/276/"
            },
            "version_details": [
                {
                    "encounter_details": [
                        {
                            "chance": 5,
                            "condition_values": [],
                            "max_level": 3,
                            "method": {
                                "name": "horde",
                                "url": "/api/v2/encounter-method/44/"
                            },
                            "min_level": 3,
                            "pokemon_details": null
                        }
                    ],
                    "max_chance": 5,
                    "version": {
                        "name": "omega-ruby",
                        "url": "/api/v2/version/25/"
                    }
                },
                {
                    "encounter_details": [
                        {
                            "chance": 5,
                            "condition_values": [],
                            "max_level": 3,
                            "method": {
                                "name": "horde",
                                "url": "/api/v2/encounter-method/44/"
                            },
                            "min_level": 3,
                            "pokemon_details": null
                        }
                    ],
                    "max_chance": 5,
                    "version": {
                        "name": "alpha-sapphire",
                        "url": "/api/v2/version/26/"
                    }
                }
            ]
        }
    ]
}

=== PokeAPI/api-data/data/api/v2/location-area/1665/index.json
{
    "encounter_method_rates": [],
    "game_index": 0,
    "id": 1665,
    "location": {
        "name": "olivine-city",
        "url": "/api/v2/location/85/"
    },
    "name": "olivine-city-gym",
    "names": [
        {
            "language": {
                "name": "en",
                "url": "/api/v2/language/9/"
            },
            "name": "Olivine City Gym"
        }
    ],
    "pokemon_encounters": [
        {
            "pokemon": {
                "name": "steelix",
                "url": "/api/v2/pokemon/208/"
            },
            "version_details": [
                {
                    "encounter_details": [
                        {
                            "chance": 100,
                            "condition_values": [
                                {
                                    "name": "trade-any-pokemon",
                                    "url": "/api/v2/encounter-condition-value/361/"
                                }
                            ],
                            "max_level": 100,
                            "method": {
                                "name": "npc-trade",
                                "url": "/api/v2/encounter-method/36/"
                            },
                            "min_level": 1,
                            "pokemon_details": null
                        }
                    ],
                    "max_chance": 100,
                    "version": {
                        "name": "heartgold",
                        "url": "/api/v2/version/15/"
                    }
                },
                {
                    "encounter_details": [
                        {
                            "chance": 100,
                            "condition_values": [
                                {
                                    "name": "trade-any-pokemon",
                                    "url": "/api/v2/encounter-condition-value/361/"
                                }
                            ],
                            "max_level": 100,
                            "method": {
                                "name": "npc-trade",
                                "url": "/api/v2/encounter-method/36/"
                            },
                            "min_level": 1,
                            "pokemon_details": null
                        }
                    ],
                    "max_chance": 100,
                    "version": {
                        "name": "soulsilver",
                        "url": "/api/v2/version/16/"
                    }
                }
            ]
        }
    ]
}

=== PokeAPI/api-data/data/api/v2/location-area/1340/index.json
{
  "id": 1340,
  "name": "unova-route-2-hidden-grotto",
  "game_index": 15,
  "encounter_method_rates": [
    {
      "encounter_method": {
        "name": "hidden-grotto",
        "url": "/api/v2/encounter-method/54/"
      },
      "version_details": [
        {
          "rate": 20,
          "version": {
            "name": "black-2",
            "url": "/api/v2/version/21/"
          }
        },
        {
          "rate": 20,
          "version": {
            "name": "white-2",
            "url": "/api/v2/version/22/"
          }
        }
      ]
    }
  ],
  "location": {
    "name": "unova-route-2",
    "url": "/api/v2/location/357/"
  },
  "names": [
    {
      "name": "Route 2 (Hidden Grotto)",
      "language": {
        "name": "en",
        "url": "/api/v2/language/9/"
      }
    },
    {
      "name": "Route 2 (Trouée Cachée)",
      "language": {
        "name": "fr",
        "url": "/api/v2/language/5/"
      }
    }
  ],
  "pokemon_encounters": [
    {
      "pokemon": {
        "name": "nidoran-f",
        "url": "/api/v2/pokemon/29/"
      },
      "version_details": [
        {
          "version": {
            "name": "black-2",
            "url": "/api/v2/version/21/"
          },
          "max_chance": 10,
          "encounter_details": [
            {
              "min_level": 55,
              "max_level": 59,
              "chance": 10,
              "method": {
                "name": "hidden-grotto",
                "url": "/api/v2/encounter-method/54/"
              },
              "condition_values": [],
              "pokemon_details": null
            }
          ]
        },
        {
          "version": {
            "name": "white-2",
            "url": "/api/v2/version/22/"
          },
          "max_chance": 10,
          "encounter_details": [
            {
              "min_level": 55,
              "max_level": 59,
              "chance": 10,
              "method": {
                "name": "hidden-grotto",
                "url": "/api/v2/encounter-method/54/"
              },
              "condition_values": [],
              "pokemon_details": null
            }
          ]
        }
      ]
    },
    {
      "pokemon": {
        "name": "nidoran-m",
        "url": "/api/v2/pokemon/32/"
      },
      "version_details": [
        {
          "version": {
            "name": "black-2",
            "url": "/api/v2/version/21/"
          },
          "max_chance": 10,
          "encounter_details": [
            {
              "min_level": 55,
              "max_level": 59,
              "chance": 10,
              "method": {
                "name": "hidden-grotto",
                "url": "/api/v2/encounter-method/54/"
              },
              "condition_values": [],
              "pokemon_details": null
            }
          ]
        },
        {
          "version": {
            "name": "white-2",
            "url": "/api/v2/version/22/"
          },
          "max_chance": 10,
          "encounter_details": [
            {
              "min_level": 55,
              "max_level": 59,
              "chance": 10,
              "method": {
                "name": "hidden-grotto",
                "url": "/api/v2/encounter-method/54/"
              },
              "condition_values": [],
              "pokemon_details": null
            }
          ]
        }
      ]
    },
    {
      "pokemon": {
        "name": "granbull",
        "url": "/api/v2/pokemon/210/"
      },
      "version_details": [
        {
          "version": {
            "name": "black-2",
            "url": "/api/v2/version/21/"
          },
          "max_chance": 5,
          "encounter_details": [
            {
              "min_level": 55,
              "max_level": 59,
              "chance": 5,
              "method": {
                "name": "hidden-grotto",
                "url": "/api/v2/encounter-method/54/"
              },
              "condition_values": [],
              "pokemon_details": null
            }
          ]
        },
        {
          "version": {
            "name": "white-2",
            "url": "/api/v2/version/22/"
          },
          "max_chance": 5,
          "encounter_details": [
            {
              "min_level": 55,
              "max_level": 59,
              "chance": 5,
              "method": {
                "name": "hidden-grotto",
                "url": "/api/v2/encounter-method/54/"
              },
              "condition_values": [],
              "pokemon_details": null
            }
          ]
        }
      ]
    },
    {
      "pokemon": {
        "name": "watchog",
        "url": "/api/v2/pokemon/505/"
      },
      "version_details": [
        {
          "version": {
            "name": "black-2",
            "url": "/api/v2/version/21/"
          },
          "max_chance": 75,
          "encounter_details": [
            {
              "min_level": 55,
              "max_level": 59,
              "chance": 75,
              "method": {
                "name": "hidden-grotto",
                "url": "/api/v2/encounter-method/54/"
              },
              "condition_values": [],
              "pokemon_details": null
            }
          ]
        },
        {
          "version": {
            "name": "white-2",
            "url": "/api/v2/version/22/"
          },
          "max_chance": 75,
          "encounter_details": [
            {
              "min_level": 55,
              "max_level": 59,
              "chance": 75,
              "method": {
                "name": "hidden-grotto",
                "url": "/api/v2/encounter-method/54/"
              },
              "condition_values": [],
              "pokemon_details": null
            }
          ]
        }
      ]
    }
  ]
}

=== PokeAPI/api-data/data/api/v2/location-area/712/index.json
{
  "id": 712,
  "name": "laverre-city-area",
  "game_index": 0,
  "encounter_method_rates": [],
  "location": {
    "name": "laverre-city",
    "url": "/api/v2/location/633/"
  },
  "names": [
    {
      "name": "Laverre City",
      "language": {
        "name": "en",
        "url": "/api/v2/language/9/"
      }
    },
    {
      "name": "Romantia City",
      "language": {
        "name": "de",
        "url": "/api/v2/language/6/"
      }
    },
    {
      "name": "Romant-sous-Bois",
      "language": {
        "name": "fr",
        "url": "/api/v2/language/5/"
      }
    }
  ],
  "pokemon_encounters": [
    {
      "pokemon": {
        "name": "poliwag",
        "url": "/api/v2/pokemon/60/"
      },
      "version_details": [
        {
          "version": {
            "name": "x",
            "url": "/api/v2/version/23/"
          },
          "max_chance": 100,
          "encounter_details": [
            {
              "min_level": 15,
              "max_level": 15,
              "chance": 60,
              "method": {
                "name": "old-rod",
                "url": "/api/v2/encounter-method/2/"
              },
              "condition_values": [],
              "pokemon_details": null
            },
            {
              "min_level": 15,
              "max_level": 15,
              "chance": 35,
              "method": {
                "name": "old-rod",
                "url": "/api/v2/encounter-method/2/"
              },
              "condition_values": [],
              "pokemon_details": null
            },
            {
              "min_level": 15,
              "max_level": 15,
              "chance": 5,
              "method": {
                "name": "old-rod",
                "url": "/api/v2/encounter-method/2/"
              },
              "condition_values": [],
              "pokemon_details": null
            }
          ]
        },
        {
          "version": {
            "name": "y",
            "url": "/api/v2/version/24/"
          },
          "max_chance": 100,
          "encounter_details": [
            {
              "min_level": 15,
              "max_level": 15,
              "chance": 60,
              "method": {
                "name": "old-rod",
                "url": "/api/v2/encounter-method/2/"
              },
              "condition_values": [],
              "pokemon_details": null
            },
            {
              "min_level": 15,
              "max_level": 15,
              "chance": 35,
              "method": {
                "name": "old-rod",
                "url": "/api/v2/encounter-method/2/"
              },
              "condition_values": [],
              "pokemon_details": null
            },
            {
              "min_level": 15,
              "max_level": 15,
              "chance": 5,
              "method": {
                "name": "old-rod",
                "url": "/api/v2/encounter-method/2/"
              },
              "condition_values": [],
              "pokemon_details": null
            }
          ]
        }
      ]
    },
    {
      "pokemon": {
        "name": "poliwhirl",
        "url": "/api/v2/pokemon/61/"
      },
      "version_details": [
        {
          "version": {
            "name": "x",
            "url": "/api/v2/version/23/"
          },
          "max_chance": 100,
          "encounter_details": [
            {
              "min_level": 25,
              "max_level": 25,
              "chance": 35,
              "method": {
                "name": "good-rod",
                "url": "/api/v2/encounter-method/3/"
              },
              "condition_values": [],
              "pokemon_details": null
            },
            {
              "min_level": 35,
              "max_level": 35,
              "chance": 60,
              "method": {
                "name": "super-rod",
                "url": "/api/v2/encounter-method/4/"
              },
              "condition_values": [],
              "pokemon_details": null
            },
            {
              "min_level": 35,
              "max_level": 35,
              "chance": 5,
              "method": {
                "name": "super-rod",
                "url": "/api/v2/encounter-method/4/"
              },
              "condition_values": [],
              "pokemon_details": null
            }
          ]
        },
        {
          "version": {
            "name": "y",
            "url": "/api/v2/version/24/"
          },
          "max_chance": 100,
          "encounter_details": [
            {
              "min_level": 25,
              "max_level": 25,
              "chance": 35,
              "method": {
                "name": "good-rod",
                "url": "/api/v2/encounter-method/3/"
              },
              "condition_values": [],
              "pokemon_details": null
            },
            {
              "min_level": 35,
              "max_level": 35,
              "chance": 60,
              "method": {
                "name": "super-rod",
                "url": "/api/v2/encounter-method/4/"
              },
              "condition_values": [],
              "pokemon_details": null
            },
            {
              "min_level": 35,
              "max_level": 35,
              "chance": 5,
              "method": {
                "name": "super-rod",
                "url": "/api/v2/encounter-method/4/"
              },
              "condition_values": [],
              "pokemon_details": null
            }
          ]
        }
      ]
    },
    {
      "pokemon": {
        "name": "basculin-red-striped",
        "url": "/api/v2/pokemon/550/"
      },
      "version_details": [
        {
          "version": {
            "name": "x",
            "url": "/api/v2/version/23/"
          },
          "max_chance": 35,
          "encounter_details": [
            {
              "min_level": 35,
              "max_level": 35,
              "chance": 35,
              "method": {
                "name": "super-rod",
                "url": "/api/v2/encounter-method/4/"
              },
              "condition_values": [],
              "pokemon_details": null
            }
          ]
        },
        {
          "version": {
            "name": "y",
            "url": "/api/v2/version/24/"
          },
          "max_chance": 65,
          "encounter_details": [
            {
              "min_level": 25,
              "max_level": 25,
              "chance": 60,
              "method": {
                "name": "good-rod",
                "url": "/api/v2/encounter-method/3/"
              },
              "condition_values": [],
              "pokemon_details": null
            },
            {
              "min_level": 25,
              "max_level": 25,
              "chance": 5,
              "method": {
                "name": "good-rod",
                "url": "/api/v2/encounter-method/3/"
              },
              "condition_values": [],
              "pokemon_details": null
            }
          ]
        }
      ]
    },
    {
      "pokemon": {
        "name": "basculin-blue-striped",
        "url": "/api/v2/pokemon/10016/"
      },
      "version_details": [
        {
          "version": {
            "name": "x",
            "url": "/api/v2/version/23/"
          },
          "max_chance": 65,
          "encounter_details": [
            {
              "min_level": 25,
              "max_level": 25,
              "chance": 60,
              "method": {
                "name": "good-rod",
                "url": "/api/v2/encounter-method/3/"
              },
              "condition_values": [],
              "pokemon_details": null
            },
            {
              "min_level": 25,
              "max_level": 25,
              "chance": 5,
              "method": {
                "name": "good-rod",
                "url": "/api/v2/encounter-method/3/"
              },
              "condition_values": [],
              "pokemon_details": null
            }
          ]
        },
        {
          "version": {
            "name": "y",
            "url": "/api/v2/version/24/"
          },
          "max_chance": 35,
          "encounter_details": [
            {
              "min_level": 35,
              "max_level": 35,
              "chance": 35,
              "method": {
                "name": "super-rod",
                "url": "/api/v2/encounter-method/4/"
              },
              "condition_values": [],
              "pokemon_details": null
            }
          ]
        }
      ]
    }
  ]
}
