=== PokeAPI/api-data/data/schema/v2/location-area/$id/index.json
{
    "$schema": "http://json-schema.org/schema#",
    "properties": {
        "encounter_method_rates": {
            "items": {
                "properties": {
                    "encounter_method": {
                        "$ref": "/schema/v2/named_api_resource.json"
                    },
                    "version_details": {
                        "items": {
                            "properties": {
                                "rate": {
                                    "type": "integer"
                                },
                                "version": {
                                    "$ref": "/schema/v2/named_api_resource.json"
                                }
                            },
                            "required": [
                                "rate",
                                "version"
                            ],
                            "type": "object"
                        },
                        "type": "array"
                    }
                },
                "required": [
                    "encounter_method",
                    "version_details"
                ],
                "type": "object"
            },
            "type": "array"
        },
        "game_index": {
            "type": "integer"
        },
        "id": {
            "type": "integer"
        },
        "location": {
            "$ref": "/schema/v2/named_api_resource.json"
        },
        "name": {
            "type": "string"
        },
        "names": {
            "items": {
                "$ref": "/schema/v2/name.json"
            },
            "type": "array"
        },
        "pokemon_encounters": {
            "items": {
                "properties": {
                    "pokemon": {
                        "$ref": "/schema/v2/named_api_resource.json"
                    },
                    "version_details": {
                        "items": {
                            "properties": {
                                "encounter_details": {
                                    "items": {
                                        "properties": {
                                            "chance": {
                                                "type": "integer"
                                            },
                                            "condition_values": {
                                                "items": {
                                                    "$ref": "/schema/v2/named_api_resource.json"
                                                },
                                                "type": "array"
                                            },
                                            "max_level": {
                                                "type": "integer"
                                            },
                                            "method": {
                                                "$ref": "/schema/v2/named_api_resource.json"
                                            },
                                            "min_level": {
                                                "type": "integer"
                                            },
                                            "pokemon_details": {
                                                "anyOf": [
                                                    {
                                                        "type": "null"
                                                    },
                                                    {
                                                        "properties": {
                                                            "always_shiny": {
                                                                "type": "boolean"
                                                            },
                                                            "is_alpha": {
                                                                "type": "boolean"
                                                            },
                                                            "min_perfect_ivs": {
                                                                "type": "null"
                                                            },
                                                            "never_shiny": {
                                                                "type": "boolean"
                                                            }
                                                        },
                                                        "required": [
                                                            "always_shiny",
                                                            "is_alpha",
                                                            "min_perfect_ivs",
                                                            "never_shiny"
                                                        ],
                                                        "type": "object"
                                                    }
                                                ]
                                            }
                                        },
                                        "required": [
                                            "chance",
                                            "condition_values",
                                            "max_level",
                                            "method",
                                            "min_level",
                                            "pokemon_details"
                                        ],
                                        "type": "object"
                                    },
                                    "type": "array"
                                },
                                "max_chance": {
                                    "type": "integer"
                                },
                                "version": {
                                    "$ref": "/schema/v2/named_api_resource.json"
                                }
                            },
                            "required": [
                                "encounter_details",
                                "max_chance",
                                "version"
                            ],
                            "type": "object"
                        },
                        "type": "array"
                    }
                },
                "required": [
                    "pokemon",
                    "version_details"
                ],
                "type": "object"
            },
            "type": "array"
        }
    },
    "required": [
        "encounter_method_rates",
        "game_index",
        "id",
        "location",
        "name",
        "names",
        "pokemon_encounters"
    ],
    "type": "object"
}

=== PokeAPI/api-data/data/api/v2/location-area/1173/index.json
{
    "encounter_method_rates": [],
    "game_index": 0,
    "id": 1173,
    "location": {
        "name": "twist-mountain",
        "url": "/api/v2/location/380/"
    },
    "name": "twist-mountain-b4f",
    "names": [],
    "pokemon_encounters": [
        {
            "pokemon": {
                "name": "regigigas",
                "url": "/api/v2/pokemon/486/"
            },
            "version_details": [
                {
                    "encounter_details": [
                        {
                            "chance": 100,
                            "condition_values": [
                                {
                                    "name": "other-regirock-regice-registeel-in-party",
                                    "url": "/api/v2/encounter-condition-value/58/"
                                }
                            ],
                            "max_level": 68,
                            "method": {
                                "name": "static",
                                "url": "/api/v2/encounter-method/20/"
                            },
                            "min_level": 68,
                            "pokemon_details": null
                        }
                    ],
                    "max_chance": 100,
                    "version": {
                        "name": "black-2",
                        "url": "/api/v2/version/21/"
                    }
                },
                {
                    "encounter_details": [
                        {
                            "chance": 100,
                            "condition_values": [
                                {
                                    "name": "other-regirock-regice-registeel-in-party",
                                    "url": "/api/v2/encounter-condition-value/58/"
                                }
                            ],
                            "max_level": 68,
                            "method": {
                                "name": "static",
                                "url": "/api/v2/encounter-method/20/"
                            },
                            "min_level": 68,
                            "pokemon_details": null
                        }
                    ],
                    "max_chance": 100,
                    "version": {
                        "name": "white-2",
                        "url": "/api/v2/version/22/"
                    }
                }
            ]
        }
    ]
}

=== PokeAPI/api-data/data/api/v2/location-area/812/index.json
{
    "encounter_method_rates": [],
    "game_index": 0,
    "id": 812,
    "location": {
        "name": "ancient-tomb",
        "url": "/api/v2/location/583/"
    },
    "name": "ancient-tomb-area",
    "names": [
        {
            "language": {
                "name": "en",
                "url": "/api/v2/language/9/"
            },
            "name": "Ancient Tomb"
        },
        {
            "language": {
                "name": "de",
                "url": "/api/v2/language/6/"
            },
            "name": "Grabmal"
        },
        {
            "language": {
                "name": "fr",
                "url": "/api/v2/language/5/"
            },
            "name": "Tombeau Antique"
        }
    ],
    "pokemon_encounters": [
        {
            "pokemon": {
                "name": "registeel",
                "url": "/api/v2/pokemon/379/"
            },
            "version_details": [
                {
                    "encounter_details": [
                        {
                            "chance": 100,
                            "condition_values": [],
                            "max_level": 40,
                            "method": {
                                "name": "static",
                                "url": "/api/v2/encounter-method/20/"
                            },
                            "min_level": 40,
                            "pokemon_details": null
                        }
                    ],
                    "max_chance": 100,
                    "version": {
                        "name": "ruby",
                        "url": "/api/v2/version/7/"
                    }
                },
                {
                    "encounter_details": [
                        {
                            "chance": 100,
                            "condition_values": [],
                            "max_level": 40,
                            "method": {
                                "name": "static",
                                "url": "/api/v2/encounter-method/20/"
                            },
                            "min_level": 40,
                            "pokemon_details": null
                        }
                    ],
                    "max_chance": 100,
                    "version": {
                        "name": "sapphire",
                        "url": "/api/v2/version/8/"
                    }
                },
                {
                    "encounter_details": [
                        {
                            "chance": 100,
                            "condition_values": [],
                            "max_level": 40,
                            "method": {
                                "name": "static",
                                "url": "/api/v2/encounter-method/20/"
                            },
                            "min_level": 40,
                            "pokemon_details": null
                        }
                    ],
                    "max_chance": 100,
                    "version": {
                        "name": "emerald",
                        "url": "/api/v2/version/9/"
                    }
                },
                {
                    "encounter_details": [
                        {
                            "chance": 100,
                            "condition_values": [],
                            "max_level": 40,
                            "method": {
                                "name": "static",
                                "url": "/api/v2/encounter-method/20/"
                            },
                            "min_level": 40,
                            "pokemon_details": null
                        }
                    ],
                    "max_chance": 100,
                    "version": {
                        "name": "omega-ruby",
                        "url": "/api/v2/version/25/"
                    }
                },
                {
                    "encounter_details": [
                        {
                            "chance": 100,
                            "condition_values": [],
                            "max_level": 40,
                            "method": {
                                "name": "static",
                                "url": "/api/v2/encounter-method/20/"
                            },
                            "min_level": 40,
                            "pokemon_details": null
                        }
                    ],
                    "max_chance": 100,
                    "version": {
                        "name": "alpha-sapphire",
                        "url": "/api/v2/version/26/"
                    }
                }
            ]
        }
    ]
}
