=== PokeAPI/api-data/data/schema/v2/pokemon-species/$id/index.json
{
  "$schema": "http://json-schema.org/schema#",
  "type": "object",
  "properties": {
    "id": {
      "type": "integer"
    },
    "name": {
      "type": "string"
    },
    "order": {
      "type": "integer"
    },
    "gender_rate": {
      "type": "integer"
    },
    "capture_rate": {
      "type": "integer"
    },
    "base_happiness": {
      "type": "integer"
    },
    "is_baby": {
      "type": "boolean"
    },
    "is_legendary": {
      "type": "boolean"
    },
    "is_mythical": {
      "type": "boolean"
    },
    "hatch_counter": {
      "type": "integer"
    },
    "has_gender_differences": {
      "type": "boolean"
    },
    "forms_switchable": {
      "type": "boolean"
    },
    "growth_rate": {
      "$ref": "/schema/v2/named_api_resource.json"
    },
    "pokedex_numbers": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "entry_number": {
            "type": "integer"
          },
          "pokedex": {
            "$ref": "/schema/v2/named_api_resource.json"
          }
        },
        "required": [
          "entry_number",
          "pokedex"
        ]
      }
    },
    "egg_groups": {
      "type": "array",
      "items": {
        "$ref": "/schema/v2/named_api_resource.json"
      }
    },
    "color": {
      "$ref": "/schema/v2/named_api_resource.json"
    },
    "shape": {
      "$ref": "/schema/v2/named_api_resource.json"
    },
    "evolves_from_species": {
      "anyOf": [
        {
          "type": "null"
        },
        {
          "$ref": "/schema/v2/named_api_resource.json"
        }
      ]
    },
    "evolution_chain": {
      "$ref": "/schema/v2/api_resource.json"
    },
    "habitat": {
      "anyOf": [
        {
          "type": "null"
        },
        {
          "$ref": "/schema/v2/named_api_resource.json"
        }
      ]
    },
    "generation": {
      "$ref": "/schema/v2/named_api_resource.json"
    },
    "names": {
      "type": "array",
      "items": {
        "$ref": "/schema/v2/name.json"
      }
    },
    "pal_park_encounters": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "base_score": {
            "type": "integer"
          },
          "rate": {
            "type": "integer"
          },
          "area": {
            "$ref": "/schema/v2/named_api_resource.json"
          }
        },
        "required": [
          "area",
          "base_score",
          "rate"
        ]
      }
    },
    "form_descriptions": {
      "type": "array",
      "items": {
        "$ref": "/schema/v2/description.json"
      }
    },
    "flavor_text_entries": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "flavor_text": {
            "type": "string"
          },
          "language": {
            "$ref": "/schema/v2/named_api_resource.json"
          },
          "version": {
            "$ref": "/schema/v2/named_api_resource.json"
          }
        },
        "required": [
          "flavor_text",
          "language",
          "version"
        ]
      }
    },
    "genera": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "genus": {
            "type": "string"
          },
          "language": {
            "$ref": "/schema/v2/named_api_resource.json"
          }
        },
        "required": [
          "genus",
          "language"
        ]
      }
    },
    "varieties": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "is_default": {
            "type": "boolean"
          },
          "pokemon": {
            "$ref": "/schema/v2/named_api_resource.json"
          }
        },
        "required": [
          "is_default",
          "pokemon"
        ]
      }
    }
  },
  "required": [
    "base_happiness",
    "capture_rate",
    "color",
    "egg_groups",
    "evolution_chain",
    "evolves_from_species",
    "flavor_text_entries",
    "form_descriptions",
    "forms_switchable",
    "gender_rate",
    "genera",
    "generation",
    "growth_rate",
    "habitat",
    "has_gender_differences",
    "hatch_counter",
    "id",
    "is_baby",
    "is_legendary",
    "is_mythical",
    "name",
    "names",
    "order",
    "pal_park_encounters",
    "pokedex_numbers",
    "shape",
    "varieties"
  ]
}

=== PokeAPI/api-data/data/api/v2/pokemon-species/1020/index.json
{
  "id": 1020,
  "name": "gouging-fire",
  "order": 1022,
  "gender_rate": -1,
  "capture_rate": 10,
  "base_happiness": 0,
  "is_baby": false,
  "is_legendary": false,
  "is_mythical": false,
  "hatch_counter": 50,
  "has_gender_differences": false,
  "forms_switchable": false,
  "growth_rate": {
    "name": "slow",
    "url": "/api/v2/growth-rate/1/"
  },
  "pokedex_numbers": [
    {
      "entry_number": 1020,
      "pokedex": {
        "name": "national",
        "url": "/api/v2/pokedex/1/"
      }
    },
    {
      "entry_number": 236,
      "pokedex": {
        "name": "blueberry",
        "url": "/api/v2/pokedex/33/"
      }
    }
  ],
  "egg_groups": [
    {
      "name": "no-eggs",
      "url": "/api/v2/egg-group/15/"
    }
  ],
  "color": {
    "name": "brown",
    "url": "/api/v2/pokemon-color/3/"
  },
  "shape": {
    "name": "quadruped",
    "url": "/api/v2/pokemon-shape/8/"
  },
  "evolves_from_species": null,
  "evolution_chain": {
    "url": "/api/v2/evolution-chain/544/"
  },
  "habitat": null,
  "generation": {
    "name": "generation-ix",
    "url": "/api/v2/generation/9/"
  },
  "names": [
    {
      "name": "ウガツホムラ",
      "language": {
        "name": "ja-hrkt",
        "url": "/api/v2/language/1/"
      }
    },
    {
      "name": "Ugatsuhomura",
      "language": {
        "name": "ja-roma",
        "url": "/api/v2/language/2/"
      }
    },
    {
      "name": "꿰뚫는화염",
      "language": {
        "name": "ko",
        "url": "/api/v2/language/3/"
      }
    },
    {
      "name": "破空焰",
      "language": {
        "name": "zh-hant",
        "url": "/api/v2/language/4/"
      }
    },
    {
      "name": "Feu-Perçant",
      "language": {
        "name": "fr",
        "url": "/api/v2/language/5/"
      }
    },
    {
      "name": "Keilflamme",
      "language": {
        "name": "de",
        "url": "/api/v2/language/6/"
      }
    },
    {
      "name": "Flamariete",
      "language": {
        "name": "es",
        "url": "/api/v2/language/7/"
      }
    },
    {
      "name": "Vampeaguzze",
      "language": {
        "name": "it",
        "url": "/api/v2/language/8/"
      }
    },
    {
      "name": "Gouging Fire",
      "language": {
        "name": "en",
        "url": "/api/v2/language/9/"
      }
    },
    {
      "name": "ウガツホムラ",
      "language": {
        "name": "ja",
        "url": "/api/v2/language/11/"
      }
    },
    {
      "name": "破空焰",
      "language": {
        "name": "zh-hans",
        "url": "/api/v2/language/12/"
      }
    },
    {
      "name": "Flamariete",
      "language": {
        "name": "es-419",
        "url": "/api/v2/language/14/"
      }
    }
  ],
  "pal_park_encounters": [],
  "form_descriptions": [],
  "flavor_text_entries": [
    {
      "flavor_text": "There are scant few reports of this creature being sighted. One short video shows it rampaging and spouting pillars of flame.",
      "language": {
        "name": "en",
        "url": "/api/v2/language/9/"
      },
      "version": {
        "name": "scarlet",
        "url": "/api/v2/version/40/"
      }
    },
    {
      "flavor_text": "It resembles an eerie Pokémon once shown in a paranormal magazine. That Pokémon was said to be an Entei regenerated from a fossil.",
      "language": {
        "name": "en",
        "url": "/api/v2/language/9/"
      },
      "version": {
        "name": "violet",
        "url": "/api/v2/version/41/"
      }
    }
  ],
  "genera": [
    {
      "genus": "パラドックスポケモン",
      "language": {
        "name": "ja-hrkt",
        "url": "/api/v2/language/1/"
      }
    },
    {
      "genus": "패러독스포켓몬",
      "language": {
        "name": "ko",
        "url": "/api/v2/language/3/"
      }
    },
    {
      "genus": "Paradoxe",
      "language": {
        "name": "fr",
        "url": "/api/v2/language/5/"
      }
    },
    {
      "genus": "Paradox Pokémon",
      "language": {
        "name": "en",
        "url": "/api/v2/language/9/"
      }
    },
    {
      "genus": "パラドックスポケモン",
      "language": {
        "name": "ja",
        "url": "/api/v2/language/11/"
      }
    }
  ],
  "varieties": [
    {
      "is_default": true,
      "pokemon": {
        "name": "gouging-fire",
        "url": "/api/v2/pokemon/1020/"
      }
    }
  ]
}

=== PokeAPI/api-data/data/api/v2/pokemon-species/1025/index.json
{
  "id": 1025,
  "name": "pecharunt",
  "order": 1027,
  "gender_rate": -1,
  "capture_rate": 3,
  "base_happiness": 0,
  "is_baby": false,
  "is_legendary": false,
  "is_mythical": true,
  "hatch_counter": 20,
  "has_gender_differences": false,
  "forms_switchable": false,
  "growth_rate": {
    "name": "slow",
    "url": "/api/v2/growth-rate/1/"
  },
  "pokedex_numbers": [
    {
      "entry_number": 1025,
      "pokedex": {
        "name": "national",
        "url": "/api/v2/pokedex/1/"
      }
    },
    {
      "entry_number": 243,
      "pokedex": {
        "name": "blueberry",
        "url": "/api/v2/pokedex/33/"
      }
    }
  ],
  "egg_groups": [
    {
      "name": "no-eggs",
      "url": "/api/v2/egg-group/15/"
    }
  ],
  "color": {
    "name": "purple",
    "url": "/api/v2/pokemon-color/7/"
  },
  "shape": {
    "name": "ball",
    "url": "/api/v2/pokemon-shape/1/"
  },
  "evolves_from_species": null,
  "evolution_chain": {
    "url": "/api/v2/evolution-chain/549/"
  },
  "habitat": null,
  "generation": {
    "name": "generation-ix",
    "url": "/api/v2/generation/9/"
  },
  "names": [
    {
      "name": "モモワロウ",
      "language": {
        "name": "ja-hrkt",
        "url": "/api/v2/language/1/"
      }
    },
    {
      "name": "Momowarou",
      "language": {
        "name": "ja-roma",
        "url": "/api/v2/language/2/"
      }
    },
    {
      "name": "복숭악동",
      "language": {
        "name": "ko",
        "url": "/api/v2/language/3/"
      }
    },
    {
      "name": "桃歹郎",
      "language": {
        "name": "zh-hant",
        "url": "/api/v2/language/4/"
      }
    },
    {
      "name": "Pêchaminus",
      "language": {
        "name": "fr",
        "url": "/api/v2/language/5/"
      }
    },
    {
      "name": "Infamomo",
      "language": {
        "name": "de",
        "url": "/api/v2/language/6/"
      }
    },
    {
      "name": "Pecharunt",
      "language": {
        "name": "es",
        "url": "/api/v2/language/7/"
      }
    },
    {
      "name": "Pecharunt",
      "language": {
        "name": "it",
        "url": "/api/v2/language/8/"
      }
    },
    {
      "name": "Pecharunt",
      "language": {
        "name": "en",
        "url": "/api/v2/language/9/"
      }
    },
    {
      "name": "モモワロウ",
      "language": {
        "name": "ja",
        "url": "/api/v2/language/11/"
      }
    },
    {
      "name": "桃歹郎",
      "language": {
        "name": "zh-hans",
        "url": "/api/v2/language/12/"
      }
    },
    {
      "name": "Pecharunt",
      "language": {
        "name": "es-419",
        "url": "/api/v2/language/14/"
      }
    }
  ],
  "pal_park_encounters": [],
  "form_descriptions": [],
  "flavor_text_entries": [
    {
      "flavor_text": "It feeds others toxic mochi that draw out desires and capabilities. Those who eat the mochi fall under Pecharunt’s control, chained to its will.",
      "language": {
        "name": "en",
        "url": "/api/v2/language/9/"
      },
      "version": {
        "name": "scarlet",
        "url": "/api/v2/version/40/"
      }
    },
    {
      "flavor_text": "Its peach-shaped shell serves as storage for a potent poison. It makes poisonous mochi and serves them to people and Pokémon.",
      "language": {
        "name": "en",
        "url": "/api/v2/language/9/"
      },
      "version": {
        "name": "violet",
        "url": "/api/v2/version/41/"
      }
    }
  ],
  "genera": [
    {
      "genus": "しはいポケモン",
      "language": {
        "name": "ja-hrkt",
        "url": "/api/v2/language/1/"
      }
    },
    {
      "genus": "지배포켓몬",
      "language": {
        "name": "ko",
        "url": "/api/v2/language/3/"
      }
    },
    {
      "genus": "Emprise",
      "language": {
        "name": "fr",
        "url": "/api/v2/language/5/"
      }
    },
    {
      "genus": "Subjugation Pokémon",
      "language": {
        "name": "en",
        "url": "/api/v2/language/9/"
      }
    },
    {
      "genus": "しはいポケモン",
      "language": {
        "name": "ja",
        "url": "/api/v2/language/11/"
      }
    }
  ],
  "varieties": [
    {
      "is_default": true,
      "pokemon": {
        "name": "pecharunt",
        "url": "/api/v2/pokemon/1025/"
      }
    }
  ]
}

=== PokeAPI/api-data/data/api/v2/pokemon-species/971/index.json
{
  "id": 971,
  "name": "greavard",
  "order": 924,
  "gender_rate": 4,
  "capture_rate": 120,
  "base_happiness": 50,
  "is_baby": false,
  "is_legendary": false,
  "is_mythical": false,
  "hatch_counter": 20,
  "has_gender_differences": false,
  "forms_switchable": false,
  "growth_rate": {
    "name": "medium-slow",
    "url": "/api/v2/growth-rate/4/"
  },
  "pokedex_numbers": [
    {
      "entry_number": 971,
      "pokedex": {
        "name": "national",
        "url": "/api/v2/pokedex/1/"
      }
    },
    {
      "entry_number": 311,
      "pokedex": {
        "name": "paldea",
        "url": "/api/v2/pokedex/31/"
      }
    },
    {
      "entry_number": 23,
      "pokedex": {
        "name": "hyperspace",
        "url": "/api/v2/pokedex/35/"
      }
    }
  ],
  "egg_groups": [
    {
      "name": "ground",
      "url": "/api/v2/egg-group/5/"
    }
  ],
  "color": {
    "name": "white",
    "url": "/api/v2/pokemon-color/9/"
  },
  "shape": {
    "name": "quadruped",
    "url": "/api/v2/pokemon-shape/8/"
  },
  "evolves_from_species": null,
  "evolution_chain": {
    "url": "/api/v2/evolution-chain/509/"
  },
  "habitat": null,
  "generation": {
    "name": "generation-ix",
    "url": "/api/v2/generation/9/"
  },
  "names": [
    {
      "name": "ボチ",
      "language": {
        "name": "ja-hrkt",
        "url": "/api/v2/language/1/"
      }
    },
    {
      "name": "Bochi",
      "language": {
        "name": "ja-roma",
        "url": "/api/v2/language/2/"
      }
    },
    {
      "name": "망망이",
      "language": {
        "name": "ko",
        "url": "/api/v2/language/3/"
      }
    },
    {
      "name": "墓仔狗",
      "language": {
        "name": "zh-hant",
        "url": "/api/v2/language/4/"
      }
    },
    {
      "name": "Toutombe",
      "language": {
        "name": "fr",
        "url": "/api/v2/language/5/"
      }
    },
    {
      "name": "Gruff",
      "language": {
        "name": "de",
        "url": "/api/v2/language/6/"
      }
    },
    {
      "name": "Greavard",
      "language": {
        "name": "es",
        "url": "/api/v2/language/7/"
      }
    },
    {
      "name": "Greavard",
      "language": {
        "name": "it",
        "url": "/api/v2/language/8/"
      }
    },
    {
      "name": "Greavard",
      "language": {
        "name": "en",
        "url": "/api/v2/language/9/"
      }
    },
    {
      "name": "ボチ",
      "language": {
        "name": "ja",
        "url": "/api/v2/language/11/"
      }
    },
    {
      "name": "墓仔狗",
      "language": {
        "name": "zh-hans",
        "url": "/api/v2/language/12/"
      }
    },
    {
      "name": "Greavard",
      "language": {
        "name": "es-419",
        "url": "/api/v2/language/14/"
      }
    }
  ],
  "pal_park_encounters": [],
  "form_descriptions": [],
  "flavor_text_entries": [
    {
      "flavor_text": "It is said that a dog Pokémon that died in the wild without ever interacting with a human was reborn as this Pokémon.",
      "language": {
        "name": "en",
        "url": "/api/v2/language/9/"
      },
      "version": {
        "name": "scarlet",
        "url": "/api/v2/version/40/"
      }
    },
    {
      "flavor_text": "This friendly Pokémon doesn’t like being alone. Pay it even the slightest bit of attention, and it will follow you forever.",
      "language": {
        "name": "en",
        "url": "/api/v2/language/9/"
      },
      "version": {
        "name": "violet",
        "url": "/api/v2/version/41/"
      }
    }
  ],
  "genera": [
    {
      "genus": "おばけいぬポケモン",
      "language": {
        "name": "ja-hrkt",
        "url": "/api/v2/language/1/"
      }
    },
    {
      "genus": "유령개포켓몬",
      "language": {
        "name": "ko",
        "url": "/api/v2/language/3/"
      }
    },
    {
      "genus": "鬼犬寶可夢",
      "language": {
        "name": "zh-hant",
        "url": "/api/v2/language/4/"
      }
    },
    {
      "genus": "Fantôchien",
      "language": {
        "name": "fr",
        "url": "/api/v2/language/5/"
      }
    },
    {
      "genus": "Geisterhund",
      "language": {
        "name": "de",
        "url": "/api/v2/language/6/"
      }
    },
    {
      "genus": "Ghost Dog Pokémon",
      "language": {
        "name": "en",
        "url": "/api/v2/language/9/"
      }
    },
    {
      "genus": "鬼犬宝可梦",
      "language": {
        "name": "zh-hans",
        "url": "/api/v2/language/12/"
      }
    }
  ],
  "varieties": [
    {
      "is_default": true,
      "pokemon": {
        "name": "greavard",
        "url": "/api/v2/pokemon/971/"
      }
    }
  ]
}

=== PokeAPI/api-data/data/api/v2/pokemon-species/1024/index.json
{
  "id": 1024,
  "name": "terapagos",
  "order": 1026,
  "gender_rate": 4,
  "capture_rate": 255,
  "base_happiness": 50,
  "is_baby": false,
  "is_legendary": true,
  "is_mythical": false,
  "hatch_counter": 5,
  "has_gender_differences": false,
  "forms_switchable": false,
  "growth_rate": {
    "name": "slow",
    "url": "/api/v2/growth-rate/1/"
  },
  "pokedex_numbers": [
    {
      "entry_number": 1024,
      "pokedex": {
        "name": "national",
        "url": "/api/v2/pokedex/1/"
      }
    },
    {
      "entry_number": 240,
      "pokedex": {
        "name": "blueberry",
        "url": "/api/v2/pokedex/33/"
      }
    }
  ],
  "egg_groups": [
    {
      "name": "no-eggs",
      "url": "/api/v2/egg-group/15/"
    }
  ],
  "color": {
    "name": "blue",
    "url": "/api/v2/pokemon-color/2/"
  },
  "shape": {
    "name": "quadruped",
    "url": "/api/v2/pokemon-shape/8/"
  },
  "evolves_from_species": null,
  "evolution_chain": {
    "url": "/api/v2/evolution-chain/548/"
  },
  "habitat": null,
  "generation": {
    "name": "generation-ix",
    "url": "/api/v2/generation/9/"
  },
  "names": [
    {
      "name": "テラパゴス",
      "language": {
        "name": "ja-hrkt",
        "url": "/api/v2/language/1/"
      }
    },
    {
      "name": "Terapagos",
      "language": {
        "name": "ja-roma",
        "url": "/api/v2/language/2/"
      }
    },
    {
      "name": "테라파고스",
      "language": {
        "name": "ko",
        "url": "/api/v2/language/3/"
      }
    },
    {
      "name": "太樂巴戈斯",
      "language": {
        "name": "zh-hant",
        "url": "/api/v2/language/4/"
      }
    },
    {
      "name": "Terapagos",
      "language": {
        "name": "fr",
        "url": "/api/v2/language/5/"
      }
    },
    {
      "name": "Terapagos",
      "language": {
        "name": "de",
        "url": "/api/v2/language/6/"
      }
    },
    {
      "name": "Terapagos",
      "language": {
        "name": "es",
        "url": "/api/v2/language/7/"
      }
    },
    {
      "name": "Terapagos",
      "language": {
        "name": "it",
        "url": "/api/v2/language/8/"
      }
    },
    {
      "name": "Terapagos",
      "language": {
        "name": "en",
        "url": "/api/v2/language/9/"
      }
    },
    {
      "name": "テラパゴス",
      "language": {
        "name": "ja",
        "url": "/api/v2/language/11/"
      }
    },
    {
      "name": "太乐巴戈斯",
      "language": {
        "name": "zh-hans",
        "url": "/api/v2/language/12/"
      }
    },
    {
      "name": "Terapagos",
      "language": {
        "name": "es-419",
        "url": "/api/v2/language/14/"
      }
    }
  ],
  "pal_park_encounters": [],
  "form_descriptions": [],
  "flavor_text_entries": [
    {
      "flavor_text": "Terapagos protects itself using its power to transform energy into hard crystals. This Pokémon is the source of the Terastal phenomenon.",
      "language": {
        "name": "en",
        "url": "/api/v2/language/9/"
      },
      "version": {
        "name": "scarlet",
        "url": "/api/v2/version/40/"
      }
    },
    {
      "flavor_text": "It’s thought that this Pokémon lived in ancient Paldea until it got caught in seismic shifts and went extinct.",
      "language": {
        "name": "en",
        "url": "/api/v2/language/9/"
      },
      "version": {
        "name": "violet",
        "url": "/api/v2/version/41/"
      }
    }
  ],
  "genera": [
    {
      "genus": "テラスタルポケモン",
      "language": {
        "name": "ja-hrkt",
        "url": "/api/v2/language/1/"
      }
    },
    {
      "genus": "테라스탈포켓몬",
      "language": {
        "name": "ko",
        "url": "/api/v2/language/3/"
      }
    },
    {
      "genus": "Téracristal",
      "language": {
        "name": "fr",
        "url": "/api/v2/language/5/"
      }
    },
    {
      "genus": "Tera Pokémon",
      "language": {
        "name": "en",
        "url": "/api/v2/language/9/"
      }
    },
    {
      "genus": "テラスタルポケモン",
      "language": {
        "name": "ja",
        "url": "/api/v2/language/11/"
      }
    }
  ],
  "varieties": [
    {
      "is_default": true,
      "pokemon": {
        "name": "terapagos",
        "url": "/api/v2/pokemon/1024/"
      }
    },
    {
      "is_default": false,
      "pokemon": {
        "name": "terapagos-terastal",
        "url": "/api/v2/pokemon/10276/"
      }
    },
    {
      "is_default": false,
      "pokemon": {
        "name": "terapagos-stellar",
        "url": "/api/v2/pokemon/10277/"
      }
    }
  ]
}

=== PokeAPI/api-data/data/api/v2/pokemon-species/1007/index.json
{
  "id": 1007,
  "name": "koraidon",
  "order": 998,
  "gender_rate": -1,
  "capture_rate": 3,
  "base_happiness": 0,
  "is_baby": false,
  "is_legendary": true,
  "is_mythical": false,
  "hatch_counter": 50,
  "has_gender_differences": false,
  "forms_switchable": false,
  "growth_rate": {
    "name": "slow",
    "url": "/api/v2/growth-rate/1/"
  },
  "pokedex_numbers": [
    {
      "entry_number": 1007,
      "pokedex": {
        "name": "national",
        "url": "/api/v2/pokedex/1/"
      }
    },
    {
      "entry_number": 399,
      "pokedex": {
        "name": "paldea",
        "url": "/api/v2/pokedex/31/"
      }
    }
  ],
  "egg_groups": [
    {
      "name": "no-eggs",
      "url": "/api/v2/egg-group/15/"
    }
  ],
  "color": {
    "name": "red",
    "url": "/api/v2/pokemon-color/8/"
  },
  "shape": {
    "name": "upright",
    "url": "/api/v2/pokemon-shape/6/"
  },
  "evolves_from_species": null,
  "evolution_chain": {
    "url": "/api/v2/evolution-chain/535/"
  },
  "habitat": null,
  "generation": {
    "name": "generation-ix",
    "url": "/api/v2/generation/9/"
  },
  "names": [
    {
      "name": "コライドン",
      "language": {
        "name": "ja-hrkt",
        "url": "/api/v2/language/1/"
      }
    },
    {
      "name": "Koraidon",
      "language": {
        "name": "ja-roma",
        "url": "/api/v2/language/2/"
      }
    },
    {
      "name": "코라이돈",
      "language": {
        "name": "ko",
        "url": "/api/v2/language/3/"
      }
    },
    {
      "name": "故勒頓",
      "language": {
        "name": "zh-hant",
        "url": "/api/v2/language/4/"
      }
    },
    {
      "name": "Koraidon",
      "language": {
        "name": "fr",
        "url": "/api/v2/language/5/"
      }
    },
    {
      "name": "Koraidon",
      "language": {
        "name": "de",
        "url": "/api/v2/language/6/"
      }
    },
    {
      "name": "Koraidon",
      "language": {
        "name": "es",
        "url": "/api/v2/language/7/"
      }
    },
    {
      "name": "Koraidon",
      "language": {
        "name": "it",
        "url": "/api/v2/language/8/"
      }
    },
    {
      "name": "Koraidon",
      "language": {
        "name": "en",
        "url": "/api/v2/language/9/"
      }
    },
    {
      "name": "コライドン",
      "language": {
        "name": "ja",
        "url": "/api/v2/language/11/"
      }
    },
    {
      "name": "故勒顿",
      "language": {
        "name": "zh-hans",
        "url": "/api/v2/language/12/"
      }
    },
    {
      "name": "Koraidon",
      "language": {
        "name": "es-419",
        "url": "/api/v2/language/14/"
      }
    }
  ],
  "pal_park_encounters": [],
  "form_descriptions": [],
  "flavor_text_entries": [
    {
      "flavor_text": "This seems to be the Winged King mentioned in an old expedition journal. It was said to have split the land with its bare fists.",
      "language": {
        "name": "en",
        "url": "/api/v2/language/9/"
      },
      "version": {
        "name": "scarlet",
        "url": "/api/v2/version/40/"
      }
    },
    {
      "flavor_text": "This Pokémon resembles Cyclizar, but it is far burlier and more ferocious. Nothing is known about its ecology or other features.",
      "language": {
        "name": "en",
        "url": "/api/v2/language/9/"
      },
      "version": {
        "name": "violet",
        "url": "/api/v2/version/41/"
      }
    }
  ],
  "genera": [
    {
      "genus": "パラドックスポケモン",
      "language": {
        "name": "ja-hrkt",
        "url": "/api/v2/language/1/"
      }
    },
    {
      "genus": "패러독스포켓몬",
      "language": {
        "name": "ko",
        "url": "/api/v2/language/3/"
      }
    },
    {
      "genus": "悖謬寶可夢",
      "language": {
        "name": "zh-hant",
        "url": "/api/v2/language/4/"
      }
    },
    {
      "genus": "Paradoxe",
      "language": {
        "name": "fr",
        "url": "/api/v2/language/5/"
      }
    },
    {
      "genus": "Paradox",
      "language": {
        "name": "de",
        "url": "/api/v2/language/6/"
      }
    },
    {
      "genus": "Paradox Pokémon",
      "language": {
        "name": "en",
        "url": "/api/v2/language/9/"
      }
    },
    {
      "genus": "悖谬宝可梦",
      "language": {
        "name": "zh-hans",
        "url": "/api/v2/language/12/"
      }
    }
  ],
  "varieties": [
    {
      "is_default": true,
      "pokemon": {
        "name": "koraidon",
        "url": "/api/v2/pokemon/1007/"
      }
    },
    {
      "is_default": false,
      "pokemon": {
        "name": "koraidon-limited-build",
        "url": "/api/v2/pokemon/10264/"
      }
    },
    {
      "is_default": false,
      "pokemon": {
        "name": "koraidon-sprinting-build",
        "url": "/api/v2/pokemon/10265/"
      }
    },
    {
      "is_default": false,
      "pokemon": {
        "name": "koraidon-swimming-build",
        "url": "/api/v2/pokemon/10266/"
      }
    },
    {
      "is_default": false,
      "pokemon": {
        "name": "koraidon-gliding-build",
        "url": "/api/v2/pokemon/10267/"
      }
    }
  ]
}
