=== PokeAPI/api-data/data/schema/v2/nature/$id/index.json
{
  "$schema": "http://json-schema.org/schema#",
  "type": "object",
  "properties": {
    "id": {
      "type": "integer"
    },
    "name": {
      "type": "string"
    },
    "decreased_stat": {
      "anyOf": [
        {
          "type": "null"
        },
        {
          "$ref": "/schema/v2/named_api_resource.json"
        }
      ]
    },
    "increased_stat": {
      "anyOf": [
        {
          "type": "null"
        },
        {
          "$ref": "/schema/v2/named_api_resource.json"
        }
      ]
    },
    "likes_flavor": {
      "anyOf": [
        {
          "type": "null"
        },
        {
          "$ref": "/schema/v2/named_api_resource.json"
        }
      ]
    },
    "hates_flavor": {
      "anyOf": [
        {
          "type": "null"
        },
        {
          "$ref": "/schema/v2/named_api_resource.json"
        }
      ]
    },
    "pokeathlon_stat_changes": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "max_change": {
            "type": "integer"
          },
          "pokeathlon_stat": {
            "$ref": "/schema/v2/named_api_resource.json"
          }
        },
        "required": [
          "max_change",
          "pokeathlon_stat"
        ]
      }
    },
    "move_battle_style_preferences": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "low_hp_preference": {
            "type": "integer"
          },
          "high_hp_preference": {
            "type": "integer"
          },
          "move_battle_style": {
            "$ref": "/schema/v2/named_api_resource.json"
          }
        },
        "required": [
          "high_hp_preference",
          "low_hp_preference",
          "move_battle_style"
        ]
      }
    },
    "names": {
      "type": "array",
      "items": {
        "$ref": "/schema/v2/name.json"
      }
    }
  },
  "required": [
    "decreased_stat",
    "hates_flavor",
    "id",
    "increased_stat",
    "likes_flavor",
    "move_battle_style_preferences",
    "name",
    "names",
    "pokeathlon_stat_changes"
  ]
}

=== PokeAPI/api-data/data/api/v2/nature/8/index.json
{
  "id": 8,
  "name": "mild",
  "decreased_stat": {
    "name": "defense",
    "url": "/api/v2/stat/3/"
  },
  "increased_stat": {
    "name": "special-attack",
    "url": "/api/v2/stat/4/"
  },
  "likes_flavor": {
    "name": "dry",
    "url": "/api/v2/berry-flavor/2/"
  },
  "hates_flavor": {
    "name": "sour",
    "url": "/api/v2/berry-flavor/5/"
  },
  "pokeathlon_stat_changes": [
    {
      "max_change": -2,
      "pokeathlon_stat": {
        "name": "skill",
        "url": "/api/v2/pokeathlon-stat/3/"
      }
    },
    {
      "max_change": 2,
      "pokeathlon_stat": {
        "name": "jump",
        "url": "/api/v2/pokeathlon-stat/5/"
      }
    }
  ],
  "move_battle_style_preferences": [
    {
      "low_hp_preference": 34,
      "high_hp_preference": 44,
      "move_battle_style": {
        "name": "attack",
        "url": "/api/v2/move-battle-style/1/"
      }
    },
    {
      "low_hp_preference": 6,
      "high_hp_preference": 50,
      "move_battle_style": {
        "name": "defense",
        "url": "/api/v2/move-battle-style/2/"
      }
    },
    {
      "low_hp_preference": 60,
      "high_hp_preference": 6,
      "move_battle_style": {
        "name": "support",
        "url": "/api/v2/move-battle-style/3/"
      }
    }
  ],
  "names": [
    {
      "name": "おっとり",
      "language": {
        "name": "ja-hrkt",
        "url": "/api/v2/language/1/"
      }
    },
    {
      "name": "의젓",
      "language": {
        "name": "ko",
        "url": "/api/v2/language/3/"
      }
    },
    {
      "name": "慢吞吞",
      "language": {
        "name": "zh-hant",
        "url": "/api/v2/language/4/"
      }
    },
    {
      "name": "Doux",
      "language": {
        "name": "fr",
        "url": "/api/v2/language/5/"
      }
    },
    {
      "name": "Mild",
      "language": {
        "name": "de",
        "url": "/api/v2/language/6/"
      }
    },
    {
      "name": "Afable",
      "language": {
        "name": "es",
        "url": "/api/v2/language/7/"
      }
    },
    {
      "name": "Mite",
      "language": {
        "name": "it",
        "url": "/api/v2/language/8/"
      }
    },
    {
      "name": "Mild",
      "language": {
        "name": "en",
        "url": "/api/v2/language/9/"
      }
    },
    {
      "name": "おっとり",
      "language": {
        "name": "ja",
        "url": "/api/v2/language/11/"
      }
    },
    {
      "name": "慢吞吞",
      "language": {
        "name": "zh-hans",
        "url": "/api/v2/language/12/"
      }
    },
    {
      "name": "Cordial",
      "language": {
        "name": "es-419",
        "url": "/api/v2/language/14/"
      }
    }
  ]
}
