=== PokeAPI/api-data/data/schema/v2/encounter-condition-value/$id/index.json
{
  "$schema": "http://json-schema.org/schema#",
  "type": "object",
  "properties": {
    "id": {
      "type": "integer"
    },
    "name": {
      "type": "string"
    },
    "condition": {
      "$ref": "/schema/v2/named_api_resource.json"
    },
    "names": {
      "type": "array",
      "items": {
        "$ref": "/schema/v2/name.json"
      }
    }
  },
  "required": [
    "condition",
    "id",
    "name",
    "names"
  ]
}

=== PokeAPI/api-data/data/api/v2/encounter-condition-value/5/index.json
{
  "id": 5,
  "name": "time-night",
  "condition": {
    "name": "time",
    "url": "/api/v2/encounter-condition/2/"
  },
  "names": [
    {
      "name": "In der Nacht",
      "language": {
        "name": "de",
        "url": "/api/v2/language/6/"
      }
    },
    {
      "name": "At night",
      "language": {
        "name": "en",
        "url": "/api/v2/language/9/"
      }
    },
    {
      "name": "La nuit",
      "language": {
        "name": "fr",
        "url": "/api/v2/language/5/"
      }
    }
  ]
}

=== PokeAPI/api-data/data/api/v2/encounter-condition-value/295/index.json
{
  "id": 295,
  "name": "johto-safari-blocks-peak-min-35",
  "condition": {
    "name": "johto-safari-blocks",
    "url": "/api/v2/encounter-condition/26/"
  },
  "names": [
    {
      "name": "At least 35 Peak block points placed",
      "language": {
        "name": "en",
        "url": "/api/v2/language/9/"
      }
    }
  ]
}

=== PokeAPI/api-data/data/api/v2/encounter-condition-value/59/index.json
{
  "id": 59,
  "name": "weekday-sunday",
  "condition": {
    "name": "weekday",
    "url": "/api/v2/encounter-condition/12/"
  },
  "names": [
    {
      "name": "Sunday",
      "language": {
        "name": "en",
        "url": "/api/v2/language/9/"
      }
    },
    {
      "name": "Le dimanche",
      "language": {
        "name": "fr",
        "url": "/api/v2/language/5/"
      }
    }
  ]
}

=== PokeAPI/api-data/data/api/v2/encounter-condition-value/31/index.json
{
  "id": 31,
  "name": "story-progress-oak-eterna-city",
  "condition": {
    "name": "story-progress",
    "url": "/api/v2/encounter-condition/9/"
  },
  "names": [
    {
      "name": "Talked to Professor Oak at Eterna City",
      "language": {
        "name": "en",
        "url": "/api/v2/language/9/"
      }
    },
    {
      "name": "Après avoir parlé au Prof. Chen à Vestigion",
      "language": {
        "name": "fr",
        "url": "/api/v2/language/5/"
      }
    }
  ]
}

=== PokeAPI/api-data/api/v2/encounter-condition-value/19/index.json
{
    "condition": {
        "name": "season",
        "url": "http://127.0.0.1:8000/api/v2/encounter-condition/6/"
    },
    "id": 19,
    "name": "season-autumn",
    "names": [
        {
            "language": {
                "name": "de",
                "url": "http://127.0.0.1:8000/api/v2/language/6/"
            },
            "name": "Im Herbst"
        },
        {
            "language": {
                "name": "en",
                "url": "http://127.0.0.1:8000/api/v2/language/9/"
            },
            "name": "During Autumn"
        }
    ]
}
