=== PokeAPI/api-data/data/schema/v2/language/$id/index.json
{
  "$schema": "http://json-schema.org/schema#",
  "type": "object",
  "properties": {
    "id": {
      "type": "integer"
    },
    "name": {
      "type": "string"
    },
    "official": {
      "type": "boolean"
    },
    "iso639": {
      "type": "string"
    },
    "iso3166": {
      "type": "string"
    },
    "names": {
      "type": "array",
      "items": {
        "$ref": "/schema/v2/name.json"
      }
    }
  },
  "required": [
    "id",
    "iso3166",
    "iso639",
    "name",
    "names",
    "official"
  ]
}

=== PokeAPI/api-data/data/api/v2/language/10/index.json
{
  "id": 10,
  "name": "cs",
  "official": false,
  "iso639": "cs",
  "iso3166": "cz",
  "names": [
    {
      "name": "チェコ語",
      "language": {
        "name": "ja-hrkt",
        "url": "/api/v2/language/1/"
      }
    },
    {
      "name": "체코어",
      "language": {
        "name": "ko",
        "url": "/api/v2/language/3/"
      }
    },
    {
      "name": "Tchèque",
      "language": {
        "name": "fr",
        "url": "/api/v2/language/5/"
      }
    },
    {
      "name": "Tschechisch",
      "language": {
        "name": "de",
        "url": "/api/v2/language/6/"
      }
    },
    {
      "name": "Checo",
      "language": {
        "name": "es",
        "url": "/api/v2/language/7/"
      }
    },
    {
      "name": "Ceco",
      "language": {
        "name": "it",
        "url": "/api/v2/language/8/"
      }
    },
    {
      "name": "Czech",
      "language": {
        "name": "en",
        "url": "/api/v2/language/9/"
      }
    },
    {
      "name": "Tcheco",
      "language": {
        "name": "pt-br",
        "url": "/api/v2/language/13/"
      }
    },
    {
      "name": "Checo",
      "language": {
        "name": "es-419",
        "url": "/api/v2/language/14/"
      }
    }
  ]
}

=== PokeAPI/api-data/data/api/v2/language/9/index.json
{
  "id": 9,
  "name": "en",
  "official": true,
  "iso639": "en",
  "iso3166": "us",
  "names": [
    {
      "name": "英語",
      "language": {
        "name": "ja-hrkt",
        "url": "/api/v2/language/1/"
      }
    },
    {
      "name": "영어",
      "language": {
        "name": "ko",
        "url": "/api/v2/language/3/"
      }
    },
    {
      "name": "Anglais",
      "language": {
        "name": "fr",
        "url": "/api/v2/language/5/"
      }
    },
    {
      "name": "Englisch",
      "language": {
        "name": "de",
        "url": "/api/v2/language/6/"
      }
    },
    {
      "name": "Inglés",
      "language": {
        "name": "es",
        "url": "/api/v2/language/7/"
      }
    },
    {
      "name": "Inglese",
      "language": {
        "name": "it",
        "url": "/api/v2/language/8/"
      }
    },
    {
      "name": "English",
      "language": {
        "name": "en",
        "url": "/api/v2/language/9/"
      }
    },
    {
      "name": "Inglês",
      "language": {
        "name": "pt-br",
        "url": "/api/v2/language/13/"
      }
    },
    {
      "name": "Inglés",
      "language": {
        "name": "es-419",
        "url": "/api/v2/language/14/"
      }
    }
  ]
}
