=== PokeAPI/api-data/data/schema/v2/api_resource_list.json
{
  "$schema": "http://json-schema.org/schema#",
  "type": "object",
  "properties": {
    "count": {
      "type": "integer"
    },
    "next": {
      "type": [
        "null",
        "string"
      ]
    },
    "previous": {
      "type": [
        "null",
        "string"
      ]
    },
    "results": {
      "type": "array",
      "items": {
        "$ref": "/schema/v2/api_resource.json"
      }
    }
  },
  "required": [
    "count",
    "next",
    "previous",
    "results"
  ]
}

=== PokeAPI/api-data/data/api/v2/region/index.json
{
  "count": 11,
  "next": null,
  "previous": null,
  "results": [
    {
      "name": "kanto",
      "url": "/api/v2/region/1/"
    },
    {
      "name": "johto",
      "url": "/api/v2/region/2/"
    },
    {
      "name": "hoenn",
      "url": "/api/v2/region/3/"
    },
    {
      "name": "sinnoh",
      "url": "/api/v2/region/4/"
    },
    {
      "name": "unova",
      "url": "/api/v2/region/5/"
    },
    {
      "name": "kalos",
      "url": "/api/v2/region/6/"
    },
    {
      "name": "alola",
      "url": "/api/v2/region/7/"
    },
    {
      "name": "galar",
      "url": "/api/v2/region/8/"
    },
    {
      "name": "hisui",
      "url": "/api/v2/region/9/"
    },
    {
      "name": "paldea",
      "url": "/api/v2/region/10/"
    },
    {
      "name": "orre",
      "url": "/api/v2/region/11/"
    }
  ]
}

=== PokeAPI/api-data/data/api/v2/characteristic/index.json
{
  "count": 30,
  "next": null,
  "previous": null,
  "results": [
    {
      "url": "/api/v2/characteristic/1/"
    },
    {
      "url": "/api/v2/characteristic/2/"
    },
    {
      "url": "/api/v2/characteristic/3/"
    },
    {
      "url": "/api/v2/characteristic/4/"
    },
    {
      "url": "/api/v2/characteristic/5/"
    },
    {
      "url": "/api/v2/characteristic/6/"
    },
    {
      "url": "/api/v2/characteristic/7/"
    },
    {
      "url": "/api/v2/characteristic/8/"
    },
    {
      "url": "/api/v2/characteristic/9/"
    },
    {
      "url": "/api/v2/characteristic/10/"
    },
    {
      "url": "/api/v2/characteristic/11/"
    },
    {
      "url": "/api/v2/characteristic/12/"
    },
    {
      "url": "/api/v2/characteristic/13/"
    },
    {
      "url": "/api/v2/characteristic/14/"
    },
    {
      "url": "/api/v2/characteristic/15/"
    },
    {
      "url": "/api/v2/characteristic/16/"
    },
    {
      "url": "/api/v2/characteristic/17/"
    },
    {
      "url": "/api/v2/characteristic/18/"
    },
    {
      "url": "/api/v2/characteristic/19/"
    },
    {
      "url": "/api/v2/characteristic/20/"
    },
    {
      "url": "/api/v2/characteristic/21/"
    },
    {
      "url": "/api/v2/characteristic/22/"
    },
    {
      "url": "/api/v2/characteristic/23/"
    },
    {
      "url": "/api/v2/characteristic/24/"
    },
    {
      "url": "/api/v2/characteristic/25/"
    },
    {
      "url": "/api/v2/characteristic/26/"
    },
    {
      "url": "/api/v2/characteristic/27/"
    },
    {
      "url": "/api/v2/characteristic/28/"
    },
    {
      "url": "/api/v2/characteristic/29/"
    },
    {
      "url": "/api/v2/characteristic/30/"
    }
  ]
}
