=== PokeAPI/api-data/data/schema/v2/move/$id/index.json
{
  "$schema": "http://json-schema.org/schema#",
  "type": "object",
  "properties": {
    "id": {
      "type": "integer"
    },
    "name": {
      "type": "string"
    },
    "accuracy": {
      "type": [
        "integer",
        "null"
      ]
    },
    "effect_chance": {
      "type": [
        "integer",
        "null"
      ]
    },
    "pp": {
      "type": [
        "integer",
        "null"
      ]
    },
    "priority": {
      "type": "integer"
    },
    "power": {
      "type": [
        "integer",
        "null"
      ]
    },
    "contest_combos": {
      "anyOf": [
        {
          "type": "null"
        },
        {
          "type": "object",
          "properties": {
            "normal": {
              "type": "object",
              "properties": {
                "use_before": {
                  "anyOf": [
                    {
                      "type": "null"
                    },
                    {
                      "type": "array",
                      "items": {
                        "$ref": "/schema/v2/named_api_resource.json"
                      }
                    }
                  ]
                },
                "use_after": {
                  "anyOf": [
                    {
                      "type": "null"
                    },
                    {
                      "type": "array",
                      "items": {
                        "$ref": "/schema/v2/named_api_resource.json"
                      }
                    }
                  ]
                }
              },
              "required": [
                "use_after",
                "use_before"
              ]
            },
            "super": {
              "type": "object",
              "properties": {
                "use_before": {
                  "anyOf": [
                    {
                      "type": "null"
                    },
                    {
                      "type": "array",
                      "items": {
                        "$ref": "/schema/v2/named_api_resource.json"
                      }
                    }
                  ]
                },
                "use_after": {
                  "anyOf": [
                    {
                      "type": "null"
                    },
                    {
                      "type": "array",
                      "items": {
                        "$ref": "/schema/v2/named_api_resource.json"
                      }
                    }
                  ]
                }
              },
              "required": [
                "use_after",
                "use_before"
              ]
            }
          },
          "required": [
            "normal",
            "super"
          ]
        }
      ]
    },
    "contest_type": {
      "anyOf": [
        {
          "type": "null"
        },
        {
          "$ref": "/schema/v2/named_api_resource.json"
        }
      ]
    },
    "contest_effect": {
      "anyOf": [
        {
          "type": "null"
        },
        {
          "$ref": "/schema/v2/api_resource.json"
        }
      ]
    },
    "damage_class": {
      "$ref": "/schema/v2/named_api_resource.json"
    },
    "effect_entries": {
      "type": "array",
      "items": {
        "$ref": "/schema/v2/verbose_effect.json"
      }
    },
    "effect_changes": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "version_group": {
            "$ref": "/schema/v2/named_api_resource.json"
          },
          "effect_entries": {
            "type": "array",
            "items": {
              "$ref": "/schema/v2/effect.json"
            }
          }
        },
        "required": [
          "effect_entries",
          "version_group"
        ]
      }
    },
    "generation": {
      "$ref": "/schema/v2/named_api_resource.json"
    },
    "meta": {
      "anyOf": [
        {
          "type": "null"
        },
        {
          "type": "object",
          "properties": {
            "ailment": {
              "$ref": "/schema/v2/named_api_resource.json"
            },
            "category": {
              "$ref": "/schema/v2/named_api_resource.json"
            },
            "min_hits": {
              "type": [
                "integer",
                "null"
              ]
            },
            "max_hits": {
              "type": [
                "integer",
                "null"
              ]
            },
            "min_turns": {
              "type": [
                "integer",
                "null"
              ]
            },
            "max_turns": {
              "type": [
                "integer",
                "null"
              ]
            },
            "drain": {
              "type": "integer"
            },
            "healing": {
              "type": "integer"
            },
            "crit_rate": {
              "type": "integer"
            },
            "ailment_chance": {
              "type": "integer"
            },
            "flinch_chance": {
              "type": "integer"
            },
            "stat_chance": {
              "type": "integer"
            }
          },
          "required": [
            "ailment",
            "ailment_chance",
            "category",
            "crit_rate",
            "drain",
            "flinch_chance",
            "healing",
            "max_hits",
            "max_turns",
            "min_hits",
            "min_turns",
            "stat_chance"
          ]
        }
      ]
    },
    "names": {
      "type": "array",
      "items": {
        "$ref": "/schema/v2/name.json"
      }
    },
    "past_values": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "accuracy": {
            "type": [
              "integer",
              "null"
            ]
          },
          "power": {
            "type": [
              "integer",
              "null"
            ]
          },
          "pp": {
            "type": [
              "integer",
              "null"
            ]
          },
          "effect_chance": {
            "type": [
              "integer",
              "null"
            ]
          },
          "effect_entries": {
            "type": "array",
            "items": {
              "$ref": "/schema/v2/verbose_effect.json"
            }
          },
          "type": {
            "anyOf": [
              {
                "type": "null"
              },
              {
                "$ref": "/schema/v2/named_api_resource.json"
              }
            ]
          },
          "version_group": {
            "$ref": "/schema/v2/named_api_resource.json"
          }
        },
        "required": [
          "accuracy",
          "effect_chance",
          "effect_entries",
          "power",
          "pp",
          "type",
          "version_group"
        ]
      }
    },
    "stat_changes": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "change": {
            "type": "integer"
          },
          "stat": {
            "$ref": "/schema/v2/named_api_resource.json"
          }
        },
        "required": [
          "change",
          "stat"
        ]
      }
    },
    "super_contest_effect": {
      "anyOf": [
        {
          "type": "null"
        },
        {
          "$ref": "/schema/v2/api_resource.json"
        }
      ]
    },
    "target": {
      "$ref": "/schema/v2/named_api_resource.json"
    },
    "type": {
      "$ref": "/schema/v2/named_api_resource.json"
    },
    "machines": {
      "type": "array",
      "items": {
        "$ref": "/schema/v2/machine_version_detail.json"
      }
    },
    "flavor_text_entries": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "flavor_text": {
            "type": "string"
          },
          "language": {
            "$ref": "/schema/v2/named_api_resource.json"
          },
          "version_group": {
            "$ref": "/schema/v2/named_api_resource.json"
          }
        },
        "required": [
          "flavor_text",
          "language",
          "version_group"
        ]
      }
    },
    "learned_by_pokemon": {
      "type": "array",
      "items": {
        "$ref": "/schema/v2/named_api_resource.json"
      }
    }
  },
  "required": [
    "accuracy",
    "contest_combos",
    "contest_effect",
    "contest_type",
    "damage_class",
    "effect_chance",
    "effect_changes",
    "effect_entries",
    "flavor_text_entries",
    "generation",
    "id",
    "learned_by_pokemon",
    "machines",
    "meta",
    "name",
    "names",
    "past_values",
    "power",
    "pp",
    "priority",
    "stat_changes",
    "super_contest_effect",
    "target",
    "type"
  ]
}

=== PokeAPI/api-data/data/api/v2/move/915/index.json
{
  "id": 915,
  "name": "temper-flare",
  "accuracy": 100,
  "effect_chance": null,
  "pp": 10,
  "priority": 0,
  "power": 75,
  "contest_combos": null,
  "contest_type": null,
  "contest_effect": null,
  "damage_class": {
    "name": "physical",
    "url": "/api/v2/move-damage-class/2/"
  },
  "effect_entries": [],
  "effect_changes": [],
  "generation": {
    "name": "generation-ix",
    "url": "/api/v2/generation/9/"
  },
  "meta": null,
  "names": [
    {
      "name": "やけっぱち",
      "language": {
        "name": "ja-hrkt",
        "url": "/api/v2/language/1/"
      }
    },
    {
      "name": "열불내기",
      "language": {
        "name": "ko",
        "url": "/api/v2/language/3/"
      }
    },
    {
      "name": "豁出去",
      "language": {
        "name": "zh-hant",
        "url": "/api/v2/language/4/"
      }
    },
    {
      "name": "Indignition",
      "language": {
        "name": "fr",
        "url": "/api/v2/language/5/"
      }
    },
    {
      "name": "Frustflamme",
      "language": {
        "name": "de",
        "url": "/api/v2/language/6/"
      }
    },
    {
      "name": "Cólera Ardiente",
      "language": {
        "name": "es",
        "url": "/api/v2/language/7/"
      }
    },
    {
      "name": "Rabbia Bruciante",
      "language": {
        "name": "it",
        "url": "/api/v2/language/8/"
      }
    },
    {
      "name": "Temper Flare",
      "language": {
        "name": "en",
        "url": "/api/v2/language/9/"
      }
    },
    {
      "name": "やけっぱち",
      "language": {
        "name": "ja",
        "url": "/api/v2/language/11/"
      }
    },
    {
      "name": "豁出去",
      "language": {
        "name": "zh-hans",
        "url": "/api/v2/language/12/"
      }
    },
    {
      "name": "Furia Ardiente",
      "language": {
        "name": "es-419",
        "url": "/api/v2/language/14/"
      }
    }
  ],
  "past_values": [],
  "stat_changes": [],
  "super_contest_effect": null,
  "target": {
    "name": "selected-pokemon",
    "url": "/api/v2/move-target/10/"
  },
  "type": {
    "name": "fire",
    "url": "/api/v2/type/10/"
  },
  "machines": [
    {
      "machine": {
        "url": "/api/v2/machine/2022/"
      },
      "version_group": {
        "name": "scarlet-violet",
        "url": "/api/v2/version-group/25/"
      }
    },
    {
      "machine": {
        "url": "/api/v2/machine/2190/"
      },
      "version_group": {
        "name": "the-indigo-disk",
        "url": "/api/v2/version-group/27/"
      }
    }
  ],
  "flavor_text_entries": [
    {
      "flavor_text": "Le lanceur utilise la force de son dépit pour attaquer. S'il a utilisé une capacité qui a échoué au tour précédent, la puissance d'Indignition est doublée.",
      "language": {
        "name": "fr",
        "url": "/api/v2/language/5/"
      },
      "version_group": {
        "name": "scarlet-violet",
        "url": "/api/v2/version-group/25/"
      }
    },
    {
      "flavor_text": "Spurred by desperation, the user attacks the target. This move's power is doubled if the user's previous move failed.",
      "language": {
        "name": "en",
        "url": "/api/v2/language/9/"
      },
      "version_group": {
        "name": "scarlet-violet",
        "url": "/api/v2/version-group/25/"
      }
    }
  ],
  "learned_by_pokemon": [
    {
      "name": "charmander",
      "url": "/api/v2/pokemon/4/"
    },
    {
      "name": "charmeleon",
      "url": "/api/v2/pokemon/5/"
    },
    {
      "name": "charizard",
      "url": "/api/v2/pokemon/6/"
    },
    {
      "name": "growlithe",
      "url": "/api/v2/pokemon/58/"
    },
    {
      "name": "arcanine",
      "url": "/api/v2/pokemon/59/"
    },
    {
      "name": "magmar",
      "url": "/api/v2/pokemon/126/"
    },
    {
      "name": "gyarados",
      "url": "/api/v2/pokemon/130/"
    },
    {
      "name": "flareon",
      "url": "/api/v2/pokemon/136/"
    },
    {
      "name": "moltres",
      "url": "/api/v2/pokemon/146/"
    },
    {
      "name": "mew",
      "url": "/api/v2/pokemon/151/"
    },
    {
      "name": "cyndaquil",
      "url": "/api/v2/pokemon/155/"
    },
    {
      "name": "quilava",
      "url": "/api/v2/pokemon/156/"
    },
    {
      "name": "typhlosion",
      "url": "/api/v2/pokemon/157/"
    },
    {
      "name": "snubbull",
      "url": "/api/v2/pokemon/209/"
    },
    {
      "name": "granbull",
      "url": "/api/v2/pokemon/210/"
    },
    {
      "name": "slugma",
      "url": "/api/v2/pokemon/218/"
    },
    {
      "name": "magcargo",
      "url": "/api/v2/pokemon/219/"
    },
    {
      "name": "houndour",
      "url": "/api/v2/pokemon/228/"
    },
    {
      "name": "houndoom",
      "url": "/api/v2/pokemon/229/"
    },
    {
      "name": "magby",
      "url": "/api/v2/pokemon/240/"
    },
    {
      "name": "torchic",
      "url": "/api/v2/pokemon/255/"
    },
    {
      "name": "combusken",
      "url": "/api/v2/pokemon/256/"
    },
    {
      "name": "blaziken",
      "url": "/api/v2/pokemon/257/"
    },
    {
      "name": "numel",
      "url": "/api/v2/pokemon/322/"
    },
    {
      "name": "camerupt",
      "url": "/api/v2/pokemon/323/"
    },
    {
      "name": "torkoal",
      "url": "/api/v2/pokemon/324/"
    },
    {
      "name": "shelgon",
      "url": "/api/v2/pokemon/372/"
    },
    {
      "name": "salamence",
      "url": "/api/v2/pokemon/373/"
    },
    {
      "name": "chimchar",
      "url": "/api/v2/pokemon/390/"
    },
    {
      "name": "monferno",
      "url": "/api/v2/pokemon/391/"
    },
    {
      "name": "infernape",
      "url": "/api/v2/pokemon/392/"
    },
    {
      "name": "drifloon",
      "url": "/api/v2/pokemon/425/"
    },
    {
      "name": "drifblim",
      "url": "/api/v2/pokemon/426/"
    },
    {
      "name": "stunky",
      "url": "/api/v2/pokemon/434/"
    },
    {
      "name": "skuntank",
      "url": "/api/v2/pokemon/435/"
    },
    {
      "name": "rhyperior",
      "url": "/api/v2/pokemon/464/"
    },
    {
      "name": "magmortar",
      "url": "/api/v2/pokemon/467/"
    },
    {
      "name": "tepig",
      "url": "/api/v2/pokemon/498/"
    },
    {
      "name": "pignite",
      "url": "/api/v2/pokemon/499/"
    },
    {
      "name": "emboar",
      "url": "/api/v2/pokemon/500/"
    },
    {
      "name": "simisear",
      "url": "/api/v2/pokemon/514/"
    },
    {
      "name": "litwick",
      "url": "/api/v2/pokemon/607/"
    },
    {
      "name": "lampent",
      "url": "/api/v2/pokemon/608/"
    },
    {
      "name": "chandelure",
      "url": "/api/v2/pokemon/609/"
    },
    {
      "name": "fletchinder",
      "url": "/api/v2/pokemon/662/"
    },
    {
      "name": "talonflame",
      "url": "/api/v2/pokemon/663/"
    },
    {
      "name": "pyroar-male",
      "url": "/api/v2/pokemon/668/"
    },
    {
      "name": "litten",
      "url": "/api/v2/pokemon/725/"
    },
    {
      "name": "torracat",
      "url": "/api/v2/pokemon/726/"
    },
    {
      "name": "incineroar",
      "url": "/api/v2/pokemon/727/"
    },
    {
      "name": "toucannon",
      "url": "/api/v2/pokemon/733/"
    },
    {
      "name": "salandit",
      "url": "/api/v2/pokemon/757/"
    },
    {
      "name": "salazzle",
      "url": "/api/v2/pokemon/758/"
    },
    {
      "name": "scorbunny",
      "url": "/api/v2/pokemon/813/"
    },
    {
      "name": "raboot",
      "url": "/api/v2/pokemon/814/"
    },
    {
      "name": "cinderace",
      "url": "/api/v2/pokemon/815/"
    },
    {
      "name": "rolycoly",
      "url": "/api/v2/pokemon/837/"
    },
    {
      "name": "carkol",
      "url": "/api/v2/pokemon/838/"
    },
    {
      "name": "coalossal",
      "url": "/api/v2/pokemon/839/"
    },
    {
      "name": "fuecoco",
      "url": "/api/v2/pokemon/909/"
    },
    {
      "name": "crocalor",
      "url": "/api/v2/pokemon/910/"
    },
    {
      "name": "skeledirge",
      "url": "/api/v2/pokemon/911/"
    },
    {
      "name": "klawf",
      "url": "/api/v2/pokemon/950/"
    },
    {
      "name": "scovillain",
      "url": "/api/v2/pokemon/952/"
    },
    {
      "name": "revavroom",
      "url": "/api/v2/pokemon/966/"
    },
    {
      "name": "cyclizar",
      "url": "/api/v2/pokemon/967/"
    },
    {
      "name": "great-tusk",
      "url": "/api/v2/pokemon/984/"
    },
    {
      "name": "slither-wing",
      "url": "/api/v2/pokemon/988/"
    },
    {
      "name": "chi-yu",
      "url": "/api/v2/pokemon/1004/"
    },
    {
      "name": "koraidon",
      "url": "/api/v2/pokemon/1007/"
    },
    {
      "name": "gouging-fire",
      "url": "/api/v2/pokemon/1020/"
    },
    {
      "name": "charizard-mega-x",
      "url": "/api/v2/pokemon/10034/"
    },
    {
      "name": "charizard-mega-y",
      "url": "/api/v2/pokemon/10035/"
    },
    {
      "name": "gyarados-mega",
      "url": "/api/v2/pokemon/10041/"
    },
    {
      "name": "houndoom-mega",
      "url": "/api/v2/pokemon/10048/"
    },
    {
      "name": "blaziken-mega",
      "url": "/api/v2/pokemon/10050/"
    },
    {
      "name": "camerupt-mega",
      "url": "/api/v2/pokemon/10087/"
    },
    {
      "name": "growlithe-hisui",
      "url": "/api/v2/pokemon/10229/"
    },
    {
      "name": "arcanine-hisui",
      "url": "/api/v2/pokemon/10230/"
    },
    {
      "name": "typhlosion-hisui",
      "url": "/api/v2/pokemon/10233/"
    },
    {
      "name": "tauros-paldea-blaze-breed",
      "url": "/api/v2/pokemon/10251/"
    },
    {
      "name": "emboar-mega",
      "url": "/api/v2/pokemon/10286/"
    },
    {
      "name": "chandelure-mega",
      "url": "/api/v2/pokemon/10291/"
    },
    {
      "name": "pyroar-mega",
      "url": "/api/v2/pokemon/10295/"
    },
    {
      "name": "scovillain-mega",
      "url": "/api/v2/pokemon/10320/"
    }
  ]
}
