=== PokeAPI/api-data/data/schema/v2/move/$id/index.json
{
  "$schema": "http://json-schema.org/schema#",
  "type": "object",
  "properties": {
    "id": {
      "type": "integer"
    },
    "name": {
      "type": "string"
    },
    "accuracy": {
      "type": [
        "integer",
        "null"
      ]
    },
    "effect_chance": {
      "type": [
        "integer",
        "null"
      ]
    },
    "pp": {
      "type": [
        "integer",
        "null"
      ]
    },
    "priority": {
      "type": "integer"
    },
    "power": {
      "type": [
        "integer",
        "null"
      ]
    },
    "contest_combos": {
      "anyOf": [
        {
          "type": "null"
        },
        {
          "type": "object",
          "properties": {
            "normal": {
              "type": "object",
              "properties": {
                "use_before": {
                  "anyOf": [
                    {
                      "type": "null"
                    },
                    {
                      "type": "array",
                      "items": {
                        "$ref": "/schema/v2/named_api_resource.json"
                      }
                    }
                  ]
                },
                "use_after": {
                  "anyOf": [
                    {
                      "type": "null"
                    },
                    {
                      "type": "array",
                      "items": {
                        "$ref": "/schema/v2/named_api_resource.json"
                      }
                    }
                  ]
                }
              },
              "required": [
                "use_after",
                "use_before"
              ]
            },
            "super": {
              "type": "object",
              "properties": {
                "use_before": {
                  "anyOf": [
                    {
                      "type": "null"
                    },
                    {
                      "type": "array",
                      "items": {
                        "$ref": "/schema/v2/named_api_resource.json"
                      }
                    }
                  ]
                },
                "use_after": {
                  "anyOf": [
                    {
                      "type": "null"
                    },
                    {
                      "type": "array",
                      "items": {
                        "$ref": "/schema/v2/named_api_resource.json"
                      }
                    }
                  ]
                }
              },
              "required": [
                "use_after",
                "use_before"
              ]
            }
          },
          "required": [
            "normal",
            "super"
          ]
        }
      ]
    },
    "contest_type": {
      "anyOf": [
        {
          "type": "null"
        },
        {
          "$ref": "/schema/v2/named_api_resource.json"
        }
      ]
    },
    "contest_effect": {
      "anyOf": [
        {
          "type": "null"
        },
        {
          "$ref": "/schema/v2/api_resource.json"
        }
      ]
    },
    "damage_class": {
      "$ref": "/schema/v2/named_api_resource.json"
    },
    "effect_entries": {
      "type": "array",
      "items": {
        "$ref": "/schema/v2/verbose_effect.json"
      }
    },
    "effect_changes": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "version_group": {
            "$ref": "/schema/v2/named_api_resource.json"
          },
          "effect_entries": {
            "type": "array",
            "items": {
              "$ref": "/schema/v2/effect.json"
            }
          }
        },
        "required": [
          "effect_entries",
          "version_group"
        ]
      }
    },
    "generation": {
      "$ref": "/schema/v2/named_api_resource.json"
    },
    "meta": {
      "anyOf": [
        {
          "type": "null"
        },
        {
          "type": "object",
          "properties": {
            "ailment": {
              "$ref": "/schema/v2/named_api_resource.json"
            },
            "category": {
              "$ref": "/schema/v2/named_api_resource.json"
            },
            "min_hits": {
              "type": [
                "integer",
                "null"
              ]
            },
            "max_hits": {
              "type": [
                "integer",
                "null"
              ]
            },
            "min_turns": {
              "type": [
                "integer",
                "null"
              ]
            },
            "max_turns": {
              "type": [
                "integer",
                "null"
              ]
            },
            "drain": {
              "type": "integer"
            },
            "healing": {
              "type": "integer"
            },
            "crit_rate": {
              "type": "integer"
            },
            "ailment_chance": {
              "type": "integer"
            },
            "flinch_chance": {
              "type": "integer"
            },
            "stat_chance": {
              "type": "integer"
            }
          },
          "required": [
            "ailment",
            "ailment_chance",
            "category",
            "crit_rate",
            "drain",
            "flinch_chance",
            "healing",
            "max_hits",
            "max_turns",
            "min_hits",
            "min_turns",
            "stat_chance"
          ]
        }
      ]
    },
    "names": {
      "type": "array",
      "items": {
        "$ref": "/schema/v2/name.json"
      }
    },
    "past_values": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "accuracy": {
            "type": [
              "integer",
              "null"
            ]
          },
          "power": {
            "type": [
              "integer",
              "null"
            ]
          },
          "pp": {
            "type": [
              "integer",
              "null"
            ]
          },
          "effect_chance": {
            "type": [
              "integer",
              "null"
            ]
          },
          "effect_entries": {
            "type": "array",
            "items": {
              "$ref": "/schema/v2/verbose_effect.json"
            }
          },
          "type": {
            "anyOf": [
              {
                "type": "null"
              },
              {
                "$ref": "/schema/v2/named_api_resource.json"
              }
            ]
          },
          "version_group": {
            "$ref": "/schema/v2/named_api_resource.json"
          }
        },
        "required": [
          "accuracy",
          "effect_chance",
          "effect_entries",
          "power",
          "pp",
          "type",
          "version_group"
        ]
      }
    },
    "stat_changes": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "change": {
            "type": "integer"
          },
          "stat": {
            "$ref": "/schema/v2/named_api_resource.json"
          }
        },
        "required": [
          "change",
          "stat"
        ]
      }
    },
    "super_contest_effect": {
      "anyOf": [
        {
          "type": "null"
        },
        {
          "$ref": "/schema/v2/api_resource.json"
        }
      ]
    },
    "target": {
      "$ref": "/schema/v2/named_api_resource.json"
    },
    "type": {
      "$ref": "/schema/v2/named_api_resource.json"
    },
    "machines": {
      "type": "array",
      "items": {
        "$ref": "/schema/v2/machine_version_detail.json"
      }
    },
    "flavor_text_entries": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "flavor_text": {
            "type": "string"
          },
          "language": {
            "$ref": "/schema/v2/named_api_resource.json"
          },
          "version_group": {
            "$ref": "/schema/v2/named_api_resource.json"
          }
        },
        "required": [
          "flavor_text",
          "language",
          "version_group"
        ]
      }
    },
    "learned_by_pokemon": {
      "type": "array",
      "items": {
        "$ref": "/schema/v2/named_api_resource.json"
      }
    }
  },
  "required": [
    "accuracy",
    "contest_combos",
    "contest_effect",
    "contest_type",
    "damage_class",
    "effect_chance",
    "effect_changes",
    "effect_entries",
    "flavor_text_entries",
    "generation",
    "id",
    "learned_by_pokemon",
    "machines",
    "meta",
    "name",
    "names",
    "past_values",
    "power",
    "pp",
    "priority",
    "stat_changes",
    "super_contest_effect",
    "target",
    "type"
  ]
}

=== PokeAPI/api-data/data/api/v2/move/889/index.json
{
    "accuracy": 100,
    "contest_combos": null,
    "contest_effect": null,
    "contest_type": null,
    "damage_class": {
        "name": "physical",
        "url": "/api/v2/move-damage-class/2/"
    },
    "effect_chance": null,
    "effect_changes": [],
    "effect_entries": [],
    "flavor_text_entries": [
        {
            "flavor_text": "Le lanceur transforme sa col\u00e8re en \u00e9nergie pour attaquer. Plus il a subi d'attaques, plus la puissance de cette capacit\u00e9 augmente.",
            "language": {
                "name": "fr",
                "url": "/api/v2/language/5/"
            },
            "version_group": {
                "name": "scarlet-violet",
                "url": "/api/v2/version-group/25/"
            }
        },
        {
            "flavor_text": "The user converts its rage into energy to attack. The more times the user has been hit by attacks, the greater the move's power.",
            "language": {
                "name": "en",
                "url": "/api/v2/language/9/"
            },
            "version_group": {
                "name": "scarlet-violet",
                "url": "/api/v2/version-group/25/"
            }
        }
    ],
    "generation": {
        "name": "generation-ix",
        "url": "/api/v2/generation/9/"
    },
    "id": 889,
    "learned_by_pokemon": [
        {
            "name": "primeape",
            "url": "/api/v2/pokemon/57/"
        },
        {
            "name": "annihilape",
            "url": "/api/v2/pokemon/979/"
        }
    ],
    "machines": [],
    "meta": null,
    "name": "rage-fist",
    "names": [
        {
            "language": {
                "name": "ja-hrkt",
                "url": "/api/v2/language/1/"
            },
            "name": "\u3075\u3093\u3069\u306e\u3053\u3076\u3057"
        },
        {
            "language": {
                "name": "ko",
                "url": "/api/v2/language/3/"
            },
            "name": "\ubd84\ub178\uc758\uc8fc\uba39"
        },
        {
            "language": {
                "name": "zh-hant",
                "url": "/api/v2/language/4/"
            },
            "name": "\u61a4\u6012\u4e4b\u62f3"
        },
        {
            "language": {
                "name": "fr",
                "url": "/api/v2/language/5/"
            },
            "name": "Poing de Col\u00e8re"
        },
        {
            "language": {
                "name": "de",
                "url": "/api/v2/language/6/"
            },
            "name": "Zornesfaust"
        },
        {
            "language": {
                "name": "it",
                "url": "/api/v2/language/8/"
            },
            "name": "Pugno Furibondo"
        },
        {
            "language": {
                "name": "en",
                "url": "/api/v2/language/9/"
            },
            "name": "Rage Fist"
        },
        {
            "language": {
                "name": "ja",
                "url": "/api/v2/language/11/"
            },
            "name": "\u3075\u3093\u3069\u306e\u3053\u3076\u3057"
        },
        {
            "language": {
                "name": "zh-hans",
                "url": "/api/v2/language/12/"
            },
            "name": "\u6124\u6012\u4e4b\u62f3"
        },
        {
            "language": {
                "name": "es-419",
                "url": "/api/v2/language/14/"
            },
            "name": "Pu\u00f1o Furia"
        },
        {
            "language": {
                "name": "es",
                "url": "/api/v2/language/7/"
            },
            "name": "Pu\u00f1o Furia"
        }
    ],
    "past_values": [],
    "power": 50,
    "pp": 10,
    "priority": 0,
    "stat_changes": [],
    "super_contest_effect": null,
    "target": {
        "name": "selected-pokemon",
        "url": "/api/v2/move-target/10/"
    },
    "type": {
        "name": "ghost",
        "url": "/api/v2/type/8/"
    }
}

=== PokeAPI/api-data/data/api/v2/move/10015/index.json
{
  "id": 10015,
  "name": "shadow-mist",
  "accuracy": 100,
  "effect_chance": null,
  "pp": null,
  "priority": 0,
  "power": null,
  "contest_combos": null,
  "contest_type": null,
  "contest_effect": null,
  "damage_class": {
    "name": "status",
    "url": "/api/v2/move-damage-class/1/"
  },
  "effect_entries": [
    {
      "effect": "Diminue l'esquive de la cible de deux niveaux.",
      "short_effect": "Diminue l'esquive de la cible de deux niveaux.",
      "language": {
        "name": "fr",
        "url": "/api/v2/language/5/"
      }
    },
    {
      "effect": "Lowers the target’s evasion by two stages.",
      "short_effect": "Lowers the target’s evasion by two stages.",
      "language": {
        "name": "en",
        "url": "/api/v2/language/9/"
      }
    }
  ],
  "effect_changes": [],
  "generation": {
    "name": "generation-iii",
    "url": "/api/v2/generation/3/"
  },
  "meta": null,
  "names": [
    {
      "name": "ダークミスト",
      "language": {
        "name": "ja-hrkt",
        "url": "/api/v2/language/1/"
      }
    },
    {
      "name": "Brume Noire",
      "language": {
        "name": "fr",
        "url": "/api/v2/language/5/"
      }
    },
    {
      "name": "Cryptodunst",
      "language": {
        "name": "de",
        "url": "/api/v2/language/6/"
      }
    },
    {
      "name": "Bruma Oscura",
      "language": {
        "name": "es",
        "url": "/api/v2/language/7/"
      }
    },
    {
      "name": "Nebbiascura",
      "language": {
        "name": "it",
        "url": "/api/v2/language/8/"
      }
    },
    {
      "name": "Shadow Mist",
      "language": {
        "name": "en",
        "url": "/api/v2/language/9/"
      }
    },
    {
      "name": "Bruma Oscura",
      "language": {
        "name": "es-419",
        "url": "/api/v2/language/14/"
      }
    }
  ],
  "past_values": [],
  "stat_changes": [],
  "super_contest_effect": null,
  "target": {
    "name": "opponents-field",
    "url": "/api/v2/move-target/6/"
  },
  "type": {
    "name": "shadow",
    "url": "/api/v2/type/10002/"
  },
  "machines": [],
  "flavor_text_entries": [],
  "learned_by_pokemon": []
}

=== PokeAPI/api-data/data/api/v2/move/748/index.json
{
  "id": 748,
  "name": "no-retreat",
  "accuracy": null,
  "effect_chance": 100,
  "pp": 5,
  "priority": 0,
  "power": null,
  "contest_combos": null,
  "contest_type": null,
  "contest_effect": null,
  "damage_class": {
    "name": "status",
    "url": "/api/v2/move-damage-class/1/"
  },
  "effect_entries": [
    {
      "effect": "Prevents user from switching out. Raises all of the user’s stats by one stage. The user or target may switch out using, Baton Pass, Flip turn, Parting Shot, Teleport, U-Turn, or Volt Switch. Fails if the user already has prevented itself from switching by this effect.",
      "short_effect": "Prevents user from switching out. Raises all of the user’s stats by one stage.",
      "language": {
        "name": "en",
        "url": "/api/v2/language/9/"
      }
    }
  ],
  "effect_changes": [],
  "generation": {
    "name": "generation-viii",
    "url": "/api/v2/generation/8/"
  },
  "meta": {
    "ailment": {
      "name": "none",
      "url": "/api/v2/move-ailment/0/"
    },
    "category": {
      "name": "net-good-stats",
      "url": "/api/v2/move-category/2/"
    },
    "min_hits": null,
    "max_hits": null,
    "min_turns": null,
    "max_turns": null,
    "drain": 0,
    "healing": 0,
    "crit_rate": 0,
    "ailment_chance": 0,
    "flinch_chance": 0,
    "stat_chance": 100
  },
  "names": [
    {
      "name": "はいすいのじん",
      "language": {
        "name": "ja-hrkt",
        "url": "/api/v2/language/1/"
      }
    },
    {
      "name": "배수의진",
      "language": {
        "name": "ko",
        "url": "/api/v2/language/3/"
      }
    },
    {
      "name": "背水一戰",
      "language": {
        "name": "zh-hant",
        "url": "/api/v2/language/4/"
      }
    },
    {
      "name": "Ultime Bastion",
      "language": {
        "name": "fr",
        "url": "/api/v2/language/5/"
      }
    },
    {
      "name": "Finalformation",
      "language": {
        "name": "de",
        "url": "/api/v2/language/6/"
      }
    },
    {
      "name": "Bastión Final",
      "language": {
        "name": "es",
        "url": "/api/v2/language/7/"
      }
    },
    {
      "name": "Spalle al Muro",
      "language": {
        "name": "it",
        "url": "/api/v2/language/8/"
      }
    },
    {
      "name": "No Retreat",
      "language": {
        "name": "en",
        "url": "/api/v2/language/9/"
      }
    },
    {
      "name": "はいすいのじん",
      "language": {
        "name": "ja",
        "url": "/api/v2/language/11/"
      }
    },
    {
      "name": "背水一战",
      "language": {
        "name": "zh-hans",
        "url": "/api/v2/language/12/"
      }
    },
    {
      "name": "Bastión Final",
      "language": {
        "name": "es-419",
        "url": "/api/v2/language/14/"
      }
    }
  ],
  "past_values": [],
  "stat_changes": [
    {
      "change": 1,
      "stat": {
        "name": "attack",
        "url": "/api/v2/stat/2/"
      }
    },
    {
      "change": 1,
      "stat": {
        "name": "defense",
        "url": "/api/v2/stat/3/"
      }
    },
    {
      "change": 1,
      "stat": {
        "name": "special-attack",
        "url": "/api/v2/stat/4/"
      }
    },
    {
      "change": 1,
      "stat": {
        "name": "special-defense",
        "url": "/api/v2/stat/5/"
      }
    },
    {
      "change": 1,
      "stat": {
        "name": "speed",
        "url": "/api/v2/stat/6/"
      }
    }
  ],
  "super_contest_effect": null,
  "target": {
    "name": "user",
    "url": "/api/v2/move-target/7/"
  },
  "type": {
    "name": "fighting",
    "url": "/api/v2/type/2/"
  },
  "machines": [],
  "flavor_text_entries": [
    {
      "flavor_text": "じぶんの　すべての\nのうりょくが　あがるが　こうたい　したり\nにげることが　できなくなる。",
      "language": {
        "name": "ja-hrkt",
        "url": "/api/v2/language/1/"
      },
      "version_group": {
        "name": "sword-shield",
        "url": "/api/v2/version-group/20/"
      }
    },
    {
      "flavor_text": "자신의 모든 능력이\n올라가지만 교체하거나\n도망칠 수 없게 된다.",
      "language": {
        "name": "ko",
        "url": "/api/v2/language/3/"
      },
      "version_group": {
        "name": "sword-shield",
        "url": "/api/v2/version-group/20/"
      }
    },
    {
      "flavor_text": "提高自己所有的能力，\n但無法進行替換或逃走。",
      "language": {
        "name": "zh-hant",
        "url": "/api/v2/language/4/"
      },
      "version_group": {
        "name": "sword-shield",
        "url": "/api/v2/version-group/20/"
      }
    },
    {
      "flavor_text": "Le lanceur voit toutes ses stats augmenter,\nmais en contrepartie, il ne peut plus fuir\nou se retirer du combat.",
      "language": {
        "name": "fr",
        "url": "/api/v2/language/5/"
      },
      "version_group": {
        "name": "sword-shield",
        "url": "/api/v2/version-group/20/"
      }
    },
    {
      "flavor_text": "Alle Statuswerte des Anwenders werden erhöht,\naber dafür kann er weder ausgewechselt werden\nnoch fliehen.",
      "language": {
        "name": "de",
        "url": "/api/v2/language/6/"
      },
      "version_group": {
        "name": "sword-shield",
        "url": "/api/v2/version-group/20/"
      }
    },
    {
      "flavor_text": "El usuario aumenta todas sus características, pero ya no\npuede huir ni ser cambiado por otro.",
      "language": {
        "name": "es",
        "url": "/api/v2/language/7/"
      },
      "version_group": {
        "name": "sword-shield",
        "url": "/api/v2/version-group/20/"
      }
    },
    {
      "flavor_text": "Chi la usa aumenta tutte le sue statistiche ma non\npuò più fuggire o essere sostituito.",
      "language": {
        "name": "it",
        "url": "/api/v2/language/8/"
      },
      "version_group": {
        "name": "sword-shield",
        "url": "/api/v2/version-group/20/"
      }
    },
    {
      "flavor_text": "This move raises all the user’s stats but prevents\nthe user from switching out or fleeing.",
      "language": {
        "name": "en",
        "url": "/api/v2/language/9/"
      },
      "version_group": {
        "name": "sword-shield",
        "url": "/api/v2/version-group/20/"
      }
    },
    {
      "flavor_text": "自分の　すべての\n能力が　上がるが　交代　したり\n逃げることが　できなくなる。",
      "language": {
        "name": "ja",
        "url": "/api/v2/language/11/"
      },
      "version_group": {
        "name": "sword-shield",
        "url": "/api/v2/version-group/20/"
      }
    },
    {
      "flavor_text": "提高自己的所有能力，\n但无法替换或逃走。",
      "language": {
        "name": "zh-hans",
        "url": "/api/v2/language/12/"
      },
      "version_group": {
        "name": "sword-shield",
        "url": "/api/v2/version-group/20/"
      }
    },
    {
      "flavor_text": "El usuario aumenta todas sus características, pero ya no\npuede huir ni ser cambiado por otro.",
      "language": {
        "name": "es-419",
        "url": "/api/v2/language/14/"
      },
      "version_group": {
        "name": "sword-shield",
        "url": "/api/v2/version-group/20/"
      }
    },
    {
      "flavor_text": "This move raises all the user's stats but prevents the user from switching out or fleeing.",
      "language": {
        "name": "en",
        "url": "/api/v2/language/9/"
      },
      "version_group": {
        "name": "legends-arceus",
        "url": "/api/v2/version-group/24/"
      }
    },
    {
      "flavor_text": "This move boosts all the user's stats but prevents the user from switching out or fleeing.",
      "language": {
        "name": "en",
        "url": "/api/v2/language/9/"
      },
      "version_group": {
        "name": "scarlet-violet",
        "url": "/api/v2/version-group/25/"
      }
    }
  ],
  "learned_by_pokemon": [
    {
      "name": "falinks",
      "url": "/api/v2/pokemon/870/"
    },
    {
      "name": "falinks-mega",
      "url": "/api/v2/pokemon/10303/"
    }
  ]
}
