=== PokeAPI/api-data/data/schema/v2/location/$id/index.json
{
  "$schema": "http://json-schema.org/schema#",
  "type": "object",
  "properties": {
    "id": {
      "type": "integer"
    },
    "name": {
      "type": "string"
    },
    "region": {
      "anyOf": [
        {
          "type": "null"
        },
        {
          "$ref": "/schema/v2/named_api_resource.json"
        }
      ]
    },
    "names": {
      "type": "array",
      "items": {
        "$ref": "/schema/v2/name.json"
      }
    },
    "game_indices": {
      "type": "array",
      "items": {
        "$ref": "/schema/v2/generation_game_index.json"
      }
    },
    "areas": {
      "type": "array",
      "items": {
        "$ref": "/schema/v2/named_api_resource.json"
      }
    }
  },
  "required": [
    "areas",
    "game_indices",
    "id",
    "name",
    "names",
    "region"
  ]
}

=== PokeAPI/api-data/data/api/v2/location/314/index.json
{
  "id": 314,
  "name": "pokepark-14",
  "region": null,
  "names": [
    {
      "name": "POKéPARK 14",
      "language": {
        "name": "fr",
        "url": "/api/v2/language/5/"
      }
    },
    {
      "name": "",
      "language": {
        "name": "de",
        "url": "/api/v2/language/6/"
      }
    },
    {
      "name": "POKéPARK 14",
      "language": {
        "name": "en",
        "url": "/api/v2/language/9/"
      }
    }
  ],
  "game_indices": [
    {
      "game_index": 3049,
      "generation": {
        "name": "generation-iv",
        "url": "/api/v2/generation/4/"
      }
    },
    {
      "game_index": 40102,
      "generation": {
        "name": "generation-v",
        "url": "/api/v2/generation/5/"
      }
    }
  ],
  "areas": []
}

=== PokeAPI/api-data/data/api/v2/location/184/index.json
{
  "id": 184,
  "name": "sinnoh-battle-tower",
  "region": {
    "name": "sinnoh",
    "url": "/api/v2/region/4/"
  },
  "names": [
    {
      "name": "Tour de Combat",
      "language": {
        "name": "fr",
        "url": "/api/v2/language/5/"
      }
    },
    {
      "name": "Duellturm",
      "language": {
        "name": "de",
        "url": "/api/v2/language/6/"
      }
    },
    {
      "name": "Battle Tower",
      "language": {
        "name": "en",
        "url": "/api/v2/language/9/"
      }
    }
  ],
  "game_indices": [
    {
      "game_index": 80,
      "generation": {
        "name": "generation-iv",
        "url": "/api/v2/generation/4/"
      }
    }
  ],
  "areas": []
}

=== PokeAPI/api-data/data/api/v2/location/672/index.json
{
  "id": 672,
  "name": "connecting-cave",
  "region": {
    "name": "kalos",
    "url": "/api/v2/region/6/"
  },
  "names": [
    {
      "name": "じつなぎのどうけつ",
      "language": {
        "name": "ja-hrkt",
        "url": "/api/v2/language/1/"
      }
    },
    {
      "name": "땅이음의 동굴",
      "language": {
        "name": "ko",
        "url": "/api/v2/language/3/"
      }
    },
    {
      "name": "Cave Connecterre",
      "language": {
        "name": "fr",
        "url": "/api/v2/language/5/"
      }
    },
    {
      "name": "Geolinkhöhle",
      "language": {
        "name": "de",
        "url": "/api/v2/language/6/"
      }
    },
    {
      "name": "Gruta Tierraunida",
      "language": {
        "name": "es",
        "url": "/api/v2/language/7/"
      }
    },
    {
      "name": "Grotta Trait d’Union",
      "language": {
        "name": "it",
        "url": "/api/v2/language/8/"
      }
    },
    {
      "name": "Connecting Cave",
      "language": {
        "name": "en",
        "url": "/api/v2/language/9/"
      }
    },
    {
      "name": "地つなぎの洞穴",
      "language": {
        "name": "ja",
        "url": "/api/v2/language/11/"
      }
    },
    {
      "name": "Gruta Tierraunida",
      "language": {
        "name": "es-419",
        "url": "/api/v2/language/14/"
      }
    }
  ],
  "game_indices": [
    {
      "game_index": 134,
      "generation": {
        "name": "generation-vi",
        "url": "/api/v2/generation/6/"
      }
    }
  ],
  "areas": [
    {
      "name": "connecting-cave-area",
      "url": "/api/v2/location-area/753/"
    }
  ]
}

=== PokeAPI/api-data/data/api/v2/location/1066/index.json
{
  "id": 1066,
  "name": "kitakami-wilds",
  "region": {
    "name": "paldea",
    "url": "/api/v2/region/10/"
  },
  "names": [
    {
      "name": "Terres Vierges de Septentria",
      "language": {
        "name": "fr",
        "url": "/api/v2/language/5/"
      }
    },
    {
      "name": "Wildnis von Kitakami",
      "language": {
        "name": "de",
        "url": "/api/v2/language/6/"
      }
    },
    {
      "name": "Kitakami Wilds",
      "language": {
        "name": "en",
        "url": "/api/v2/language/9/"
      }
    }
  ],
  "game_indices": [
    {
      "game_index": 164,
      "generation": {
        "name": "generation-ix",
        "url": "/api/v2/generation/9/"
      }
    }
  ],
  "areas": []
}

=== PokeAPI/api-data/data/api/v2/location/1012/index.json
{
  "id": 1012,
  "name": "sacred-plaza",
  "region": {
    "name": "hisui",
    "url": "/api/v2/region/9/"
  },
  "names": [
    {
      "name": "Parvis des Prières",
      "language": {
        "name": "fr",
        "url": "/api/v2/language/5/"
      }
    },
    {
      "name": "Platz der Huldigung",
      "language": {
        "name": "de",
        "url": "/api/v2/language/6/"
      }
    },
    {
      "name": "Sacred Plaza",
      "language": {
        "name": "en",
        "url": "/api/v2/language/9/"
      }
    }
  ],
  "game_indices": [],
  "areas": [
    {
      "name": "sacred-plaza-area",
      "url": "/api/v2/location-area/1006/"
    }
  ]
}
