=== PokeAPI/api-data/data/schema/v2/location/$id/index.json
{
  "$schema": "http://json-schema.org/schema#",
  "type": "object",
  "properties": {
    "id": {
      "type": "integer"
    },
    "name": {
      "type": "string"
    },
    "region": {
      "anyOf": [
        {
          "type": "null"
        },
        {
          "$ref": "/schema/v2/named_api_resource.json"
        }
      ]
    },
    "names": {
      "type": "array",
      "items": {
        "$ref": "/schema/v2/name.json"
      }
    },
    "game_indices": {
      "type": "array",
      "items": {
        "$ref": "/schema/v2/generation_game_index.json"
      }
    },
    "areas": {
      "type": "array",
      "items": {
        "$ref": "/schema/v2/named_api_resource.json"
      }
    }
  },
  "required": [
    "areas",
    "game_indices",
    "id",
    "name",
    "names",
    "region"
  ]
}

=== PokeAPI/api-data/data/api/v2/location/593/index.json
{
  "id": 593,
  "name": "santalune-forest",
  "region": {
    "name": "kalos",
    "url": "/api/v2/region/6/"
  },
  "names": [
    {
      "name": "ハクダンのもり",
      "language": {
        "name": "ja-hrkt",
        "url": "/api/v2/language/1/"
      }
    },
    {
      "name": "백단숲",
      "language": {
        "name": "ko",
        "url": "/api/v2/language/3/"
      }
    },
    {
      "name": "Forêt de Neuvartault",
      "language": {
        "name": "fr",
        "url": "/api/v2/language/5/"
      }
    },
    {
      "name": "Nouvaria-Wald",
      "language": {
        "name": "de",
        "url": "/api/v2/language/6/"
      }
    },
    {
      "name": "Bosque de Novarte",
      "language": {
        "name": "es",
        "url": "/api/v2/language/7/"
      }
    },
    {
      "name": "Bosco Novartopoli",
      "language": {
        "name": "it",
        "url": "/api/v2/language/8/"
      }
    },
    {
      "name": "Santalune Forest",
      "language": {
        "name": "en",
        "url": "/api/v2/language/9/"
      }
    },
    {
      "name": "ハクダンの森",
      "language": {
        "name": "ja",
        "url": "/api/v2/language/11/"
      }
    },
    {
      "name": "Bosque de Novarte",
      "language": {
        "name": "es-419",
        "url": "/api/v2/language/14/"
      }
    }
  ],
  "game_indices": [
    {
      "game_index": 14,
      "generation": {
        "name": "generation-vi",
        "url": "/api/v2/generation/6/"
      }
    }
  ],
  "areas": [
    {
      "name": "santalune-forest-area",
      "url": "/api/v2/location-area/734/"
    }
  ]
}

=== PokeAPI/api-data/data/api/v2/location/1029/index.json
{
  "id": 1029,
  "name": "tidewater-dam",
  "region": {
    "name": "hisui",
    "url": "/api/v2/region/9/"
  },
  "names": [
    {
      "name": "Digue de l'Estuaire",
      "language": {
        "name": "fr",
        "url": "/api/v2/language/5/"
      }
    },
    {
      "name": "Mündungsdamm",
      "language": {
        "name": "de",
        "url": "/api/v2/language/6/"
      }
    },
    {
      "name": "Tidewater Dam",
      "language": {
        "name": "en",
        "url": "/api/v2/language/9/"
      }
    }
  ],
  "game_indices": [],
  "areas": [
    {
      "name": "tidewater-dam-area",
      "url": "/api/v2/location-area/1023/"
    }
  ]
}

=== PokeAPI/api-data/api/v2/location/656/index.json
{
    "areas": [],
    "game_indices": [
        {
            "game_index": 103,
            "generation": {
                "name": "generation-vi",
                "url": "http://localhost/api/v2/generation/6/"
            }
        }
    ],
    "id": 656,
    "name": "detourner-way",
    "names": [
        {
            "language": {
                "name": "ja",
                "url": "http://localhost/api/v2/language/11/"
            },
            "name": "\u30c7\u30c8\u30eb\u30cd\u901a\u308a"
        },
        {
            "language": {
                "name": "en",
                "url": "http://localhost/api/v2/language/9/"
            },
            "name": "D\u00e9tourner Way"
        },
        {
            "language": {
                "name": "it",
                "url": "http://localhost/api/v2/language/8/"
            },
            "name": "Via Detour"
        },
        {
            "language": {
                "name": "es",
                "url": "http://localhost/api/v2/language/7/"
            },
            "name": "V\u00eda Desv\u00edo"
        },
        {
            "language": {
                "name": "de",
                "url": "http://localhost/api/v2/language/6/"
            },
            "name": "D\u00e9tourn\u00e9-Weg"
        },
        {
            "language": {
                "name": "fr",
                "url": "http://localhost/api/v2/language/5/"
            },
            "name": "Chemin D\u00e9tour"
        },
        {
            "language": {
                "name": "ko",
                "url": "http://localhost/api/v2/language/3/"
            },
            "name": "\ub370\ub69c\ub974\ub124 \ub3c4\ub85c"
        },
        {
            "language": {
                "name": "ja-Hrkt",
                "url": "http://localhost/api/v2/language/1/"
            },
            "name": "\u30c7\u30c8\u30eb\u30cd\u3069\u304a\u308a"
        }
    ],
    "region": {
        "name": "kalos",
        "url": "http://localhost/api/v2/region/6/"
    }
}

=== PokeAPI/api-data/api/v2/location/56/index.json
{
    "areas": [
        {
            "name": "sinnoh-route-228-area",
            "url": "http://localhost/api/v2/location-area/175/"
        }
    ],
    "game_indices": [
        {
            "game_index": 43,
            "generation": {
                "name": "generation-iv",
                "url": "http://localhost/api/v2/generation/4/"
            }
        }
    ],
    "id": 56,
    "name": "sinnoh-route-228",
    "names": [
        {
            "language": {
                "name": "en",
                "url": "http://localhost/api/v2/language/9/"
            },
            "name": "Route 228"
        },
        {
            "language": {
                "name": "fr",
                "url": "http://localhost/api/v2/language/5/"
            },
            "name": "Route 228"
        }
    ],
    "region": {
        "name": "sinnoh",
        "url": "http://localhost/api/v2/region/4/"
    }
}

=== PokeAPI/api-data/data/api/v2/location/47/index.json
{
  "id": 47,
  "name": "sinnoh-route-216",
  "region": {
    "name": "sinnoh",
    "url": "/api/v2/region/4/"
  },
  "names": [
    {
      "name": "Route 216",
      "language": {
        "name": "fr",
        "url": "/api/v2/language/5/"
      }
    },
    {
      "name": "Route 216",
      "language": {
        "name": "de",
        "url": "/api/v2/language/6/"
      }
    },
    {
      "name": "Route 216",
      "language": {
        "name": "en",
        "url": "/api/v2/language/9/"
      }
    }
  ],
  "game_indices": [
    {
      "game_index": 31,
      "generation": {
        "name": "generation-iv",
        "url": "/api/v2/generation/4/"
      }
    }
  ],
  "areas": [
    {
      "name": "sinnoh-route-216-area",
      "url": "/api/v2/location-area/166/"
    }
  ]
}

=== PokeAPI/api-data/data/api/v2/location/627/index.json
{
  "id": 627,
  "name": "fourrage-road",
  "region": {
    "name": "kalos",
    "url": "/api/v2/region/6/"
  },
  "names": [
    {
      "name": "フラージュどおり",
      "language": {
        "name": "ja-hrkt",
        "url": "/api/v2/language/1/"
      }
    },
    {
      "name": "프라주 도로",
      "language": {
        "name": "ko",
        "url": "/api/v2/language/3/"
      }
    },
    {
      "name": "Chemin Fourrage",
      "language": {
        "name": "fr",
        "url": "/api/v2/language/5/"
      }
    },
    {
      "name": "Fourrage-Weg",
      "language": {
        "name": "de",
        "url": "/api/v2/language/6/"
      }
    },
    {
      "name": "Vereda del Heno",
      "language": {
        "name": "es",
        "url": "/api/v2/language/7/"
      }
    },
    {
      "name": "Via dei Pascoli",
      "language": {
        "name": "it",
        "url": "/api/v2/language/8/"
      }
    },
    {
      "name": "Fourrage Road",
      "language": {
        "name": "en",
        "url": "/api/v2/language/9/"
      }
    },
    {
      "name": "フラージュ通り",
      "language": {
        "name": "ja",
        "url": "/api/v2/language/11/"
      }
    },
    {
      "name": "Vereda del Heno",
      "language": {
        "name": "es-419",
        "url": "/api/v2/language/14/"
      }
    }
  ],
  "game_indices": [
    {
      "game_index": 63,
      "generation": {
        "name": "generation-vi",
        "url": "/api/v2/generation/6/"
      }
    }
  ],
  "areas": []
}

=== PokeAPI/api-data/data/api/v2/location/1121/index.json
{
  "id": 1121,
  "name": "kalos-berry-fields",
  "region": {
    "name": "kalos",
    "url": "/api/v2/region/6/"
  },
  "names": [
    {
      "name": "Kalos Berry Fields",
      "language": {
        "name": "de",
        "url": "/api/v2/language/6/"
      }
    }
  ],
  "game_indices": [],
  "areas": [
    {
      "name": "kalos-berry-fields-area",
      "url": "/api/v2/location-area/1483/"
    }
  ]
}

=== PokeAPI/api-data/data/api/v2/location/714/index.json
{
  "id": 714,
  "name": "kalae-bay",
  "region": {
    "name": "alola",
    "url": "/api/v2/region/7/"
  },
  "names": [
    {
      "name": "カーラエわん",
      "language": {
        "name": "ja-hrkt",
        "url": "/api/v2/language/1/"
      }
    },
    {
      "name": "칼라에만",
      "language": {
        "name": "ko",
        "url": "/api/v2/language/3/"
      }
    },
    {
      "name": "卡拉蔚灣",
      "language": {
        "name": "zh-hant",
        "url": "/api/v2/language/4/"
      }
    },
    {
      "name": "Baie de Kala’e",
      "language": {
        "name": "fr",
        "url": "/api/v2/language/5/"
      }
    },
    {
      "name": "Kala’e-Bucht",
      "language": {
        "name": "de",
        "url": "/api/v2/language/6/"
      }
    },
    {
      "name": "Bahía Kalae",
      "language": {
        "name": "es",
        "url": "/api/v2/language/7/"
      }
    },
    {
      "name": "Baia Kala’e",
      "language": {
        "name": "it",
        "url": "/api/v2/language/8/"
      }
    },
    {
      "name": "Kala’e Bay",
      "language": {
        "name": "en",
        "url": "/api/v2/language/9/"
      }
    },
    {
      "name": "カーラエ湾",
      "language": {
        "name": "ja",
        "url": "/api/v2/language/11/"
      }
    },
    {
      "name": "卡拉蔚湾",
      "language": {
        "name": "zh-hans",
        "url": "/api/v2/language/12/"
      }
    },
    {
      "name": "Bahía Kalae",
      "language": {
        "name": "es-419",
        "url": "/api/v2/language/14/"
      }
    }
  ],
  "game_indices": [
    {
      "game_index": 14,
      "generation": {
        "name": "generation-vii",
        "url": "/api/v2/generation/7/"
      }
    }
  ],
  "areas": [
    {
      "name": "kalae-bay-area",
      "url": "/api/v2/location-area/1090/"
    }
  ]
}
