=== PokeAPI/api-data/data/schema/v2/location/$id/index.json
{
  "$schema": "http://json-schema.org/schema#",
  "type": "object",
  "properties": {
    "id": {
      "type": "integer"
    },
    "name": {
      "type": "string"
    },
    "region": {
      "anyOf": [
        {
          "type": "null"
        },
        {
          "$ref": "/schema/v2/named_api_resource.json"
        }
      ]
    },
    "names": {
      "type": "array",
      "items": {
        "$ref": "/schema/v2/name.json"
      }
    },
    "game_indices": {
      "type": "array",
      "items": {
        "$ref": "/schema/v2/generation_game_index.json"
      }
    },
    "areas": {
      "type": "array",
      "items": {
        "$ref": "/schema/v2/named_api_resource.json"
      }
    }
  },
  "required": [
    "areas",
    "game_indices",
    "id",
    "name",
    "names",
    "region"
  ]
}

=== PokeAPI/api-data/data/api/v2/location/89/index.json
{
  "id": 89,
  "name": "kanto-route-10",
  "region": {
    "name": "kanto",
    "url": "/api/v2/region/1/"
  },
  "names": [
    {
      "name": "Route 10",
      "language": {
        "name": "fr",
        "url": "/api/v2/language/5/"
      }
    },
    {
      "name": "Route 10",
      "language": {
        "name": "de",
        "url": "/api/v2/language/6/"
      }
    },
    {
      "name": "Route 10",
      "language": {
        "name": "en",
        "url": "/api/v2/language/9/"
      }
    }
  ],
  "game_indices": [
    {
      "game_index": 21,
      "generation": {
        "name": "generation-i",
        "url": "/api/v2/generation/1/"
      }
    },
    {
      "game_index": 67,
      "generation": {
        "name": "generation-ii",
        "url": "/api/v2/generation/2/"
      }
    },
    {
      "game_index": 110,
      "generation": {
        "name": "generation-iii",
        "url": "/api/v2/generation/3/"
      }
    },
    {
      "game_index": 158,
      "generation": {
        "name": "generation-iv",
        "url": "/api/v2/generation/4/"
      }
    }
  ],
  "areas": [
    {
      "name": "kanto-route-10-area",
      "url": "/api/v2/location-area/304/"
    }
  ]
}

=== PokeAPI/api-data/data/api/v2/location/613/index.json
{
  "id": 613,
  "name": "muraille-coast",
  "region": {
    "name": "kalos",
    "url": "/api/v2/region/6/"
  },
  "names": [
    {
      "name": "ミュライユかいがん",
      "language": {
        "name": "ja-hrkt",
        "url": "/api/v2/language/1/"
      }
    },
    {
      "name": "미라유 해안",
      "language": {
        "name": "ko",
        "url": "/api/v2/language/3/"
      }
    },
    {
      "name": "Falaise Muraille",
      "language": {
        "name": "fr",
        "url": "/api/v2/language/5/"
      }
    },
    {
      "name": "Muraille-Küstenpfad",
      "language": {
        "name": "de",
        "url": "/api/v2/language/6/"
      }
    },
    {
      "name": "Muralla Costera",
      "language": {
        "name": "es",
        "url": "/api/v2/language/7/"
      }
    },
    {
      "name": "Muraglia Costiera",
      "language": {
        "name": "it",
        "url": "/api/v2/language/8/"
      }
    },
    {
      "name": "Muraille Coast",
      "language": {
        "name": "en",
        "url": "/api/v2/language/9/"
      }
    },
    {
      "name": "ミュライユ海岸",
      "language": {
        "name": "ja",
        "url": "/api/v2/language/11/"
      }
    },
    {
      "name": "Muralla Costera",
      "language": {
        "name": "es-419",
        "url": "/api/v2/language/14/"
      }
    }
  ],
  "game_indices": [
    {
      "game_index": 43,
      "generation": {
        "name": "generation-vi",
        "url": "/api/v2/generation/6/"
      }
    }
  ],
  "areas": []
}

=== PokeAPI/api-data/data/api/v2/location/469/index.json
{
  "id": 469,
  "name": "hoenn-route-121",
  "region": {
    "name": "hoenn",
    "url": "/api/v2/region/3/"
  },
  "names": [
    {
      "name": "１２１ばんどうろ",
      "language": {
        "name": "ja-hrkt",
        "url": "/api/v2/language/1/"
      }
    },
    {
      "name": "121번도로",
      "language": {
        "name": "ko",
        "url": "/api/v2/language/3/"
      }
    },
    {
      "name": "Route 121",
      "language": {
        "name": "fr",
        "url": "/api/v2/language/5/"
      }
    },
    {
      "name": "Route 121",
      "language": {
        "name": "de",
        "url": "/api/v2/language/6/"
      }
    },
    {
      "name": "Ruta 121",
      "language": {
        "name": "es",
        "url": "/api/v2/language/7/"
      }
    },
    {
      "name": "Percorso 121",
      "language": {
        "name": "it",
        "url": "/api/v2/language/8/"
      }
    },
    {
      "name": "Route 121",
      "language": {
        "name": "en",
        "url": "/api/v2/language/9/"
      }
    },
    {
      "name": "１２１番道路",
      "language": {
        "name": "ja",
        "url": "/api/v2/language/11/"
      }
    },
    {
      "name": "Ruta 121",
      "language": {
        "name": "es-419",
        "url": "/api/v2/language/14/"
      }
    }
  ],
  "game_indices": [
    {
      "game_index": 36,
      "generation": {
        "name": "generation-iii",
        "url": "/api/v2/generation/3/"
      }
    },
    {
      "game_index": 244,
      "generation": {
        "name": "generation-vi",
        "url": "/api/v2/generation/6/"
      }
    }
  ],
  "areas": [
    {
      "name": "hoenn-route-121-area",
      "url": "/api/v2/location-area/413/"
    }
  ]
}

=== PokeAPI/api-data/data/api/v2/location/517/index.json
{
  "id": 517,
  "name": "ruin-valley",
  "region": {
    "name": "kanto",
    "url": "/api/v2/region/1/"
  },
  "names": [
    {
      "name": "Vallée Ruine",
      "language": {
        "name": "fr",
        "url": "/api/v2/language/5/"
      }
    },
    {
      "name": "Ruinental",
      "language": {
        "name": "de",
        "url": "/api/v2/language/6/"
      }
    },
    {
      "name": "Ruin Valley",
      "language": {
        "name": "en",
        "url": "/api/v2/language/9/"
      }
    }
  ],
  "game_indices": [
    {
      "game_index": 166,
      "generation": {
        "name": "generation-iii",
        "url": "/api/v2/generation/3/"
      }
    }
  ],
  "areas": [
    {
      "name": "ruin-valley-area",
      "url": "/api/v2/location-area/524/"
    }
  ]
}

=== PokeAPI/api-data/data/api/v2/location/954/index.json
{
  "id": 954,
  "name": "arenas-approach",
  "region": {
    "name": "hisui",
    "url": "/api/v2/region/9/"
  },
  "names": [
    {
      "name": "Sentier de l'Arène",
      "language": {
        "name": "fr",
        "url": "/api/v2/language/5/"
      }
    },
    {
      "name": "Pfad zum Kampffeld",
      "language": {
        "name": "de",
        "url": "/api/v2/language/6/"
      }
    },
    {
      "name": "Arena's Approach",
      "language": {
        "name": "en",
        "url": "/api/v2/language/9/"
      }
    }
  ],
  "game_indices": [],
  "areas": [
    {
      "name": "arenas-approach-area",
      "url": "/api/v2/location-area/948/"
    }
  ]
}

=== PokeAPI/api-data/api/v2/location/572/index.json
{
    "areas": [],
    "game_indices": [],
    "id": 572,
    "name": "mauville-city",
    "names": [
        {
            "language": {
                "name": "en",
                "url": "http://localhost/api/v2/language/9/"
            },
            "name": "Mauville City"
        },
        {
            "language": {
                "name": "fr",
                "url": "http://localhost/api/v2/language/5/"
            },
            "name": "Lavandia"
        }
    ],
    "region": {
        "name": "hoenn",
        "url": "http://localhost/api/v2/region/3/"
    }
}

=== PokeAPI/api-data/data/api/v2/location/818/index.json
{
  "id": 818,
  "name": "cortondo",
  "region": {
    "name": "paldea",
    "url": "/api/v2/region/10/"
  },
  "names": [
    {
      "name": "Sevaro",
      "language": {
        "name": "fr",
        "url": "/api/v2/language/5/"
      }
    },
    {
      "name": "Moldrid",
      "language": {
        "name": "de",
        "url": "/api/v2/language/6/"
      }
    },
    {
      "name": "Cortondo",
      "language": {
        "name": "en",
        "url": "/api/v2/language/9/"
      }
    }
  ],
  "game_indices": [
    {
      "game_index": 84,
      "generation": {
        "name": "generation-ix",
        "url": "/api/v2/generation/9/"
      }
    }
  ],
  "areas": []
}

=== PokeAPI/api-data/data/api/v2/location/253/index.json
{
  "id": 253,
  "name": "day-care-couple",
  "region": null,
  "names": [
    {
      "name": "Couple Pension",
      "language": {
        "name": "fr",
        "url": "/api/v2/language/5/"
      }
    },
    {
      "name": "Pensions-Paar",
      "language": {
        "name": "de",
        "url": "/api/v2/language/6/"
      }
    },
    {
      "name": "Day-Care Couple",
      "language": {
        "name": "en",
        "url": "/api/v2/language/9/"
      }
    }
  ],
  "game_indices": [
    {
      "game_index": 2000,
      "generation": {
        "name": "generation-iv",
        "url": "/api/v2/generation/4/"
      }
    },
    {
      "game_index": 60002,
      "generation": {
        "name": "generation-v",
        "url": "/api/v2/generation/5/"
      }
    },
    {
      "game_index": 60002,
      "generation": {
        "name": "generation-vi",
        "url": "/api/v2/generation/6/"
      }
    }
  ],
  "areas": []
}
