=== PokeAPI/api-data/data/schema/v2/item/$id/index.json
{
  "$schema": "http://json-schema.org/schema#",
  "type": "object",
  "properties": {
    "id": {
      "type": "integer"
    },
    "name": {
      "type": "string"
    },
    "fling_power": {
      "type": [
        "integer",
        "null"
      ]
    },
    "fling_effect": {
      "anyOf": [
        {
          "type": "null"
        },
        {
          "$ref": "/schema/v2/named_api_resource.json"
        }
      ]
    },
    "attributes": {
      "type": "array",
      "items": {
        "$ref": "/schema/v2/named_api_resource.json"
      }
    },
    "category": {
      "$ref": "/schema/v2/named_api_resource.json"
    },
    "effect_entries": {
      "type": "array",
      "items": {
        "$ref": "/schema/v2/verbose_effect.json"
      }
    },
    "flavor_text_entries": {
      "type": "array",
      "items": {
        "$ref": "/schema/v2/version_group_flavor_text.json"
      }
    },
    "game_indices": {
      "type": "array",
      "items": {
        "$ref": "/schema/v2/generation_game_index.json"
      }
    },
    "prices": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "purchase_price": {
            "type": [
              "integer",
              "null"
            ]
          },
          "sell_price": {
            "type": [
              "integer",
              "null"
            ]
          },
          "currency": {
            "$ref": "/schema/v2/named_api_resource.json"
          },
          "version_group": {
            "$ref": "/schema/v2/named_api_resource.json"
          }
        },
        "required": [
          "currency",
          "purchase_price",
          "sell_price",
          "version_group"
        ]
      }
    },
    "names": {
      "type": "array",
      "items": {
        "$ref": "/schema/v2/name.json"
      }
    },
    "held_by_pokemon": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "pokemon": {
            "$ref": "/schema/v2/named_api_resource.json"
          },
          "version_details": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "rarity": {
                  "type": "integer"
                },
                "version": {
                  "$ref": "/schema/v2/named_api_resource.json"
                }
              },
              "required": [
                "rarity",
                "version"
              ]
            }
          }
        },
        "required": [
          "pokemon",
          "version_details"
        ]
      }
    },
    "sprites": {
      "type": "object",
      "properties": {
        "default": {
          "type": "string"
        }
      },
      "required": [
        "default"
      ]
    },
    "baby_trigger_for": {
      "anyOf": [
        {
          "type": "null"
        },
        {
          "$ref": "/schema/v2/api_resource.json"
        }
      ]
    },
    "machines": {
      "type": "array",
      "items": {
        "$ref": "/schema/v2/machine_version_detail.json"
      }
    }
  },
  "required": [
    "attributes",
    "baby_trigger_for",
    "category",
    "effect_entries",
    "flavor_text_entries",
    "fling_effect",
    "fling_power",
    "game_indices",
    "held_by_pokemon",
    "id",
    "machines",
    "name",
    "names",
    "prices",
    "sprites"
  ]
}

=== PokeAPI/api-data/data/api/v2/item/1467/index.json
{
  "id": 1467,
  "name": "dynamax-crystal-cet681",
  "fling_power": null,
  "fling_effect": null,
  "attributes": [],
  "category": {
    "name": "dynamax-crystals",
    "url": "/api/v2/item-category/49/"
  },
  "effect_entries": [],
  "flavor_text_entries": [
    {
      "text": "つかった　ひに　ワイルドエリアの\nみはりとうのダイすあな　から\n[VAR (0000)]が　あらわれる。",
      "version_group": {
        "name": "sword-shield",
        "url": "/api/v2/version-group/20/"
      },
      "language": {
        "name": "ja-hrkt",
        "url": "/api/v2/language/1/"
      }
    },
    {
      "text": "사용한 당일에만 와일드에리어에 있는\n감시탑의 다이맥스굴에서\n[VAR (0000)][VAR (0003)] 나타난다.",
      "version_group": {
        "name": "sword-shield",
        "url": "/api/v2/version-group/20/"
      },
      "language": {
        "name": "ko",
        "url": "/api/v2/language/3/"
      }
    },
    {
      "text": "使用後的當天，\n[VAR (0000)]會出現在\n曠野地帶的瞭望塔巨巢。",
      "version_group": {
        "name": "sword-shield",
        "url": "/api/v2/version-group/20/"
      },
      "language": {
        "name": "zh-hant",
        "url": "/api/v2/language/4/"
      }
    },
    {
      "text": "Un objet faisant apparaître un [VAR (0000)]\ndans l’antre géant de la Tour en ruines\ndes Terres Sauvages jusqu’à la fin de la journée.",
      "version_group": {
        "name": "sword-shield",
        "url": "/api/v2/version-group/20/"
      },
      "language": {
        "name": "fr",
        "url": "/api/v2/language/5/"
      }
    },
    {
      "text": "Dieses Item bewirkt, dass im Wachturm-Nest in der\nNaturzone ein [VAR (0000)] bis zum Ende des Tages\nerscheint, an dem das Item eingesetzt wurde.",
      "version_group": {
        "name": "sword-shield",
        "url": "/api/v2/version-group/20/"
      },
      "language": {
        "name": "de",
        "url": "/api/v2/language/6/"
      }
    },
    {
      "text": "Posibilita la aparición de [VAR (0000)] en el nido\nDinamax de la Atalaya del Área Silvestre hasta finalizar\nel día en que se ha usado.",
      "version_group": {
        "name": "sword-shield",
        "url": "/api/v2/version-group/20/"
      },
      "language": {
        "name": "es",
        "url": "/api/v2/language/7/"
      }
    },
    {
      "text": "Strumento che fa apparire [VAR (0000)] nella\ndynatana della Torre Diroccata, nelle Terre Selvagge,\nfino alla fine del giorno in cui viene usato.",
      "version_group": {
        "name": "sword-shield",
        "url": "/api/v2/version-group/20/"
      },
      "language": {
        "name": "it",
        "url": "/api/v2/language/8/"
      }
    },
    {
      "text": "An item that causes [VAR (0000)] to appear from\nthe Watchtower Lair in the Wild Area until the end of\nthe day.",
      "version_group": {
        "name": "sword-shield",
        "url": "/api/v2/version-group/20/"
      },
      "language": {
        "name": "en",
        "url": "/api/v2/language/9/"
      }
    },
    {
      "text": "使った　日に　ワイルドエリアの\n見張り塔のダイ巣穴　から\n[VAR (0000)]が　現れる。",
      "version_group": {
        "name": "sword-shield",
        "url": "/api/v2/version-group/20/"
      },
      "language": {
        "name": "ja",
        "url": "/api/v2/language/11/"
      }
    },
    {
      "text": "使用后的当天，\n旷野地带的瞭望塔巨巢中\n会出现[VAR (0000)]。",
      "version_group": {
        "name": "sword-shield",
        "url": "/api/v2/version-group/20/"
      },
      "language": {
        "name": "zh-hans",
        "url": "/api/v2/language/12/"
      }
    },
    {
      "text": "Posibilita la aparición de [VAR (0000)] en el nido\nDinamax de la Atalaya del Área Silvestre hasta finalizar\nel día en que se ha usado.",
      "version_group": {
        "name": "sword-shield",
        "url": "/api/v2/version-group/20/"
      },
      "language": {
        "name": "es-419",
        "url": "/api/v2/language/14/"
      }
    }
  ],
  "game_indices": [
    {
      "game_index": 1416,
      "generation": {
        "name": "generation-viii",
        "url": "/api/v2/generation/8/"
      }
    },
    {
      "game_index": 1416,
      "generation": {
        "name": "generation-ix",
        "url": "/api/v2/generation/9/"
      }
    }
  ],
  "prices": [],
  "names": [
    {
      "name": "★Cet681",
      "language": {
        "name": "ja-hrkt",
        "url": "/api/v2/language/1/"
      }
    },
    {
      "name": "★Cet681",
      "language": {
        "name": "ko",
        "url": "/api/v2/language/3/"
      }
    },
    {
      "name": "★Cet681",
      "language": {
        "name": "zh-hant",
        "url": "/api/v2/language/4/"
      }
    },
    {
      "name": "★Cet681",
      "language": {
        "name": "fr",
        "url": "/api/v2/language/5/"
      }
    },
    {
      "name": "★Cet681",
      "language": {
        "name": "de",
        "url": "/api/v2/language/6/"
      }
    },
    {
      "name": "★Cet681",
      "language": {
        "name": "es",
        "url": "/api/v2/language/7/"
      }
    },
    {
      "name": "★Cet681",
      "language": {
        "name": "it",
        "url": "/api/v2/language/8/"
      }
    },
    {
      "name": "★Cet681",
      "language": {
        "name": "en",
        "url": "/api/v2/language/9/"
      }
    },
    {
      "name": "★Cet681",
      "language": {
        "name": "ja",
        "url": "/api/v2/language/11/"
      }
    },
    {
      "name": "★Cet681",
      "language": {
        "name": "zh-hans",
        "url": "/api/v2/language/12/"
      }
    },
    {
      "name": "★Cet681",
      "language": {
        "name": "es-419",
        "url": "/api/v2/language/14/"
      }
    }
  ],
  "held_by_pokemon": [],
  "sprites": {
    "default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/dynamax-crystal-cet681.png"
  },
  "baby_trigger_for": null,
  "machines": []
}

=== PokeAPI/api-data/data/api/v2/item/2065/index.json
{
  "id": 2065,
  "name": "plaid-tablecloth-y",
  "fling_power": null,
  "fling_effect": null,
  "attributes": [],
  "category": {
    "name": "picnic",
    "url": "/api/v2/item-category/55/"
  },
  "effect_entries": [],
  "flavor_text_entries": [],
  "game_indices": [
    {
      "game_index": 2366,
      "generation": {
        "name": "generation-ix",
        "url": "/api/v2/generation/9/"
      }
    }
  ],
  "prices": [],
  "names": [
    {
      "name": "きいろチェッククロス",
      "language": {
        "name": "ja-hrkt",
        "url": "/api/v2/language/1/"
      }
    },
    {
      "name": "옐로 체크 테이블보",
      "language": {
        "name": "ko",
        "url": "/api/v2/language/3/"
      }
    },
    {
      "name": "黃色格子桌巾",
      "language": {
        "name": "zh-hant",
        "url": "/api/v2/language/4/"
      }
    },
    {
      "name": "Nappe Tartan Jaune",
      "language": {
        "name": "fr",
        "url": "/api/v2/language/5/"
      }
    },
    {
      "name": "Gelbkaro-Tischtuch",
      "language": {
        "name": "de",
        "url": "/api/v2/language/6/"
      }
    },
    {
      "name": "Mantel Cuadros Ámbar",
      "language": {
        "name": "es",
        "url": "/api/v2/language/7/"
      }
    },
    {
      "name": "Tovaglia a quadri gialla",
      "language": {
        "name": "it",
        "url": "/api/v2/language/8/"
      }
    },
    {
      "name": "Plaid Tablecloth (Y)",
      "language": {
        "name": "en",
        "url": "/api/v2/language/9/"
      }
    },
    {
      "name": "きいろチェッククロス",
      "language": {
        "name": "ja",
        "url": "/api/v2/language/11/"
      }
    },
    {
      "name": "黄色格子桌巾",
      "language": {
        "name": "zh-hans",
        "url": "/api/v2/language/12/"
      }
    }
  ],
  "held_by_pokemon": [],
  "sprites": {
    "default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/plaid-tablecloth-y.png"
  },
  "baby_trigger_for": null,
  "machines": []
}

=== PokeAPI/api-data/data/api/v2/item/2030/index.json
{
  "id": 2030,
  "name": "spooky-tablecloth",
  "fling_power": null,
  "fling_effect": null,
  "attributes": [],
  "category": {
    "name": "picnic",
    "url": "/api/v2/item-category/55/"
  },
  "effect_entries": [],
  "flavor_text_entries": [],
  "game_indices": [
    {
      "game_index": 2327,
      "generation": {
        "name": "generation-ix",
        "url": "/api/v2/generation/9/"
      }
    }
  ],
  "prices": [],
  "names": [
    {
      "name": "うらめしクロス",
      "language": {
        "name": "ja-hrkt",
        "url": "/api/v2/language/1/"
      }
    },
    {
      "name": "원망 테이블보",
      "language": {
        "name": "ko",
        "url": "/api/v2/language/3/"
      }
    },
    {
      "name": "鬼祟桌巾",
      "language": {
        "name": "zh-hant",
        "url": "/api/v2/language/4/"
      }
    },
    {
      "name": "Nappe Hantée",
      "language": {
        "name": "fr",
        "url": "/api/v2/language/5/"
      }
    },
    {
      "name": "Groll-Tischtuch",
      "language": {
        "name": "de",
        "url": "/api/v2/language/6/"
      }
    },
    {
      "name": "Mantel Espectral",
      "language": {
        "name": "es",
        "url": "/api/v2/language/7/"
      }
    },
    {
      "name": "Tovaglia dispetto",
      "language": {
        "name": "it",
        "url": "/api/v2/language/8/"
      }
    },
    {
      "name": "Spooky Tablecloth",
      "language": {
        "name": "en",
        "url": "/api/v2/language/9/"
      }
    },
    {
      "name": "うらめしクロス",
      "language": {
        "name": "ja",
        "url": "/api/v2/language/11/"
      }
    },
    {
      "name": "鬼祟桌巾",
      "language": {
        "name": "zh-hans",
        "url": "/api/v2/language/12/"
      }
    }
  ],
  "held_by_pokemon": [],
  "sprites": {
    "default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/spooky-tablecloth.png"
  },
  "baby_trigger_for": null,
  "machines": []
}

=== PokeAPI/api-data/data/api/v2/item/1968/index.json
{
    "attributes": [],
    "baby_trigger_for": null,
    "category": {
        "name": "all-machines",
        "url": "/api/v2/item-category/37/"
    },
    "effect_entries": [],
    "flavor_text_entries": [],
    "fling_effect": null,
    "fling_power": null,
    "game_indices": [
        {
            "game_index": 2185,
            "generation": {
                "name": "generation-ix",
                "url": "/api/v2/generation/9/"
            }
        }
    ],
    "held_by_pokemon": [],
    "id": 1968,
    "machines": [
        {
            "machine": {
                "url": "/api/v2/machine/1940/"
            },
            "version_group": {
                "name": "scarlet-violet",
                "url": "/api/v2/version-group/25/"
            }
        },
        {
            "machine": {
                "url": "/api/v2/machine/2133/"
            },
            "version_group": {
                "name": "the-indigo-disk",
                "url": "/api/v2/version-group/27/"
            }
        },
        {
            "machine": {
                "url": "/api/v2/machine/2337/"
            },
            "version_group": {
                "name": "mega-dimension",
                "url": "/api/v2/version-group/31/"
            }
        }
    ],
    "name": "tm125",
    "names": [
        {
            "language": {
                "name": "ja-hrkt",
                "url": "/api/v2/language/1/"
            },
            "name": "\u308f\u3056\u30de\u30b7\u30f3\uff11\uff12\uff15"
        },
        {
            "language": {
                "name": "zh-hant",
                "url": "/api/v2/language/4/"
            },
            "name": "\u62db\u5f0f\u5b66\u4e60\u5668\uff11\uff12\uff15"
        },
        {
            "language": {
                "name": "fr",
                "url": "/api/v2/language/5/"
            },
            "name": "CT125"
        },
        {
            "language": {
                "name": "en",
                "url": "/api/v2/language/9/"
            },
            "name": "TM125"
        },
        {
            "language": {
                "name": "ja",
                "url": "/api/v2/language/11/"
            },
            "name": "\u308f\u3056\u30de\u30b7\u30f3\uff11\uff12\uff15"
        }
    ],
    "prices": [],
    "sprites": {
        "default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tm-normal.png"
    }
}

=== PokeAPI/api-data/data/api/v2/item/2056/index.json
{
  "id": 2056,
  "name": "fire-pattern-cup",
  "fling_power": null,
  "fling_effect": null,
  "attributes": [],
  "category": {
    "name": "picnic",
    "url": "/api/v2/item-category/55/"
  },
  "effect_entries": [],
  "flavor_text_entries": [],
  "game_indices": [
    {
      "game_index": 2357,
      "generation": {
        "name": "generation-ix",
        "url": "/api/v2/generation/9/"
      }
    }
  ],
  "prices": [],
  "names": [
    {
      "name": "ファイヤーカップ",
      "language": {
        "name": "ja-hrkt",
        "url": "/api/v2/language/1/"
      }
    },
    {
      "name": "파이어 컵",
      "language": {
        "name": "ko",
        "url": "/api/v2/language/3/"
      }
    },
    {
      "name": "火焰水杯",
      "language": {
        "name": "zh-hant",
        "url": "/api/v2/language/4/"
      }
    },
    {
      "name": "Tasse à Flammes",
      "language": {
        "name": "fr",
        "url": "/api/v2/language/5/"
      }
    },
    {
      "name": "Flammen-Tasse",
      "language": {
        "name": "de",
        "url": "/api/v2/language/6/"
      }
    },
    {
      "name": "Taza Llamas",
      "language": {
        "name": "es",
        "url": "/api/v2/language/7/"
      }
    },
    {
      "name": "Tazza con fiamme",
      "language": {
        "name": "it",
        "url": "/api/v2/language/8/"
      }
    },
    {
      "name": "Fire Pattern Cup",
      "language": {
        "name": "en",
        "url": "/api/v2/language/9/"
      }
    },
    {
      "name": "ファイヤーカップ",
      "language": {
        "name": "ja",
        "url": "/api/v2/language/11/"
      }
    },
    {
      "name": "火焰水杯",
      "language": {
        "name": "zh-hans",
        "url": "/api/v2/language/12/"
      }
    }
  ],
  "held_by_pokemon": [],
  "sprites": {
    "default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/fire-pattern-cup.png"
  },
  "baby_trigger_for": null,
  "machines": []
}

=== PokeAPI/api-data/data/api/v2/item/2279/index.json
{
    "attributes": [],
    "baby_trigger_for": null,
    "category": {
        "name": "type-protection",
        "url": "/api/v2/item-category/7/"
    },
    "effect_entries": [],
    "flavor_text_entries": [],
    "fling_effect": null,
    "fling_power": 10,
    "game_indices": [],
    "held_by_pokemon": [],
    "id": 2279,
    "machines": [],
    "name": "roseli-berry",
    "names": [],
    "prices": [],
    "sprites": {
        "default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/roseli-berry.png"
    }
}

=== PokeAPI/api-data/data/api/v2/item/1329/index.json
{
  "id": 1329,
  "name": "rotom-catalog",
  "fling_power": null,
  "fling_effect": null,
  "attributes": [],
  "category": {
    "name": "gameplay",
    "url": "/api/v2/item-category/21/"
  },
  "effect_entries": [],
  "flavor_text_entries": [
    {
      "text": "ロトムが　すきな　かでんが　のっている。\nカタログを　つかうことで　ロトムを\nかでんに　いれたり　だすことが　できる。",
      "version_group": {
        "name": "sword-shield",
        "url": "/api/v2/version-group/20/"
      },
      "language": {
        "name": "ja-hrkt",
        "url": "/api/v2/language/1/"
      }
    },
    {
      "text": "로토무가 좋아하는 가전제품이 실려 있다.\n카탈로그를 사용하면 로토무를\n가전제품에 넣거나 꺼낼 수 있다.",
      "version_group": {
        "name": "sword-shield",
        "url": "/api/v2/version-group/20/"
      },
      "language": {
        "name": "ko",
        "url": "/api/v2/language/3/"
      }
    },
    {
      "text": "記載著洛托姆喜歡的電器。\n透過使用這本型錄，可以讓\n洛托姆進入或離開電器。",
      "version_group": {
        "name": "sword-shield",
        "url": "/api/v2/version-group/20/"
      },
      "language": {
        "name": "zh-hant",
        "url": "/api/v2/language/4/"
      }
    },
    {
      "text": "Un catalogue présentant divers appareils ménagers\nque Motisma apprécie. À utiliser pour faire entrer\nMotisma dans ces appareils ou l’en faire sortir.",
      "version_group": {
        "name": "sword-shield",
        "url": "/api/v2/version-group/20/"
      },
      "language": {
        "name": "fr",
        "url": "/api/v2/language/5/"
      }
    },
    {
      "text": "Ein Katalog, der Rotoms Lieblingsgeräte auflistet.\nMit diesem Katalog kann Rotom in Geräte schlüpfen\nund sie wieder verlassen.",
      "version_group": {
        "name": "sword-shield",
        "url": "/api/v2/version-group/20/"
      },
      "language": {
        "name": "de",
        "url": "/api/v2/language/6/"
      }
    },
    {
      "text": "Un catálogo de los artilugios favoritos de Rotom que le\npermite introducirse o salir fácilmente de los mismos.",
      "version_group": {
        "name": "sword-shield",
        "url": "/api/v2/version-group/20/"
      },
      "language": {
        "name": "es",
        "url": "/api/v2/language/7/"
      }
    },
    {
      "text": "Contiene una lista degli apparecchi che piacciono\na Rotom. Può essere usato per far entrare Rotom\nnel motore degli elettrodomestici o per farlo uscire.",
      "version_group": {
        "name": "sword-shield",
        "url": "/api/v2/version-group/20/"
      },
      "language": {
        "name": "it",
        "url": "/api/v2/language/8/"
      }
    },
    {
      "text": "A catalog of devices that Rotom like. Use the catalog\nto have Rotom hop in and out of the various devices\nlisted within.",
      "version_group": {
        "name": "sword-shield",
        "url": "/api/v2/version-group/20/"
      },
      "language": {
        "name": "en",
        "url": "/api/v2/language/9/"
      }
    },
    {
      "text": "ロトムが　好きな　家電が　載っている。\nカタログを　使うことで　ロトムを\n家電に　いれたり　だすことが　できる。",
      "version_group": {
        "name": "sword-shield",
        "url": "/api/v2/version-group/20/"
      },
      "language": {
        "name": "ja",
        "url": "/api/v2/language/11/"
      }
    },
    {
      "text": "上面记载着洛托姆喜欢的家电。\n通过使用这本指南，可以\n让洛托姆潜入或脱离家电。",
      "version_group": {
        "name": "sword-shield",
        "url": "/api/v2/version-group/20/"
      },
      "language": {
        "name": "zh-hans",
        "url": "/api/v2/language/12/"
      }
    },
    {
      "text": "Un catálogo de los artilugios favoritos de Rotom que le\npermite introducirse o salir fácilmente de los mismos.",
      "version_group": {
        "name": "sword-shield",
        "url": "/api/v2/version-group/20/"
      },
      "language": {
        "name": "es-419",
        "url": "/api/v2/language/14/"
      }
    }
  ],
  "game_indices": [
    {
      "game_index": 1278,
      "generation": {
        "name": "generation-viii",
        "url": "/api/v2/generation/8/"
      }
    },
    {
      "game_index": 1278,
      "generation": {
        "name": "generation-ix",
        "url": "/api/v2/generation/9/"
      }
    }
  ],
  "prices": [],
  "names": [
    {
      "name": "ロトムのカタログ",
      "language": {
        "name": "ja-hrkt",
        "url": "/api/v2/language/1/"
      }
    },
    {
      "name": "로토무카탈로그",
      "language": {
        "name": "ko",
        "url": "/api/v2/language/3/"
      }
    },
    {
      "name": "洛托姆型錄",
      "language": {
        "name": "zh-hant",
        "url": "/api/v2/language/4/"
      }
    },
    {
      "name": "Moti-Catalogue",
      "language": {
        "name": "fr",
        "url": "/api/v2/language/5/"
      }
    },
    {
      "name": "Rotom-Katalog",
      "language": {
        "name": "de",
        "url": "/api/v2/language/6/"
      }
    },
    {
      "name": "Catálogo Rotom",
      "language": {
        "name": "es",
        "url": "/api/v2/language/7/"
      }
    },
    {
      "name": "Catalogo Rotom",
      "language": {
        "name": "it",
        "url": "/api/v2/language/8/"
      }
    },
    {
      "name": "Rotom Catalog",
      "language": {
        "name": "en",
        "url": "/api/v2/language/9/"
      }
    },
    {
      "name": "ロトムのカタログ",
      "language": {
        "name": "ja",
        "url": "/api/v2/language/11/"
      }
    },
    {
      "name": "洛托姆型录",
      "language": {
        "name": "zh-hans",
        "url": "/api/v2/language/12/"
      }
    },
    {
      "name": "Catálogo Rotom",
      "language": {
        "name": "es-419",
        "url": "/api/v2/language/14/"
      }
    }
  ],
  "held_by_pokemon": [],
  "sprites": {
    "default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/rotom-catalog.png"
  },
  "baby_trigger_for": null,
  "machines": []
}

=== PokeAPI/api-data/data/api/v2/item/1250/index.json
{
  "id": 1250,
  "name": "tr62",
  "fling_power": 85,
  "fling_effect": null,
  "attributes": [],
  "category": {
    "name": "all-machines",
    "url": "/api/v2/item-category/37/"
  },
  "effect_entries": [],
  "flavor_text_entries": [
    {
      "text": "おおきな　くちから　しょうげきはを\nまきおこして　あいてを　こうげきする。",
      "version_group": {
        "name": "sword-shield",
        "url": "/api/v2/version-group/20/"
      },
      "language": {
        "name": "ja-hrkt",
        "url": "/api/v2/language/1/"
      }
    },
    {
      "text": "큰 입으로 충격파를\n일으켜서 상대를 공격한다.",
      "version_group": {
        "name": "sword-shield",
        "url": "/api/v2/version-group/20/"
      },
      "language": {
        "name": "ko",
        "url": "/api/v2/language/3/"
      }
    },
    {
      "text": "從張大的口中\n發射衝擊波攻擊對手。",
      "version_group": {
        "name": "sword-shield",
        "url": "/api/v2/version-group/20/"
      },
      "language": {
        "name": "zh-hant",
        "url": "/api/v2/language/4/"
      }
    },
    {
      "text": "Le lanceur ouvre la bouche pour envoyer\nune onde de choc qui frappe l’ennemi.",
      "version_group": {
        "name": "sword-shield",
        "url": "/api/v2/version-group/20/"
      },
      "language": {
        "name": "fr",
        "url": "/api/v2/language/5/"
      }
    },
    {
      "text": "Das Ziel wird mit einer Schockwelle angegriffen,\ndie aus dem offenen Maul des Anwenders kommt.",
      "version_group": {
        "name": "sword-shield",
        "url": "/api/v2/version-group/20/"
      },
      "language": {
        "name": "de",
        "url": "/api/v2/language/6/"
      }
    },
    {
      "text": "Abre mucho la boca y libera una onda de choque que\nataca al objetivo.",
      "version_group": {
        "name": "sword-shield",
        "url": "/api/v2/version-group/20/"
      },
      "language": {
        "name": "es",
        "url": "/api/v2/language/7/"
      }
    },
    {
      "text": "Chi la usa spalanca la bocca e genera un’onda\nd’urto che colpisce il bersaglio.",
      "version_group": {
        "name": "sword-shield",
        "url": "/api/v2/version-group/20/"
      },
      "language": {
        "name": "it",
        "url": "/api/v2/language/8/"
      }
    },
    {
      "text": "The target is attacked with a shock wave generated\nby the user’s gaping mouth.",
      "version_group": {
        "name": "sword-shield",
        "url": "/api/v2/version-group/20/"
      },
      "language": {
        "name": "en",
        "url": "/api/v2/language/9/"
      }
    },
    {
      "text": "大きな　口から　衝撃波を\nまきおこして　相手を　攻撃する。",
      "version_group": {
        "name": "sword-shield",
        "url": "/api/v2/version-group/20/"
      },
      "language": {
        "name": "ja",
        "url": "/api/v2/language/11/"
      }
    },
    {
      "text": "从大大的口中\n掀起冲击波攻击对手。",
      "version_group": {
        "name": "sword-shield",
        "url": "/api/v2/version-group/20/"
      },
      "language": {
        "name": "zh-hans",
        "url": "/api/v2/language/12/"
      }
    },
    {
      "text": "Abre mucho la boca y libera una onda de choque que\nataca al objetivo.",
      "version_group": {
        "name": "sword-shield",
        "url": "/api/v2/version-group/20/"
      },
      "language": {
        "name": "es-419",
        "url": "/api/v2/language/14/"
      }
    }
  ],
  "game_indices": [
    {
      "game_index": 1192,
      "generation": {
        "name": "generation-viii",
        "url": "/api/v2/generation/8/"
      }
    },
    {
      "game_index": 1192,
      "generation": {
        "name": "generation-ix",
        "url": "/api/v2/generation/9/"
      }
    }
  ],
  "prices": [],
  "names": [
    {
      "name": "わざレコード６２",
      "language": {
        "name": "ja-hrkt",
        "url": "/api/v2/language/1/"
      }
    },
    {
      "name": "기술레코드62",
      "language": {
        "name": "ko",
        "url": "/api/v2/language/3/"
      }
    },
    {
      "name": "招式紀錄６２",
      "language": {
        "name": "zh-hant",
        "url": "/api/v2/language/4/"
      }
    },
    {
      "name": "DT62",
      "language": {
        "name": "fr",
        "url": "/api/v2/language/5/"
      }
    },
    {
      "name": "TP62",
      "language": {
        "name": "de",
        "url": "/api/v2/language/6/"
      }
    },
    {
      "name": "DT62",
      "language": {
        "name": "es",
        "url": "/api/v2/language/7/"
      }
    },
    {
      "name": "DT62",
      "language": {
        "name": "it",
        "url": "/api/v2/language/8/"
      }
    },
    {
      "name": "TR62",
      "language": {
        "name": "en",
        "url": "/api/v2/language/9/"
      }
    },
    {
      "name": "わざレコード６２",
      "language": {
        "name": "ja",
        "url": "/api/v2/language/11/"
      }
    },
    {
      "name": "招式记录６２",
      "language": {
        "name": "zh-hans",
        "url": "/api/v2/language/12/"
      }
    },
    {
      "name": "DT62",
      "language": {
        "name": "es-419",
        "url": "/api/v2/language/14/"
      }
    }
  ],
  "held_by_pokemon": [],
  "sprites": {
    "default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/tr62.png"
  },
  "baby_trigger_for": null,
  "machines": [
    {
      "machine": {
        "url": "/api/v2/machine/1761/"
      },
      "version_group": {
        "name": "sword-shield",
        "url": "/api/v2/version-group/20/"
      }
    }
  ]
}
