=== PokeAPI/api-data/data/schema/v2/item/$id/index.json
{
  "$schema": "http://json-schema.org/schema#",
  "type": "object",
  "properties": {
    "id": {
      "type": "integer"
    },
    "name": {
      "type": "string"
    },
    "fling_power": {
      "type": [
        "integer",
        "null"
      ]
    },
    "fling_effect": {
      "anyOf": [
        {
          "type": "null"
        },
        {
          "$ref": "/schema/v2/named_api_resource.json"
        }
      ]
    },
    "attributes": {
      "type": "array",
      "items": {
        "$ref": "/schema/v2/named_api_resource.json"
      }
    },
    "category": {
      "$ref": "/schema/v2/named_api_resource.json"
    },
    "effect_entries": {
      "type": "array",
      "items": {
        "$ref": "/schema/v2/verbose_effect.json"
      }
    },
    "flavor_text_entries": {
      "type": "array",
      "items": {
        "$ref": "/schema/v2/version_group_flavor_text.json"
      }
    },
    "game_indices": {
      "type": "array",
      "items": {
        "$ref": "/schema/v2/generation_game_index.json"
      }
    },
    "prices": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "purchase_price": {
            "type": [
              "integer",
              "null"
            ]
          },
          "sell_price": {
            "type": [
              "integer",
              "null"
            ]
          },
          "currency": {
            "$ref": "/schema/v2/named_api_resource.json"
          },
          "version_group": {
            "$ref": "/schema/v2/named_api_resource.json"
          }
        },
        "required": [
          "currency",
          "purchase_price",
          "sell_price",
          "version_group"
        ]
      }
    },
    "names": {
      "type": "array",
      "items": {
        "$ref": "/schema/v2/name.json"
      }
    },
    "held_by_pokemon": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "pokemon": {
            "$ref": "/schema/v2/named_api_resource.json"
          },
          "version_details": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "rarity": {
                  "type": "integer"
                },
                "version": {
                  "$ref": "/schema/v2/named_api_resource.json"
                }
              },
              "required": [
                "rarity",
                "version"
              ]
            }
          }
        },
        "required": [
          "pokemon",
          "version_details"
        ]
      }
    },
    "sprites": {
      "type": "object",
      "properties": {
        "default": {
          "type": "string"
        }
      },
      "required": [
        "default"
      ]
    },
    "baby_trigger_for": {
      "anyOf": [
        {
          "type": "null"
        },
        {
          "$ref": "/schema/v2/api_resource.json"
        }
      ]
    },
    "machines": {
      "type": "array",
      "items": {
        "$ref": "/schema/v2/machine_version_detail.json"
      }
    }
  },
  "required": [
    "attributes",
    "baby_trigger_for",
    "category",
    "effect_entries",
    "flavor_text_entries",
    "fling_effect",
    "fling_power",
    "game_indices",
    "held_by_pokemon",
    "id",
    "machines",
    "name",
    "names",
    "prices",
    "sprites"
  ]
}

=== PokeAPI/api-data/data/api/v2/item/1818/index.json
{
  "id": 1818,
  "name": "shuppet-scrap",
  "fling_power": null,
  "fling_effect": null,
  "attributes": [],
  "category": {
    "name": "tm-materials",
    "url": "/api/v2/item-category/54/"
  },
  "effect_entries": [],
  "flavor_text_entries": [],
  "game_indices": [
    {
      "game_index": 2012,
      "generation": {
        "name": "generation-ix",
        "url": "/api/v2/generation/9/"
      }
    }
  ],
  "prices": [],
  "names": [
    {
      "name": "カゲボウズのきれはし",
      "language": {
        "name": "ja-hrkt",
        "url": "/api/v2/language/1/"
      }
    },
    {
      "name": "어둠대신의천조각",
      "language": {
        "name": "ko",
        "url": "/api/v2/language/3/"
      }
    },
    {
      "name": "怨影娃娃的殘片",
      "language": {
        "name": "zh-hant",
        "url": "/api/v2/language/4/"
      }
    },
    {
      "name": "Tissu de Polichombr",
      "language": {
        "name": "fr",
        "url": "/api/v2/language/5/"
      }
    },
    {
      "name": "Shuppet-Fetzen",
      "language": {
        "name": "de",
        "url": "/api/v2/language/6/"
      }
    },
    {
      "name": "Retal de Shuppet",
      "language": {
        "name": "es",
        "url": "/api/v2/language/7/"
      }
    },
    {
      "name": "Brandello di Shuppet",
      "language": {
        "name": "it",
        "url": "/api/v2/language/8/"
      }
    },
    {
      "name": "Shuppet Scrap",
      "language": {
        "name": "en",
        "url": "/api/v2/language/9/"
      }
    },
    {
      "name": "カゲボウズのきれはし",
      "language": {
        "name": "ja",
        "url": "/api/v2/language/11/"
      }
    },
    {
      "name": "怨影娃娃的残片",
      "language": {
        "name": "zh-hans",
        "url": "/api/v2/language/12/"
      }
    }
  ],
  "held_by_pokemon": [],
  "sprites": {
    "default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/shuppet-scrap.png"
  },
  "baby_trigger_for": null,
  "machines": []
}

=== PokeAPI/api-data/data/api/v2/item/1933/index.json
{
  "id": 1933,
  "name": "glimmet-crystal",
  "fling_power": null,
  "fling_effect": null,
  "attributes": [],
  "category": {
    "name": "tm-materials",
    "url": "/api/v2/item-category/54/"
  },
  "effect_entries": [],
  "flavor_text_entries": [],
  "game_indices": [
    {
      "game_index": 2132,
      "generation": {
        "name": "generation-ix",
        "url": "/api/v2/generation/9/"
      }
    }
  ],
  "prices": [],
  "names": [
    {
      "name": "キラーメのけっしょう",
      "language": {
        "name": "ja-hrkt",
        "url": "/api/v2/language/1/"
      }
    },
    {
      "name": "초롱순의결정",
      "language": {
        "name": "ko",
        "url": "/api/v2/language/3/"
      }
    },
    {
      "name": "晶光芽的結晶",
      "language": {
        "name": "zh-hant",
        "url": "/api/v2/language/4/"
      }
    },
    {
      "name": "Cristal de Germéclat",
      "language": {
        "name": "fr",
        "url": "/api/v2/language/5/"
      }
    },
    {
      "name": "Lumispross-Kristall",
      "language": {
        "name": "de",
        "url": "/api/v2/language/6/"
      }
    },
    {
      "name": "Cristal de Glimmet",
      "language": {
        "name": "es",
        "url": "/api/v2/language/7/"
      }
    },
    {
      "name": "Cristallo di Glimmet",
      "language": {
        "name": "it",
        "url": "/api/v2/language/8/"
      }
    },
    {
      "name": "Glimmet Crystal",
      "language": {
        "name": "en",
        "url": "/api/v2/language/9/"
      }
    },
    {
      "name": "キラーメのけっしょう",
      "language": {
        "name": "ja",
        "url": "/api/v2/language/11/"
      }
    },
    {
      "name": "晶光芽的结晶",
      "language": {
        "name": "zh-hans",
        "url": "/api/v2/language/12/"
      }
    }
  ],
  "held_by_pokemon": [],
  "sprites": {
    "default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/glimmet-crystal.png"
  },
  "baby_trigger_for": null,
  "machines": []
}

=== PokeAPI/api-data/data/api/v2/item/2137/index.json
{
  "id": 2137,
  "name": "lotad-leaf",
  "fling_power": null,
  "fling_effect": null,
  "attributes": [],
  "category": {
    "name": "tm-materials",
    "url": "/api/v2/item-category/54/"
  },
  "effect_entries": [],
  "flavor_text_entries": [],
  "game_indices": [
    {
      "game_index": 2456,
      "generation": {
        "name": "generation-ix",
        "url": "/api/v2/generation/9/"
      }
    }
  ],
  "prices": [],
  "names": [
    {
      "name": "ハスボーのはっぱ",
      "language": {
        "name": "ja-hrkt",
        "url": "/api/v2/language/1/"
      }
    },
    {
      "name": "연꽃몬의잎",
      "language": {
        "name": "ko",
        "url": "/api/v2/language/3/"
      }
    },
    {
      "name": "蓮葉童子的葉片",
      "language": {
        "name": "zh-hant",
        "url": "/api/v2/language/4/"
      }
    },
    {
      "name": "Feuille de Nénupiot",
      "language": {
        "name": "fr",
        "url": "/api/v2/language/5/"
      }
    },
    {
      "name": "Loturzel-Blatt",
      "language": {
        "name": "de",
        "url": "/api/v2/language/6/"
      }
    },
    {
      "name": "Hoja de Lotad",
      "language": {
        "name": "es",
        "url": "/api/v2/language/7/"
      }
    },
    {
      "name": "Foglia di Lotad",
      "language": {
        "name": "it",
        "url": "/api/v2/language/8/"
      }
    },
    {
      "name": "Lotad Leaf",
      "language": {
        "name": "en",
        "url": "/api/v2/language/9/"
      }
    },
    {
      "name": "ハスボーのはっぱ",
      "language": {
        "name": "ja",
        "url": "/api/v2/language/11/"
      }
    },
    {
      "name": "莲叶童子的叶片",
      "language": {
        "name": "zh-hans",
        "url": "/api/v2/language/12/"
      }
    }
  ],
  "held_by_pokemon": [],
  "sprites": {
    "default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/lotad-leaf.png"
  },
  "baby_trigger_for": null,
  "machines": []
}

=== PokeAPI/api-data/data/api/v2/item/1179/index.json
{
  "id": 1179,
  "name": "blunder-policy",
  "fling_power": 80,
  "fling_effect": null,
  "attributes": [],
  "category": {
    "name": "held-items",
    "url": "/api/v2/item-category/12/"
  },
  "effect_entries": [],
  "flavor_text_entries": [
    {
      "text": "めいちゅうりつに　よって\nわざが　はずれたとき\nすばやさが　ぐーんと　あがる。",
      "version_group": {
        "name": "sword-shield",
        "url": "/api/v2/version-group/20/"
      },
      "language": {
        "name": "ja-hrkt",
        "url": "/api/v2/language/1/"
      }
    },
    {
      "text": "명중률에 의해\n기술이 빗나갔을 때\n스피드가 크게 올라간다.",
      "version_group": {
        "name": "sword-shield",
        "url": "/api/v2/version-group/20/"
      },
      "language": {
        "name": "ko",
        "url": "/api/v2/language/3/"
      }
    },
    {
      "text": "當招式受命中率影響\n而未能擊中對手時，\n自己的速度將大幅提高。",
      "version_group": {
        "name": "sword-shield",
        "url": "/api/v2/version-group/20/"
      },
      "language": {
        "name": "zh-hant",
        "url": "/api/v2/language/4/"
      }
    },
    {
      "text": "Si un Pokémon manque sa cible parce qu’une capacité\na peu de Précision, sa Vitesse augmente beaucoup.",
      "version_group": {
        "name": "sword-shield",
        "url": "/api/v2/version-group/20/"
      },
      "language": {
        "name": "fr",
        "url": "/api/v2/language/5/"
      }
    },
    {
      "text": "Schlägt eine Attacke des Anwenders mangels\nGenauigkeit fehl, steigt im Gegenzug dessen\nInitiative stark an.",
      "version_group": {
        "name": "sword-shield",
        "url": "/api/v2/version-group/20/"
      },
      "language": {
        "name": "de",
        "url": "/api/v2/language/6/"
      }
    },
    {
      "text": "Aumenta mucho la Velocidad cuando el Pokémon yerra\nel movimiento debido a la precisión.",
      "version_group": {
        "name": "sword-shield",
        "url": "/api/v2/version-group/20/"
      },
      "language": {
        "name": "es",
        "url": "/api/v2/language/7/"
      }
    },
    {
      "text": "Se una mossa non va a segno a causa della scarsa\nprecisione, la Velocità aumenta considerevolmente.",
      "version_group": {
        "name": "sword-shield",
        "url": "/api/v2/version-group/20/"
      },
      "language": {
        "name": "it",
        "url": "/api/v2/language/8/"
      }
    },
    {
      "text": "Raises Speed sharply when a Pokémon misses with a\nmove because of accuracy.",
      "version_group": {
        "name": "sword-shield",
        "url": "/api/v2/version-group/20/"
      },
      "language": {
        "name": "en",
        "url": "/api/v2/language/9/"
      }
    },
    {
      "text": "命中率に　よって\n技が　はずれたとき\n素早さが　ぐーんと　上がる。",
      "version_group": {
        "name": "sword-shield",
        "url": "/api/v2/version-group/20/"
      },
      "language": {
        "name": "ja",
        "url": "/api/v2/language/11/"
      }
    },
    {
      "text": "招式因命中率影响而落空时，\n速度会大幅提高。",
      "version_group": {
        "name": "sword-shield",
        "url": "/api/v2/version-group/20/"
      },
      "language": {
        "name": "zh-hans",
        "url": "/api/v2/language/12/"
      }
    },
    {
      "text": "Aumenta mucho la Velocidad cuando el Pokémon yerra\nel movimiento debido a la precisión.",
      "version_group": {
        "name": "sword-shield",
        "url": "/api/v2/version-group/20/"
      },
      "language": {
        "name": "es-419",
        "url": "/api/v2/language/14/"
      }
    }
  ],
  "game_indices": [
    {
      "game_index": 1121,
      "generation": {
        "name": "generation-viii",
        "url": "/api/v2/generation/8/"
      }
    },
    {
      "game_index": 1121,
      "generation": {
        "name": "generation-ix",
        "url": "/api/v2/generation/9/"
      }
    }
  ],
  "prices": [],
  "names": [
    {
      "name": "からぶりほけん",
      "language": {
        "name": "ja-hrkt",
        "url": "/api/v2/language/1/"
      }
    },
    {
      "name": "허탕보험",
      "language": {
        "name": "ko",
        "url": "/api/v2/language/3/"
      }
    },
    {
      "name": "打空保險",
      "language": {
        "name": "zh-hant",
        "url": "/api/v2/language/4/"
      }
    },
    {
      "name": "Assurance Échec",
      "language": {
        "name": "fr",
        "url": "/api/v2/language/5/"
      }
    },
    {
      "name": "Fehlschlagschutz",
      "language": {
        "name": "de",
        "url": "/api/v2/language/6/"
      }
    },
    {
      "name": "Seguro Fallo",
      "language": {
        "name": "es",
        "url": "/api/v2/language/7/"
      }
    },
    {
      "name": "Fiascopolizza",
      "language": {
        "name": "it",
        "url": "/api/v2/language/8/"
      }
    },
    {
      "name": "Blunder Policy",
      "language": {
        "name": "en",
        "url": "/api/v2/language/9/"
      }
    },
    {
      "name": "からぶりほけん",
      "language": {
        "name": "ja",
        "url": "/api/v2/language/11/"
      }
    },
    {
      "name": "打空保险",
      "language": {
        "name": "zh-hans",
        "url": "/api/v2/language/12/"
      }
    },
    {
      "name": "Seguro Fallo",
      "language": {
        "name": "es-419",
        "url": "/api/v2/language/14/"
      }
    }
  ],
  "held_by_pokemon": [],
  "sprites": {
    "default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/blunder-policy.png"
  },
  "baby_trigger_for": null,
  "machines": []
}

=== PokeAPI/api-data/data/api/v2/item/2115/index.json
{
  "id": 2115,
  "name": "genius-mochi",
  "fling_power": null,
  "fling_effect": null,
  "attributes": [],
  "category": {
    "name": "vitamins",
    "url": "/api/v2/item-category/26/"
  },
  "effect_entries": [],
  "flavor_text_entries": [],
  "game_indices": [
    {
      "game_index": 2414,
      "generation": {
        "name": "generation-ix",
        "url": "/api/v2/generation/9/"
      }
    }
  ],
  "prices": [],
  "names": [
    {
      "name": "ちりょくのもち",
      "language": {
        "name": "ja-hrkt",
        "url": "/api/v2/language/1/"
      }
    },
    {
      "name": "지력떡",
      "language": {
        "name": "ko",
        "url": "/api/v2/language/3/"
      }
    },
    {
      "name": "智力糬",
      "language": {
        "name": "zh-hant",
        "url": "/api/v2/language/4/"
      }
    },
    {
      "name": "Mochi Esprit",
      "language": {
        "name": "fr",
        "url": "/api/v2/language/5/"
      }
    },
    {
      "name": "Genie-Mochi",
      "language": {
        "name": "de",
        "url": "/api/v2/language/6/"
      }
    },
    {
      "name": "Mochi Intelecto",
      "language": {
        "name": "es",
        "url": "/api/v2/language/7/"
      }
    },
    {
      "name": "Mochi dell’ingegno",
      "language": {
        "name": "it",
        "url": "/api/v2/language/8/"
      }
    },
    {
      "name": "Genius Mochi",
      "language": {
        "name": "en",
        "url": "/api/v2/language/9/"
      }
    },
    {
      "name": "ちりょくのもち",
      "language": {
        "name": "ja",
        "url": "/api/v2/language/11/"
      }
    },
    {
      "name": "智力粘糕",
      "language": {
        "name": "zh-hans",
        "url": "/api/v2/language/12/"
      }
    }
  ],
  "held_by_pokemon": [],
  "sprites": {
    "default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/genius-mochi.png"
  },
  "baby_trigger_for": null,
  "machines": []
}

=== PokeAPI/api-data/data/api/v2/item/1018/index.json
{
  "id": 1018,
  "name": "silver-pinap-berry",
  "fling_power": 10,
  "fling_effect": null,
  "attributes": [],
  "category": {
    "name": "catching-bonus",
    "url": "/api/v2/item-category/48/"
  },
  "effect_entries": [],
  "flavor_text_entries": [
    {
      "text": "ポケモンに　あたえると\nつかまえた　ときに　どうぐが\nてにはいり　やすくなる　きのみ。",
      "version_group": {
        "name": "lets-go-pikachu-lets-go-eevee",
        "url": "/api/v2/version-group/19/"
      },
      "language": {
        "name": "ja-hrkt",
        "url": "/api/v2/language/1/"
      }
    },
    {
      "text": "포켓몬에게 주면\n잡았을 때 도구를 손에 넣기\n쉬워지는 나무열매.",
      "version_group": {
        "name": "lets-go-pikachu-lets-go-eevee",
        "url": "/api/v2/version-group/19/"
      },
      "language": {
        "name": "ko",
        "url": "/api/v2/language/3/"
      }
    },
    {
      "text": "把這個樹果餵給寶可夢，\n在捕捉成功後，\n會更容易獲得道具。",
      "version_group": {
        "name": "lets-go-pikachu-lets-go-eevee",
        "url": "/api/v2/version-group/19/"
      },
      "language": {
        "name": "zh-hant",
        "url": "/api/v2/language/4/"
      }
    },
    {
      "text": "Une Baie à donner à un Pokémon sauvage pour avoir\nplus de chances d’obtenir un objet après l’avoir capturé.",
      "version_group": {
        "name": "lets-go-pikachu-lets-go-eevee",
        "url": "/api/v2/version-group/19/"
      },
      "language": {
        "name": "fr",
        "url": "/api/v2/language/5/"
      }
    },
    {
      "text": "Gibst du diese Beere einem Pokémon zu essen, wird die\nChance, bei einem erfolgreichen Fangversuch ein Item\nzu erhalten, erhöht.",
      "version_group": {
        "name": "lets-go-pikachu-lets-go-eevee",
        "url": "/api/v2/version-group/19/"
      },
      "language": {
        "name": "de",
        "url": "/api/v2/language/6/"
      }
    },
    {
      "text": "Una baya que puedes lanzar a un Pokémon salvaje\npara aumentar bastante las probabilidades de conseguir\nun objeto tras capturarlo.",
      "version_group": {
        "name": "lets-go-pikachu-lets-go-eevee",
        "url": "/api/v2/version-group/19/"
      },
      "language": {
        "name": "es",
        "url": "/api/v2/language/7/"
      }
    },
    {
      "text": "Bacca che rende più facile ottenere strumenti\nquando catturi il Pokémon a cui l’hai data.",
      "version_group": {
        "name": "lets-go-pikachu-lets-go-eevee",
        "url": "/api/v2/version-group/19/"
      },
      "language": {
        "name": "it",
        "url": "/api/v2/language/8/"
      }
    },
    {
      "text": "A Berry that makes you more likely to get an item when\ngiven to Pokémon you’re trying to catch.",
      "version_group": {
        "name": "lets-go-pikachu-lets-go-eevee",
        "url": "/api/v2/version-group/19/"
      },
      "language": {
        "name": "en",
        "url": "/api/v2/language/9/"
      }
    },
    {
      "text": "ポケモンに　あたえると\n捕まえた　ときに　道具が\n手にはいり　やすくなる　きのみ。",
      "version_group": {
        "name": "lets-go-pikachu-lets-go-eevee",
        "url": "/api/v2/version-group/19/"
      },
      "language": {
        "name": "ja",
        "url": "/api/v2/language/11/"
      }
    },
    {
      "text": "如果把这树果交给宝可梦，\n那么接下来捉住该宝可梦时，\n会更容易获得道具。",
      "version_group": {
        "name": "lets-go-pikachu-lets-go-eevee",
        "url": "/api/v2/version-group/19/"
      },
      "language": {
        "name": "zh-hans",
        "url": "/api/v2/language/12/"
      }
    },
    {
      "text": "Una baya que puedes lanzar a un Pokémon salvaje\npara aumentar bastante las probabilidades de conseguir\nun objeto tras capturarlo.",
      "version_group": {
        "name": "lets-go-pikachu-lets-go-eevee",
        "url": "/api/v2/version-group/19/"
      },
      "language": {
        "name": "es-419",
        "url": "/api/v2/language/14/"
      }
    },
    {
      "text": "ポケモンに　あたえると\nつかまえた　ときに　どうぐが\nてにはいり　やすくなる　きのみ。",
      "version_group": {
        "name": "sword-shield",
        "url": "/api/v2/version-group/20/"
      },
      "language": {
        "name": "ja-hrkt",
        "url": "/api/v2/language/1/"
      }
    },
    {
      "text": "포켓몬에게 주면\n잡았을 때 도구를 손에 넣기\n쉬워지는 나무열매.",
      "version_group": {
        "name": "sword-shield",
        "url": "/api/v2/version-group/20/"
      },
      "language": {
        "name": "ko",
        "url": "/api/v2/language/3/"
      }
    },
    {
      "text": "把這個樹果餵給寶可夢，\n在捕捉成功後，\n會更容易獲得道具。",
      "version_group": {
        "name": "sword-shield",
        "url": "/api/v2/version-group/20/"
      },
      "language": {
        "name": "zh-hant",
        "url": "/api/v2/language/4/"
      }
    },
    {
      "text": "Une Baie à donner à un Pokémon sauvage pour avoir\nplus de chances d’obtenir un objet après l’avoir capturé.",
      "version_group": {
        "name": "sword-shield",
        "url": "/api/v2/version-group/20/"
      },
      "language": {
        "name": "fr",
        "url": "/api/v2/language/5/"
      }
    },
    {
      "text": "Gibst du diese Beere einem Pokémon zu essen, wird die\nChance, bei einem erfolgreichen Fangversuch ein Item\nzu erhalten, erhöht.",
      "version_group": {
        "name": "sword-shield",
        "url": "/api/v2/version-group/20/"
      },
      "language": {
        "name": "de",
        "url": "/api/v2/language/6/"
      }
    },
    {
      "text": "Una baya que puedes lanzar a un Pokémon salvaje\npara aumentar bastante las probabilidades de conseguir\nun objeto tras capturarlo.",
      "version_group": {
        "name": "sword-shield",
        "url": "/api/v2/version-group/20/"
      },
      "language": {
        "name": "es",
        "url": "/api/v2/language/7/"
      }
    },
    {
      "text": "Bacca che rende più facile ottenere strumenti\nquando catturi il Pokémon a cui l’hai data.",
      "version_group": {
        "name": "sword-shield",
        "url": "/api/v2/version-group/20/"
      },
      "language": {
        "name": "it",
        "url": "/api/v2/language/8/"
      }
    },
    {
      "text": "A Berry that makes you more likely to get an item when\ngiven to Pokémon you’re trying to catch.",
      "version_group": {
        "name": "sword-shield",
        "url": "/api/v2/version-group/20/"
      },
      "language": {
        "name": "en",
        "url": "/api/v2/language/9/"
      }
    },
    {
      "text": "ポケモンに　あたえると\n捕まえた　ときに　道具が\n手にはいり　やすくなる　きのみ。",
      "version_group": {
        "name": "sword-shield",
        "url": "/api/v2/version-group/20/"
      },
      "language": {
        "name": "ja",
        "url": "/api/v2/language/11/"
      }
    },
    {
      "text": "如果把这树果交给宝可梦，\n那么接下来捉住该宝可梦时，\n会更容易获得道具。",
      "version_group": {
        "name": "sword-shield",
        "url": "/api/v2/version-group/20/"
      },
      "language": {
        "name": "zh-hans",
        "url": "/api/v2/language/12/"
      }
    },
    {
      "text": "Una baya que puedes lanzar a un Pokémon salvaje\npara aumentar bastante las probabilidades de conseguir\nun objeto tras capturarlo.",
      "version_group": {
        "name": "sword-shield",
        "url": "/api/v2/version-group/20/"
      },
      "language": {
        "name": "es-419",
        "url": "/api/v2/language/14/"
      }
    }
  ],
  "game_indices": [
    {
      "game_index": 865,
      "generation": {
        "name": "generation-vii",
        "url": "/api/v2/generation/7/"
      }
    },
    {
      "game_index": 865,
      "generation": {
        "name": "generation-viii",
        "url": "/api/v2/generation/8/"
      }
    },
    {
      "game_index": 865,
      "generation": {
        "name": "generation-ix",
        "url": "/api/v2/generation/9/"
      }
    }
  ],
  "prices": [],
  "names": [
    {
      "name": "ぎんのパイルのみ",
      "language": {
        "name": "ja-hrkt",
        "url": "/api/v2/language/1/"
      }
    },
    {
      "name": "은 파인열매",
      "language": {
        "name": "ko",
        "url": "/api/v2/language/3/"
      }
    },
    {
      "name": "銀色凰梨果",
      "language": {
        "name": "zh-hant",
        "url": "/api/v2/language/4/"
      }
    },
    {
      "name": "Baie Nanana argentée",
      "language": {
        "name": "fr",
        "url": "/api/v2/language/5/"
      }
    },
    {
      "name": "Silberne Sananabeere",
      "language": {
        "name": "de",
        "url": "/api/v2/language/6/"
      }
    },
    {
      "name": "Baya Pinia Plateada",
      "language": {
        "name": "es",
        "url": "/api/v2/language/7/"
      }
    },
    {
      "name": "Baccananas argentata",
      "language": {
        "name": "it",
        "url": "/api/v2/language/8/"
      }
    },
    {
      "name": "Silver Pinap Berry",
      "language": {
        "name": "en",
        "url": "/api/v2/language/9/"
      }
    },
    {
      "name": "ぎんのパイルのみ",
      "language": {
        "name": "ja",
        "url": "/api/v2/language/11/"
      }
    },
    {
      "name": "银色凰梨果",
      "language": {
        "name": "zh-hans",
        "url": "/api/v2/language/12/"
      }
    },
    {
      "name": "Baya Pinia Plateada",
      "language": {
        "name": "es-419",
        "url": "/api/v2/language/14/"
      }
    }
  ],
  "held_by_pokemon": [],
  "sprites": {
    "default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/silver-pinap-berry.png"
  },
  "baby_trigger_for": null,
  "machines": []
}
